# Topic Modeling of Policy-Cited Literature

This notebook performs topic modeling on the cleaned publication
datasets produced by the data-preparation workflow.

The analysis includes text preprocessing, document-term matrix
construction, LDA model selection, final topic estimation, topic
interpretation, prevalence analysis, and temporal analysis.

In [16]:
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
import subprocess
import tempfile

# Project directories
NOTEBOOK_DIR = Path.cwd()

if NOTEBOOK_DIR.name == "notebooks":
    PROJECT_DIR = NOTEBOOK_DIR.parent
else:
    PROJECT_DIR = NOTEBOOK_DIR

DATA_DIR = PROJECT_DIR / "data"
OUTPUT_DIR = PROJECT_DIR / "output"

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

print("Project directory :", PROJECT_DIR)
print("Data directory    :", DATA_DIR)
print("Output directory  :", OUTPUT_DIR)

Project directory : /nfs/mfirdausi/project/review_paper_2
Data directory    : /nfs/mfirdausi/project/review_paper_2/data
Output directory  : /nfs/mfirdausi/project/review_paper_2/output

## 1. Load Cleaned Publication Data

The cleaned Overton and Scopus publication datasets produced by the
data-preparation notebook are loaded separately. The two sources are
retained as distinct datasets rather than merged.

In [17]:
OVERTON_FILE = (
    DATA_DIR / "overton_full_clean.xlsx"
)

SCOPUS_FILE = (
    DATA_DIR / "scopus_full_clean.xlsx"
)

overton = pd.read_excel(
    OVERTON_FILE
)

scopus = pd.read_excel(
    SCOPUS_FILE
)

print("Overton")
print("-------")
print(f"Documents : {len(overton):,}")
print(f"Columns   : {len(overton.columns):,}")

print("\nScopus")
print("------")
print(f"Documents : {len(scopus):,}")
print(f"Columns   : {len(scopus.columns):,}")

Overton
-------
Documents : 14,266
Columns   : 21

Scopus
------
Documents : 16,403
Columns   : 18

### 1.1 Define the Independent Topic-Modeling Corpora

The Overton and Scopus publication collections are analyzed as
independent corpora. Each corpus therefore receives its own text
preprocessing, document-term matrix, LDA model-selection procedure,
final topic model, and downstream topic analysis.

In [19]:
corpora = {
    "overton": overton.copy(),
    "scopus": scopus.copy(),
}

for corpus_name, corpus_df in corpora.items():

    print(f"{corpus_name.upper()}")
    print("-" * len(corpus_name))

    print(
        f"Documents          : "
        f"{len(corpus_df):,}"
    )

    print(
        f"Non-missing titles : "
        f"{corpus_df['Title'].notna().sum():,}"
    )

    print(
        f"Non-missing abstracts: "
        f"{corpus_df['Abstract'].notna().sum():,}"
    )

    print(
        f"Missing abstracts  : "
        f"{corpus_df['Abstract'].isna().sum():,}"
    )

    print()

OVERTON
-------
Documents          : 14,266
Non-missing titles : 14,266
Non-missing abstracts: 14,264
Missing abstracts  : 2

SCOPUS
------
Documents          : 16,403
Non-missing titles : 16,403
Non-missing abstracts: 16,403
Missing abstracts  : 0

## 2. Prepare Corpora for Topic Modeling

Topic modeling is performed independently for the Overton and Scopus
datasets. Publications without abstracts are excluded because the LDA
models are estimated from abstract text.

In [20]:
lda_corpora = {}

for corpus_name, corpus_df in corpora.items():

    lda_df = (
        corpus_df[
            corpus_df["Abstract"].notna()
        ]
        .copy()
        .reset_index(drop=True)
    )

    # Remove abstracts that are empty after whitespace stripping.
    lda_df["Abstract"] = (
        lda_df["Abstract"]
        .astype(str)
        .str.strip()
    )

    lda_df = (
        lda_df[
            lda_df["Abstract"] != ""
        ]
        .reset_index(drop=True)
    )

    lda_corpora[corpus_name] = lda_df

    print(corpus_name.upper())
    print("-" * len(corpus_name))
    print(
        f"Input publications : "
        f"{len(corpus_df):,}"
    )
    print(
        f"LDA documents      : "
        f"{len(lda_df):,}"
    )
    print(
        f"Excluded           : "
        f"{len(corpus_df) - len(lda_df):,}"
    )
    print()

OVERTON
-------
Input publications : 14,266
LDA documents      : 14,264
Excluded           : 2

SCOPUS
------
Input publications : 16,403
LDA documents      : 16,403
Excluded           : 0

### 2.1 Corpus Relevance Diagnostic

Before topic modeling, the retrieved publications are screened
diagnostically for terminology associated with electrical power and
energy systems. This step evaluates whether the search results contain
substantial off-domain literature that could distort the latent topic
structure.

In [21]:
POWER_DOMAIN_TERMS = [
    r"\bpower system",
    r"\bpower systems",
    r"\belectric power",
    r"\belectrical power",
    r"\bpower grid",
    r"\belectric grid",
    r"\belectrical grid",
    r"\bsmart grid",
    r"\bmicrogrid",
    r"\bmicro-grid",
    r"\btransmission system",
    r"\bdistribution system",
    r"\bpower network",
    r"\belectricity",
    r"\bvoltage",
    r"\breactive power",
    r"\bactive power",
    r"\boptimal power flow",
    r"\bload flow",
    r"\bpower flow",
]

power_pattern = re.compile(
    "|".join(POWER_DOMAIN_TERMS),
    flags=re.IGNORECASE,
)

for corpus_name, corpus_df in lda_corpora.items():

    relevant_mask = (
        corpus_df["Title"]
        .fillna("")
        .str.contains(
            power_pattern,
            regex=True,
        )
        |
        corpus_df["Abstract"]
        .fillna("")
        .str.contains(
            power_pattern,
            regex=True,
        )
    )

    print(corpus_name.upper())
    print("-" * len(corpus_name))

    print(
        f"Total documents             : "
        f"{len(corpus_df):,}"
    )

    print(
        f"Power-domain terminology    : "
        f"{relevant_mask.sum():,}"
    )

    print(
        f"No power-domain terminology : "
        f"{(~relevant_mask).sum():,}"
    )

    print(
        f"Share with domain terminology: "
        f"{relevant_mask.mean() * 100:.2f}%"
    )

    print()

OVERTON
-------
Total documents             : 14,264
Power-domain terminology    : 3,515
No power-domain terminology : 10,749
Share with domain terminology: 24.64%

SCOPUS
------
Total documents             : 16,403
Power-domain terminology    : 10,234
No power-domain terminology : 6,169
Share with domain terminology: 62.39%

In [22]:
relevance_diagnostics = {}

for corpus_name, corpus_df in lda_corpora.items():

    text = (
        corpus_df["Title"].fillna("")
        + " "
        + corpus_df["Abstract"].fillna("")
    )

    relevant_mask = text.str.contains(
        power_pattern,
        regex=True,
    )

    diagnostic_df = (
        corpus_df.loc[
            ~relevant_mask,
            [
                "Title",
                "Year",
                "DOI",
                "Abstract",
            ],
        ]
        .copy()
    )

    relevance_diagnostics[
        corpus_name
    ] = diagnostic_df

    print(f"\n{corpus_name.upper()}")
    print("-" * len(corpus_name))

    display(
        diagnostic_df[
            [
                "Title",
                "Year",
                "DOI",
            ]
        ]
        .sample(
            n=min(
                30,
                len(diagnostic_df),
            ),
            random_state=123,
        )
        .reset_index(drop=True)
    )

OVERTON
-------

,Title,Year,DOI
0,Development and mean life of aluminum first-su...,2009,10.1016/j.solmat.2009.05.004
1,High Reliability Safeguards approach to remote...,2017,10.1016/j.nucengdes.2017.08.012
2,Economic valuation of coccidioidomycosis (vall...,2021,10.1175/WCAS-D-20-0036.1
3,Taxi time prediction at Charlotte airport usin...,2015,10.2514/6.2015-2272
4,Urban Development and Energy Access in Informa...,2016,10.1016/j.proeng.2016.08.680
5,Model order reduction a key technology for dig...,2018,10.1007/978-3-319-75319-5_8
6,Superior room-temperature ductility of typical...,2016,10.1038/ncomms12261
7,Fourier-bessel series model for the Stefan pro...,2018,10.1115/ICONE26-81009
8,A simple apparatus for the injection of lithiu...,2010,10.1016/j.fusengdes.2010.08.033
9,The 'southern model' of welfare in social Europe,1996,10.1177/095892879600600102
10,Appraising the impact and role of platform mod...,2017,10.1016/j.giq.2017.03.003
11,Investigation of frequency domain traveling wa...,2010,10.1109/TDC.2010.5484571
12,Artificial Intelligence for infectious disease...,2019,10.1016/j.idh.2018.10.002
13,Simulation study of VoIP performance in IEEE 8...,2010,10.1007/978-3-642-15428-7_15
14,Digital public goods platforms for development...,2022,10.1080/01972243.2022.2105999
15,Integrated protection of industrial control sy...,2018,10.1016/j.ijcip.2018.04.004
16,A Wide Range of Testing Results on an Excellen...,2019,10.1149/2.0981913jes
17,South Pole Ozone Profile and Lower Tolerance L...,2013,10.1007/978-1-4614-6862-2_8
18,Artificial Intelligence and emerging digital t...,2021,10.1016/j.apenergy.2021.117615
19,Improved long-period generators based on linea...,2006,10.1145/1132973.1132974
20,Improving science-policy interface: Lessons fr...,2020,10.1016/j.forpol.2019.101997
21,Governing for Transformative Change across the...,2022,10.1093/biosci/biac031
22,Trends in black carbon and size-resolved parti...,2017,10.1016/j.atmosenv.2017.06.036
23,Demand charge savings from solar PV and energy...,2020,10.1016/j.enpol.2020.111766
24,Automated defect identification in electrolumi...,2022,10.1016/j.solener.2022.06.031
25,Financial inclusion in India: An axiomatic app...,2013,10.1016/j.jpolmod.2012.12.007
26,Impact in Software Engineering Activities Afte...,2023,10.1109/ACCESS.2023.3279917
27,Lateral Movement Detection Using Distributed D...,2016,10.1109/SRDS.2016.014
28,Order-Disorder Transitions and Superionic Cond...,2017,10.1021/acs.chemmater.7b04332
29,A Hybrid Distribution Feeder Long-Term Load Fo...,2020,10.1109/TSG.2019.2924183

SCOPUS
------

,Title,Year,DOI
0,Power optimisation scheme of induction motor u...,2020,10.1049/iet-est.2019.0151
1,An Adaptive Sparse Anisotropic Polynomial-Chao...,2021,10.1109/MEMC.2021.9477248
2,Artificial intelligence in renewable energy te...,2026,10.1016/j.nxener.2026.100575
3,High-performance computing for electric vehicl...,2024,10.4018/978-1-6684-3795-7.ch016
4,Smart energy efficient transportation systems,2026,10.1016/B978-0-323-95045-9.00023-8
5,NEAR-OPTIMAL SOLUTIONS OF CONSTRAINED LEARNING...,2024,0
6,Asynchronous observer-based control for input-...,2026,10.1016/j.cnsns.2025.109458
7,Multi-Objective Optimal Design of an On-Grid H...,2026,10.1109/ACCESS.2026.3667538
8,A review of distributed energy system optimiza...,2023,10.1016/j.jobe.2023.106735
9,Advances in Mountain Gazelle Optimizer: A Comp...,2025,10.1007/s44196-025-00968-4
10,An enhanced binary particle swarmoptimization ...,2010,10.1243/09544062JMES2128
11,Optimizing deep CNN architecture via hybrid Ha...,2026,10.1016/j.neuroscience.2026.02.001
12,DRCC-LPVMPC: Robust Data-Driven Control for Au...,2026,10.1109/TCST.2026.3713995
13,Optimal sensor placement in power transformers...,2026,10.1186/s13662-026-04070-7
14,CNN-LSTM to Predict and Investigate the Perfor...,2023,10.3390/pr11092731
15,Physics-guided deep learning surrogate model w...,2026,10.1016/j.jhazmat.2025.140767
16,Using a machine learning method with novel opt...,2025,10.1177/13272314241295963
17,Ensemble classification technique for heart di...,2021,10.1515/bams-2020-0033
18,Carbon-Aware Scheduling of Thermostatically Co...,2025,10.1109/TSG.2024.3525134
19,Distributed Fixed-time Optimization for Multip...,2024,10.1007/s12555-023-0451-2
20,Improved black hole algorithm for intelligent ...,2021,10.53106/160792642021072204001
21,A hybrid RSA-IPA optimizer for designing an ar...,2023,10.1016/j.rineng.2023.101542
22,Prediction of EV arrivals at battery swapping ...,2021,10.1088/1742-6596/2062/1/012021
23,Deep operator networks for Bayesian parameter ...,2025,10.1016/j.cpc.2025.109853
24,Safe Flexibility in Active Distribution Grids:...,2021,10.1109/ISGTEurope52324.2021.9640135
25,Network Performance Oriented Study of Sensor N...,2024,10.1117/12.3026737
26,Improving maximum power point tracking efficie...,2024,10.1049/rpg2.13138
27,Asynchronous ADMM for nonlinear continuous-tim...,2024,10.1002/oca.3104
28,An efficient multi-core implementation of the ...,2019,10.1080/17445760.2017.1416387
29,Multi-objective optimization of economic emiss...,2023,10.1016/j.epsr.2023.109700

### 2.2 Domain-Relevance Screening

To support a meaningful comparison between policy-facing and academic
literature, both corpora are restricted to publications relevant to
the power and energy systems domain before topic modeling.

The relevance screen is applied identically to Overton and Scopus.
A broad domain vocabulary is used to capture power-system research
without requiring specific terminology such as "power system" or
"power flow". The screening rule is validated through manual
inspection of retained and excluded records before the filtered
corpora are used for LDA.

In [23]:
# Broad power-and-energy-system terminology used for relevance screening.
#
# This is intentionally broader than the earlier diagnostic.
# The same rule is applied to both Overton and Scopus.

DOMAIN_TERM_GROUPS = {

    "power_system": [
        r"\bpower systems?\b",
        r"\belectric(?:al)? power\b",
        r"\bpower networks?\b",
        r"\belectric(?:al)? networks?\b",
        r"\bpower grids?\b",
        r"\belectric(?:al)? grids?\b",
        r"\bsmart grids?\b",
        r"\bmicrogrids?\b",
        r"\bmicro-grids?\b",
    ],

    "power_flow_operation": [
    r"\bpower flows?\b",
    r"\bload flows?\b",
    r"\boptimal power flows?\b",
    r"\bopf\b",

    # Dispatch and system operation
    r"\beconomic power dispatch\b",
    r"\beconomic dispatch\b",
    r"\boptimal dispatch\b",
    r"\bpower dispatch\b",
    r"\bunit commitment\b",

    # Loss / operating quantities
    r"\bpower loss(?:es)?\b",
    r"\breal power\b",
    r"\bactive power\b",
    r"\breactive power\b",

    # State / voltage / frequency operation
    r"\bstate estimation\b",
    r"\bvoltage stability\b",
    r"\bvoltage control\b",
    r"\bfrequency control\b",
    r"\bfrequency regulation\b",
    ],

    "transmission_distribution": [
        r"\btransmission systems?\b",
        r"\btransmission networks?\b",
        r"\bdistribution systems?\b",
        r"\bdistribution networks?\b",
        r"\bdistribution grids?\b",
        r"\btransmission grids?\b",
        r"\bdistribution feeders?\b",
        r"\bfeeders?\b",
        r"\bsubstations?\b",
    ],

    "electricity": [
        r"\belectricity\b",
        r"\belectric energy\b",
        r"\belectrical energy\b",
        r"\belectricity markets?\b",
        r"\benergy markets?\b",
        r"\belectric utilities?\b",
        r"\bpower utilities?\b",
    ],

    "generation_resources": [
    r"\bpower generation\b",
    r"\belectricity generation\b",
    r"\bgenerating units?\b",
    r"\bgenerators?\b",
    r"\bdistributed generation\b",
    r"\bdistributed energy resources?\b",
    r"\bder\b",
    r"\bders\b",
    r"\benergy resources?\b",
    ],

    "renewables": [
        r"\brenewable energy\b",
        r"\brenewable generation\b",
        r"\bsolar energy\b",
        r"\bsolar power\b",
        r"\bphotovoltaic\b",
        r"\bphotovoltaics\b",
        r"\bpv systems?\b",
        r"\bwind energy\b",
        r"\bwind power\b",
        r"\bwind farms?\b",
        r"\bwind turbines?\b",
    ],

    "storage_ev": [
        r"\benergy storage\b",
        r"\bbattery storage\b",
        r"\bbattery energy storage\b",
        r"\bbess\b",
        r"\belectric vehicles?\b",
        r"\bev charging\b",
        r"\bvehicle-to-grid\b",
        r"\bv2g\b",
    ],

    "power_electronics": [
        r"\bpower electronics\b",
        r"\binverters?\b",
        r"\bconverters?\b",
        r"\bac[- ]dc\b",
        r"\bdc[- ]ac\b",
    ],

    "load_demand": [
        r"\belectric(?:al)? loads?\b",
        r"\bload demand\b",
        r"\belectricity demand\b",
        r"\benergy demand\b",
        r"\bload forecasting\b",
        r"\bdemand response\b",
        r"\bdemand-side management\b",
    ],

    "energy_system": [
    r"\benergy systems?\b",
    r"\bintegrated energy systems?\b",
    r"\bmulti-energy systems?\b",
    r"\bmultienergy systems?\b",
    r"\benergy management systems?\b",
    r"\benergy management\b",
    ],

    "market_reliability": [
    r"\blocational marginal pric(?:e|es|ing)\b",
    r"\blmp\b",
    r"\belectricity pric(?:e|es|ing)\b",
    r"\benergy pric(?:e|es|ing)\b",
    r"\bpower system reliability\b",
    r"\bgrid reliability\b",
    r"\bline failures?\b",
    r"\btransmission line failures?\b",
    r"\bpower system security\b",
    r"\bgrid security\b",
    ],
}

In [24]:
domain_patterns = {
    group: re.compile(
        "|".join(patterns),
        flags=re.IGNORECASE,
    )
    for group, patterns in DOMAIN_TERM_GROUPS.items()
}

domain_screening = {}

for corpus_name, corpus_df in lda_corpora.items():

    screening_df = corpus_df.copy()

    screening_text = (
        screening_df["Title"]
        .fillna("")
        .astype(str)
        + " "
        + screening_df["Abstract"]
        .fillna("")
        .astype(str)
    )

    matched_columns = []

    for group, pattern in domain_patterns.items():

        column = f"match_{group}"

        screening_df[column] = (
            screening_text.str.contains(
                pattern,
                regex=True,
            )
        )

        matched_columns.append(column)

    # Number of different domain concept groups matched.
    screening_df[
        "Domain_Group_Count"
    ] = (
        screening_df[
            matched_columns
        ]
        .sum(axis=1)
    )

    # Initial broad relevance rule:
    # at least one substantive power/energy-domain group.
    screening_df[
        "Domain_Relevant"
    ] = (
        screening_df[
            "Domain_Group_Count"
        ] >= 1
    )

    domain_screening[
        corpus_name
    ] = screening_df

    print(corpus_name.upper())
    print("-" * len(corpus_name))

    print(
        f"Total documents       : "
        f"{len(screening_df):,}"
    )

    print(
        f"Domain relevant       : "
        f"{screening_df['Domain_Relevant'].sum():,}"
    )

    print(
        f"Not domain relevant   : "
        f"{(~screening_df['Domain_Relevant']).sum():,}"
    )

    print(
        f"Retention rate        : "
        f"{screening_df['Domain_Relevant'].mean() * 100:.2f}%"
    )

    print()

OVERTON
-------
Total documents       : 14,264
Domain relevant       : 5,045
Not domain relevant   : 9,219
Retention rate        : 35.37%

SCOPUS
------
Total documents       : 16,403
Domain relevant       : 12,042
Not domain relevant   : 4,361
Retention rate        : 73.41%

In [28]:
domain_group_summary = []

for corpus_name, screening_df in domain_screening.items():

    for group in DOMAIN_TERM_GROUPS:

        count = int(
            screening_df[
                f"match_{group}"
            ].sum()
        )

        domain_group_summary.append({
            "Corpus": corpus_name.capitalize(),
            "Domain_Group": group,
            "Documents": count,
            "Percent": (
                count
                / len(screening_df)
                * 100
            ),
        })

domain_group_summary = pd.DataFrame(
    domain_group_summary
)

domain_group_summary.pivot(
    index="Domain_Group",
    columns="Corpus",
    values="Documents",
)

Corpus                     Overton  Scopus
Domain_Group
electricity                   1366    2035
energy_system                  564    2390
generation_resources          1282    3485
load_demand                    427    1362
market_reliability             177     546
power_electronics              475    1140
power_flow_operation           917    5747
power_system                  1989    7107
renewables                    2139    4603
storage_ev                     868    2544
transmission_distribution      996    3399

In [29]:
for corpus_name, screening_df in domain_screening.items():

    print(f"\n{'=' * 70}")
    print(corpus_name.upper())
    print(f"{'=' * 70}")

    retained = screening_df[
        screening_df["Domain_Relevant"]
    ]

    rejected = screening_df[
        ~screening_df["Domain_Relevant"]
    ]

    print("\nRANDOM RETAINED DOCUMENTS")
    print("-------------------------")

    display(
        retained[
            [
                "Title",
                "Year",
                "DOI",
                "Domain_Group_Count",
            ]
        ]
        .sample(
            n=min(20, len(retained)),
            random_state=123,
        )
        .reset_index(drop=True)
    )

    print("\nRANDOM REJECTED DOCUMENTS")
    print("-------------------------")

    display(
        rejected[
            [
                "Title",
                "Year",
                "DOI",
            ]
        ]
        .sample(
            n=min(20, len(rejected)),
            random_state=123,
        )
        .reset_index(drop=True)
    )

======================================================================
OVERTON
======================================================================

RANDOM RETAINED DOCUMENTS
-------------------------

,Title,Year,DOI,Domain_Group_Count
0,Forecasting day-ahead price of electricity - A...,2013,10.1504/IJBEX.2013.056110,2
1,Exploring electric vehicle charging patterns: ...,2020,10.1016/j.trd.2020.102249,1
2,Condition monitoring of wind turbines: Techniq...,2012,10.1016/j.renene.2012.03.003,1
3,Validation of combined analytical methods to p...,2020,10.1016/j.triboint.2020.106347,1
4,Distributed energy resources and the organized...,2019,10.1016/j.enpol.2018.11.009,3
5,Reduced-order structure-preserving model for p...,2017,10.1109/COMPEL.2017.8013389,2
6,AI-assistance for predictive maintenance of re...,2021,10.1016/j.energy.2021.119775,2
7,Agent-based control framework for distributed ...,2006,10.1109/IAT.2006.27,6
8,Optimization methods applied to renewable and ...,2011,10.1016/j.rser.2010.12.008,2
9,A Setting-Free Differential Protection for Pow...,2019,10.1109/TPWRD.2018.2889471,1
10,Multiphase Distribution Feeder Reduction,2018,10.1109/TPWRS.2017.2726502,4
11,Wind turbine nacelle cooling systems: A review,2022,10.1002/wene.456,1
12,A stochastic downscaling approach for generati...,2018,10.1016/j.solener.2018.10.019,2
13,A comprehensive wind power forecasting system ...,2020,10.3390/en13061372,2
14,The impact of wind power geographical smoothin...,2016,10.1109/ACC.2016.7526593,2
15,Data-driven upscaling methods for regional pho...,2017,10.1016/j.solener.2017.09.068,3
16,Strategic Location of EV Fast Charging Station...,2019,10.1109/ISGT-LA.2019.8895284,1
17,Reduced-Order Parameterized Short-Circuit Curr...,2021,10.1109/TPWRD.2020.3046966,2
18,Extreme load alleviation using industrial impl...,2016,10.1088/1742-6596/753/4/042001,1
19,Review of grid interconnection requirements an...,2021,10.1109/PowerAfrica52236.2021.9543220,1

RANDOM REJECTED DOCUMENTS
-------------------------

,Title,Year,DOI
0,The economic burden of physical inactivity: a ...,2016,10.1016/S0140-6736(16)30383-X
1,Challenges to Transforming Unconventional Soci...,2020,10.1017/dmp.2019.92
2,Water transport mechanisms for salt-rejecting ...,2018,10.1016/j.memsci.2018.05.041
3,Associations of mortality with long-term expos...,2015,10.1289/ehp.1408565
4,The impact of synchronisation on secure inform...,2001,10.1007/3-540-45575-2_22
5,Options for reforming agricultural subsidies f...,2022,10.1038/s41467-021-27645-2
6,Distributed snapshots for mobile computing sys...,2004,10.1109/PERCOM.2004.1276856
7,Handling SQL Databases in Automated System Tes...,2020,10.1145/3391533
8,CCured: Type-safe retrofitting of legacy software,2005,10.1145/1065887.1065892
9,Geometry of Kapitsa's potentials,1998,10.1088/0951-7715/11/5/011
10,Assessing crop N status of fertigated vegetabl...,2015,10.1111/aab.12235
11,Analysis of a mathematical model for tuberculo...,2011,10.1016/j.jtbi.2010.09.044
12,Geometric mechanics of curved crease origami,2012,10.1103/PhysRevLett.109.114301
13,Average stress in matrix and average elastic e...,1973,10.1016/0001-6160(73)90064-3
14,ERBB oncogene proteins as targets for monoclon...,2012,10.1134/S0006297912030029
15,Geometry of function spaces,2013,10.1155/2013/636025
16,Variation in height and BMI of adult Indians,2014,10.1017/S002193201300014X
17,An overview of lean exhaust denox aftertreatme...,2021,10.3390/catal11030404
18,Modeling and Visualization of Complex Systems ...,2016,10.1002/9781118982747
19,Roughness evaluation in shotcrete-lined water ...,2018,10.1016/j.jrmge.2017.07.006

======================================================================
SCOPUS
======================================================================

RANDOM RETAINED DOCUMENTS
-------------------------

,Title,Year,DOI,Domain_Group_Count
0,Power systems and microgrids resilience enhanc...,2025,10.1016/j.rser.2024.114953,1
1,Transfer Learning-Based Model Training for Sho...,2026,10.35833/MPCE.2024.000940,3
2,Machine-learned security assessment for changi...,2022,10.1016/j.ijepes.2021.107380,2
3,Robustness of Evolving Power Grids: Modeling a...,2026,10.1201/9781003622130,2
4,Thyristor controlled series compensator planni...,2010,10.1109/PECON.2010.5697550,3
5,Optimal design and operation of a power-to-gas...,2026,10.1016/j.egyr.2026.109680,4
6,Scalable Optimization Methods for Distribution...,2016,10.1109/TSG.2016.2543264,4
7,Probabilistic Power Flow Method for Hybrid AC/...,2023,10.3390/en16062547,4
8,Genetic search for an optimal power flow solut...,2008,0,1
9,Convex Optimization of Power Systems,2015,10.1017/9781139924672,2
10,Dynamic thermal rating of offshore cables: An ...,2026,10.1016/j.segan.2026.102263,3
11,Control performance of a natural gas-hybrid re...,2025,10.1016/j.fraope.2025.100326,4
12,Artificial intelligence in electricity market ...,2005,10.4018/978-1-59140-702-7.ch008,1
13,Design and performance evaluation of an island...,2025,10.1016/j.rineng.2025.107494,5
14,Coordinated Operation of Multienergy Systems W...,2024,10.1109/JIOT.2024.3355132,2
15,Reinforcement learning-based solution to power...,2020,10.1109/MLHPCAI4S51975.2020.00015,3
16,Practical controller design of three-phase dua...,2020,10.3390/electronics9122101,3
17,Adaptable scheduling of smart building communi...,2022,10.1016/j.apenergy.2021.118445,6
18,A hierarchical deep learning approach to optim...,2025,10.1016/j.apenergy.2024.124313,3
19,Privacy-Preserving Distributed Optimization an...,2025,10.1016/B978-0-443-14081-5.00125-2,1

RANDOM REJECTED DOCUMENTS
-------------------------

,Title,Year,DOI
0,A Review of Optimal Design for Large-Scale Mic...,2023,10.3390/agronomy13122966
1,Integration of Robust Control and Multi-Object...,2025,10.1002/oca.3249
2,Accuracy analysis of rebar quantity estimation...,2026,10.1080/15623599.2026.2707233
3,Convergence Track Based Adaptive Differential ...,2022,10.32604/cmc.2022.024211
4,Nondestructive detection of trace cadmium in l...,2025,10.1016/j.jfca.2025.108038
5,Survey on Lagrangian relaxation for MILP: impo...,2024,10.1007/s10479-023-05499-9
6,The Comprehensive Review for Biobased FPA Algo...,2021,10.1002/9781119681984.ch7
7,Data-Driven Optimal Scheduling Algorithm of Hu...,2022,10.1155/2022/8602015
8,A modified teaching–learning-based optimizatio...,2019,10.1007/s13042-018-0815-8
9,Dual mutations collaboration mechanism with el...,2022,10.1007/s00500-021-06454-1
10,A Real-Time Edge-Aware Neural Enhancement Algo...,2026,10.59543/jidmis.v3.1537
11,Fitting procedure based on Differential Evolut...,2019,10.1108/EC-11-2018-0513
12,Adaptive robust online portfolio selection,2025,10.1016/j.ejor.2024.09.002
13,Low frequency residential non-intrusive load m...,2022,10.1080/15567036.2022.2046663
14,Automated brain tumor detection and classifica...,2021,10.1002/ima.22582
15,Machine learning-assisted design of flow field...,2022,10.1039/d1ee03224k
16,Efficient reinforcement learning-based method ...,2024,10.1016/j.eswa.2023.122088
17,Privacy-Preserving Technologies for 6G-Enabled...,2025,10.1201/9781003564645-8
18,A New Distributed Optimization Algorithm for M...,2020,10.1145/3423390.3423397
19,Transfer machine learning framework for effici...,2025,10.1016/j.ijheatmasstransfer.2025.126785

### 2.3 Final Domain-Filtered Corpora

In [30]:
lda_corpora_filtered = {}

for corpus_name, screening_df in domain_screening.items():

    filtered_df = (
        screening_df[
            screening_df["Domain_Relevant"]
        ]
        .copy()
        .reset_index(drop=True)
    )

    lda_corpora_filtered[
        corpus_name
    ] = filtered_df

    original_n = len(
        lda_corpora[corpus_name]
    )

    filtered_n = len(
        filtered_df
    )

    print(corpus_name.upper())
    print("-" * len(corpus_name))

    print(
        f"Original documents : "
        f"{original_n:,}"
    )

    print(
        f"Retained documents : "
        f"{filtered_n:,}"
    )

    print(
        f"Excluded documents : "
        f"{original_n - filtered_n:,}"
    )

    print(
        f"Retention rate     : "
        f"{filtered_n / original_n * 100:.2f}%"
    )

    print()

OVERTON
-------
Original documents : 14,264
Retained documents : 5,045
Excluded documents : 9,219
Retention rate     : 35.37%

SCOPUS
------
Original documents : 16,403
Retained documents : 12,042
Excluded documents : 4,361
Retention rate     : 73.41%

## 3. R Text-Processing Backend

The abstract corpora are preprocessed using R `tm` and `SnowballC`
through `Rscript`. This preserves the text-processing methodology used
for the LDA analysis while allowing the complete workflow to be
controlled from Python.

In [ ]:
from pathlib import Path
import subprocess

RSCRIPT = Path(
    r"/nfs/mfirdausi/miniconda3/envs/pytorch/bin/Rscript"
)

if not RSCRIPT.exists():
    raise FileNotFoundError(
        f"Rscript not found: {RSCRIPT}"
    )

# Check required R packages.
r_package_check = subprocess.run(
    [
        str(RSCRIPT),
        "-e",
        (
            'pkgs <- c("tm", "SnowballC", "slam", "topicmodels"); '
            'ok <- sapply(pkgs, requireNamespace, quietly=TRUE); '
            'cat(paste(pkgs, ok, sep="="), sep="\\n")'
        ),
    ],
    capture_output=True,
    text=True,
    check=True,
)

print("Rscript:")
print(RSCRIPT)

print("\nRequired R packages:")
print(r_package_check.stdout)

### 3.1 Text-Preprocessing Configuration

The Overton and Scopus corpora are processed using an identical text
preprocessing configuration to support direct comparison between the
two independently estimated topic models.

Standard English stopwords are supplemented with terms appearing
explicitly in the literature-search query because these terms define
the corpus but provide limited information for distinguishing latent
topics.

In [ ]:
# Search-query terms removed from both corpora.
# change this based on your topic

QUERY_STOPWORDS = [
    # Search-query terms
    "power",
    "flow",
    "machine",
    "learning",
    "optimization",
    "optimisation",

    # Publisher/copyright boilerplate
    "©",
]

# Initial DTM configuration.
MIN_TERM_LENGTH = 3
MIN_DOC_FREQ = 3

print("Query-specific stopwords:")
for word in QUERY_STOPWORDS:
    print(f"  - {word}")

print("\nDTM configuration")
print("-----------------")
print("Minimum term length     :", MIN_TERM_LENGTH)
print("Minimum document freq.  :", MIN_DOC_FREQ)

### 3.2 Preprocess Abstracts with R `tm`

The same R `tm` and `SnowballC` preprocessing pipeline is applied
independently to the Overton and Scopus abstracts. Processing includes
lowercasing, punctuation and number removal, whitespace normalization,
English and query-specific stopword removal, and English Snowball
stemming.

The resulting corpora are used to inspect vocabulary characteristics
before the final document-term matrices are constructed.

In [ ]:
R_PREPROCESS_DIR = OUTPUT_DIR / "r_preprocessing"

R_PREPROCESS_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

R_PREPROCESS_SCRIPT = (
    R_PREPROCESS_DIR / "preprocess_corpus.R"
)

r_preprocess_code = r'''
args <- commandArgs(trailingOnly = TRUE)

input_file  <- args[1]
output_file <- args[2]

suppressPackageStartupMessages({
    library(tm)
    library(SnowballC)
})

# ------------------------------------------------------------
# Load abstracts
# ------------------------------------------------------------

data <- read.csv(
    input_file,
    stringsAsFactors = FALSE,
    check.names = FALSE,
    fileEncoding = "UTF-8"
)

abstracts <- data$Abstract

# ------------------------------------------------------------
# Shared stopwords
# ------------------------------------------------------------

custom_stops <- c(
    "power",
    "flow",
    "machine",
    "learning",
    "optimization",
    "optimisation",
    "©"
)

all_stops <- unique(
    c(
        tm::stopwords("english"),
        custom_stops
    )
)

# ------------------------------------------------------------
# tm preprocessing
# ------------------------------------------------------------

corpus <- VCorpus(
    VectorSource(abstracts)
)

corpus <- tm_map(
    corpus,
    content_transformer(tolower)
)

corpus <- tm_map(
    corpus,
    removePunctuation
)

corpus <- tm_map(
    corpus,
    removeNumbers
)

corpus <- tm_map(
    corpus,
    stripWhitespace
)

corpus <- tm_map(
    corpus,
    removeWords,
    all_stops
)

# Remove copyright symbol explicitly.
corpus <- tm_map(
    corpus,
    content_transformer(
        function(x) gsub(
            "©",
            " ",
            x,
            fixed = TRUE
        )
    )
)

corpus <- tm_map(
    corpus,
    stripWhitespace
)

corpus <- tm_map(
    corpus,
    stemDocument,
    language = "english"
)

corpus <- tm_map(
    corpus,
    stripWhitespace
)

processed <- vapply(
    corpus,
    as.character,
    character(1)
)

result <- data.frame(
    document_id = seq_along(processed),
    processed_text = processed,
    stringsAsFactors = FALSE
)

write.csv(
    result,
    output_file,
    row.names = FALSE,
    fileEncoding = "UTF-8"
)
'''

R_PREPROCESS_SCRIPT.write_text(
    r_preprocess_code,
    encoding="utf-8",
)

print(
    "Created R preprocessing script:",
    R_PREPROCESS_SCRIPT
)

In [ ]:
processed_corpora = {}

for corpus_name, corpus_df in lda_corpora_filtered.items():

    input_file = (
    R_PREPROCESS_DIR
    / f"{corpus_name}_domain_filtered_abstracts.csv"
    )

    output_file = (
        R_PREPROCESS_DIR
        / f"{corpus_name}_domain_filtered_processed.csv"
    )
    # ---------------------------------------------------------
    # Use cached processed corpus if it already exists
    # ---------------------------------------------------------

    if output_file.exists():

        print(
            f"Loading cached {corpus_name.upper()} "
            f"processed corpus ..."
        )

    else:

        print(
            f"Processing {corpus_name.upper()} with R ..."
        )

        # Export abstracts only when preprocessing is required.
        corpus_df[
            ["Abstract"]
        ].to_csv(
            input_file,
            index=False,
            encoding="utf-8",
        )

        run = subprocess.run(
            [
                str(RSCRIPT),
                str(R_PREPROCESS_SCRIPT),
                str(input_file),
                str(output_file),
            ],
            capture_output=True,
            text=True,
            check=True,
        )

    # ---------------------------------------------------------
    # Load processed corpus
    # ---------------------------------------------------------

    processed_df = pd.read_csv(
        output_file,
        keep_default_na=False,
    )

    processed_corpora[
        corpus_name
    ] = processed_df

    print(
        f"Documents processed : "
        f"{len(processed_df):,}"
    )

    print(
        f"Empty documents     : "
        f"{(processed_df['processed_text'].str.strip() == '').sum():,}"
    )

    print()

In [ ]:
for corpus_name, processed_df in processed_corpora.items():

    token_counts = (
        processed_df[
            "processed_text"
        ]
        .str.split()
        .str.len()
    )

    print(corpus_name.upper())
    print("-" * len(corpus_name))

    print(
        f"Documents       : "
        f"{len(processed_df):,}"
    )

    print(
        f"Total tokens    : "
        f"{int(token_counts.sum()):,}"
    )

    print(
        f"Minimum tokens  : "
        f"{int(token_counts.min()):,}"
    )

    print(
        f"Median tokens   : "
        f"{token_counts.median():.0f}"
    )

    print(
        f"Mean tokens     : "
        f"{token_counts.mean():.1f}"
    )

    print(
        f"Maximum tokens  : "
        f"{int(token_counts.max()):,}"
    )

    print()

### 3.3 Inspect Frequent Terms

The most frequent terms remaining after preprocessing are inspected
before constructing the final document-term matrices. This diagnostic
is used to identify high-frequency generic terms that provide little
thematic discrimination and may therefore warrant inclusion in the
shared custom stopword list.

In [ ]:
from collections import Counter

term_frequency_tables = {}

for corpus_name, processed_df in processed_corpora.items():

    term_frequency = Counter(
        token
        for text in processed_df["processed_text"]
        for token in text.split()
    )

    top_terms = pd.DataFrame(
        term_frequency.most_common(50),
        columns=[
            "term",
            "frequency",
        ],
    )

    term_frequency_tables[
        corpus_name
    ] = top_terms

    print(f"\n{corpus_name.upper()}")
    print("-" * len(corpus_name))

    display(
        top_terms.head(30)
    )

## 4. Document-Term Matrix Construction

Separate document-term matrices are constructed for the Overton and
Scopus corpora using R `tm`. The same preprocessing and vocabulary
filtering rules are applied to both corpora.

Terms shorter than three characters and terms occurring in fewer than
three documents are excluded. The resulting matrix dimensions and
sparsity are inspected before LDA model selection.

In [ ]:
R_DTM_SCRIPT = (
    R_PREPROCESS_DIR / "construct_dtm.R"
)

r_dtm_code = r'''
args <- commandArgs(trailingOnly = TRUE)

input_file   <- args[1]
summary_file <- args[2]
terms_file   <- args[3]

suppressPackageStartupMessages({
    library(tm)
    library(slam)
})

MIN_TERM_LENGTH <- 3
MIN_DOC_FREQ <- 3

# ------------------------------------------------------------
# Load processed documents
# ------------------------------------------------------------

data <- read.csv(
    input_file,
    stringsAsFactors = FALSE,
    check.names = FALSE,
    fileEncoding = "UTF-8"
)

processed <- data$processed_text

# Remove empty documents before DTM construction.
valid <- !is.na(processed) & nzchar(trimws(processed))

processed <- processed[valid]

# ------------------------------------------------------------
# Construct tm corpus
# ------------------------------------------------------------

corpus <- VCorpus(
    VectorSource(processed)
)

# ------------------------------------------------------------
# Initial DTM
# ------------------------------------------------------------

dtm <- DocumentTermMatrix(
    corpus,
    control = list(
        wordLengths = c(
            MIN_TERM_LENGTH,
            Inf
        )
    )
)

# ------------------------------------------------------------
# Minimum document frequency
# ------------------------------------------------------------

doc_freq <- slam::col_sums(
    dtm > 0
)

keep <- doc_freq >= MIN_DOC_FREQ

dtm <- dtm[
    ,
    keep
]

doc_freq <- doc_freq[
    keep
]

# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------

n_docs <- dtm$nrow
n_terms <- dtm$ncol
n_nonzero <- length(dtm$v)
n_tokens <- sum(dtm$v)

density <- (
    n_nonzero
    / (n_docs * n_terms)
    * 100
)

summary_result <- data.frame(
    Documents = n_docs,
    Vocabulary = n_terms,
    Nonzero_entries = n_nonzero,
    Total_tokens = n_tokens,
    Density_percent = density
)

write.csv(
    summary_result,
    summary_file,
    row.names = FALSE
)

term_result <- data.frame(
    Term = Terms(dtm),
    Document_frequency = as.numeric(doc_freq),
    stringsAsFactors = FALSE
)

write.csv(
    term_result,
    terms_file,
    row.names = FALSE
)
'''

R_DTM_SCRIPT.write_text(
    r_dtm_code,
    encoding="utf-8",
)

print(
    "Created R DTM script:",
    R_DTM_SCRIPT
)

In [ ]:
dtm_summaries = {}
dtm_term_tables = {}

for corpus_name in [
    "overton",
    "scopus",
]:

    # Domain-filtered processed corpus
    processed_file = (
        R_PREPROCESS_DIR
        / f"{corpus_name}_domain_filtered_processed.csv"
    )

    # Keep domain-filtered DTM diagnostics separate
    # from the previous unfiltered analysis.
    summary_file = (
        R_PREPROCESS_DIR
        / f"{corpus_name}_domain_filtered_dtm_summary.csv"
    )

    terms_file = (
        R_PREPROCESS_DIR
        / f"{corpus_name}_domain_filtered_dtm_terms.csv"
    )

    subprocess.run(
        [
            str(RSCRIPT),
            str(R_DTM_SCRIPT),
            str(processed_file),
            str(summary_file),
            str(terms_file),
        ],
        capture_output=True,
        text=True,
        check=True,
    )

    summary_df = pd.read_csv(
        summary_file
    )

    terms_df = pd.read_csv(
        terms_file
    )

    dtm_summaries[
        corpus_name
    ] = summary_df

    dtm_term_tables[
        corpus_name
    ] = terms_df

    row = summary_df.iloc[0]

    print(corpus_name.upper())
    print("-" * len(corpus_name))

    print(
        f"Documents       : "
        f"{int(row['Documents']):,}"
    )

    print(
        f"Vocabulary      : "
        f"{int(row['Vocabulary']):,}"
    )

    print(
        f"Nonzero entries : "
        f"{int(row['Nonzero_entries']):,}"
    )

    print(
        f"Total tokens    : "
        f"{int(row['Total_tokens']):,}"
    )

    print(
        f"Matrix density  : "
        f"{row['Density_percent']:.4f}%"
    )

    print()

### 4.1 Vocabulary Filtering

In [ ]:
# Compare vocabulary sizes under alternative document-frequency
# thresholds using the document frequencies already calculated in R.

DF_THRESHOLDS = [
    3,
    5,
    10,
    15,
    20,
    25,
    50,
    100,
]

df_threshold_results = []

for corpus_name, terms_df in dtm_term_tables.items():

    for threshold in DF_THRESHOLDS:

        retained = (
            terms_df["Document_frequency"]
            >= threshold
        ).sum()

        df_threshold_results.append({
            "Corpus": corpus_name.capitalize(),
            "Min_Document_Frequency": threshold,
            "Retained_Terms": int(retained),
        })

df_threshold_results = pd.DataFrame(
    df_threshold_results
)

df_threshold_pivot = (
    df_threshold_results
    .pivot(
        index="Min_Document_Frequency",
        columns="Corpus",
        values="Retained_Terms",
    )
)

df_threshold_pivot

In [ ]:
for corpus_name, terms_df in dtm_term_tables.items():

    print(corpus_name.upper())
    print("-" * len(corpus_name))

    n_docs = int(
        dtm_summaries[
            corpus_name
        ].iloc[0]["Documents"]
    )

    for threshold in DF_THRESHOLDS:

        retained = (
            terms_df["Document_frequency"]
            >= threshold
        ).sum()

        print(
            f"DF >= {threshold:3d} "
            f"({threshold / n_docs * 100:5.3f}% docs)"
            f" : {retained:6,d} terms"
        )

    print()

Based on the threshold analysis, the final vocabulary filter is defined
proportionally rather than using a common absolute document-frequency
count. Terms must occur in at least 0.2% of documents within each
corpus.

This corresponds to a minimum document frequency of 11 documents for
Overton and 25 documents for Scopus. The proportional rule provides
comparable vocabulary filtering despite the different corpus sizes.

### 4.2 Construct the Final Document-Term Matrices

The final document-term matrices are constructed using a minimum term
length of three characters and a minimum document frequency equal to
0.2% of the documents in each corpus.

In [ ]:
R_DTM_SCRIPT = (
    R_PREPROCESS_DIR / "construct_dtm.R"
)

r_dtm_code = r'''
args <- commandArgs(trailingOnly = TRUE)

input_file   <- args[1]
summary_file <- args[2]
terms_file   <- args[3]
min_doc_freq <- as.integer(args[4])

suppressPackageStartupMessages({
    library(tm)
    library(slam)
})

MIN_TERM_LENGTH <- 3
MIN_DOC_FREQ <- min_doc_freq

# ------------------------------------------------------------
# Load processed documents
# ------------------------------------------------------------

data <- read.csv(
    input_file,
    stringsAsFactors = FALSE,
    check.names = FALSE,
    fileEncoding = "UTF-8"
)

processed <- data$processed_text

# Remove empty documents before DTM construction.
valid <- !is.na(processed) & nzchar(trimws(processed))

processed <- processed[valid]

# ------------------------------------------------------------
# Construct tm corpus
# ------------------------------------------------------------

corpus <- VCorpus(
    VectorSource(processed)
)

# ------------------------------------------------------------
# Initial DTM
# ------------------------------------------------------------

dtm <- DocumentTermMatrix(
    corpus,
    control = list(
        wordLengths = c(
            MIN_TERM_LENGTH,
            Inf
        )
    )
)

# ------------------------------------------------------------
# Minimum document frequency
# ------------------------------------------------------------

doc_freq <- slam::col_sums(
    dtm > 0
)

keep <- doc_freq >= MIN_DOC_FREQ

dtm <- dtm[
    ,
    keep
]

doc_freq <- doc_freq[
    keep
]

# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------

n_docs <- dtm$nrow
n_terms <- dtm$ncol
n_nonzero <- length(dtm$v)
n_tokens <- sum(dtm$v)

density <- (
    n_nonzero
    / (n_docs * n_terms)
    * 100
)

summary_result <- data.frame(
    Documents = n_docs,
    Vocabulary = n_terms,
    Nonzero_entries = n_nonzero,
    Total_tokens = n_tokens,
    Density_percent = density
)

write.csv(
    summary_result,
    summary_file,
    row.names = FALSE
)

term_result <- data.frame(
    Term = Terms(dtm),
    Document_frequency = as.numeric(doc_freq),
    stringsAsFactors = FALSE
)

write.csv(
    term_result,
    terms_file,
    row.names = FALSE
)
'''

R_DTM_SCRIPT.write_text(
    r_dtm_code,
    encoding="utf-8",
)

print(
    "Created R DTM script:",
    R_DTM_SCRIPT
)

In [ ]:
import math

MIN_DOC_PERCENT = 0.002

final_dtm_summaries = {}
final_dtm_term_tables = {}

for corpus_name in [
    "overton",
    "scopus",
]:

    processed_file = (
        R_PREPROCESS_DIR
        / f"{corpus_name}_domain_filtered_processed.csv"
    )

    n_documents = len(
        processed_corpora[corpus_name]
    )

    min_doc_freq = math.ceil(
        n_documents * MIN_DOC_PERCENT
    )

    summary_file = (
        R_PREPROCESS_DIR
        / f"{corpus_name}_final_dtm_summary.csv"
    )

    terms_file = (
        R_PREPROCESS_DIR
        / f"{corpus_name}_final_dtm_terms.csv"
    )

    subprocess.run(
        [
            str(RSCRIPT),
            str(R_DTM_SCRIPT),
            str(processed_file),
            str(summary_file),
            str(terms_file),
            str(min_doc_freq),
        ],
        capture_output=True,
        text=True,
        check=True,
    )

    summary_df = pd.read_csv(
        summary_file
    )

    terms_df = pd.read_csv(
        terms_file
    )

    final_dtm_summaries[
        corpus_name
    ] = summary_df

    final_dtm_term_tables[
        corpus_name
    ] = terms_df

    row = summary_df.iloc[0]

    print(corpus_name.upper())
    print("-" * len(corpus_name))

    print(
        f"Documents            : "
        f"{int(row['Documents']):,}"
    )

    print(
        f"Minimum document freq: "
        f"{min_doc_freq:,}"
    )

    print(
        f"DF threshold         : "
        f"{min_doc_freq / n_documents * 100:.3f}%"
    )

    print(
        f"Vocabulary           : "
        f"{int(row['Vocabulary']):,}"
    )

    print(
        f"Nonzero entries      : "
        f"{int(row['Nonzero_entries']):,}"
    )

    print(
        f"Total tokens         : "
        f"{int(row['Total_tokens']):,}"
    )

    print(
        f"Matrix density       : "
        f"{row['Density_percent']:.4f}%"
    )

    print()

## 5. LDA Topic Modeling and Model Selection

LDA models are estimated independently for the domain-filtered Overton
and Scopus corpora using R `topicmodels` with Gibbs sampling.

For model selection, each corpus is divided reproducibly into 80%
training and 20% held-out documents using a fixed random seed.
Candidate topic numbers are evaluated using held-out predictive
performance together with topic coherence and distinctiveness.

In [ ]:
LDA_DIR = OUTPUT_DIR / "lda"

LDA_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

print("LDA output directory:")
print(LDA_DIR)

### 5.1 Training and Held-Out Splits

An independent 80/20 split is generated for each corpus using R's
random-number generator with seed 123. The same sampling procedure is
therefore applied to both datasets.

In [ ]:
RANDOM_SEED = 123

lda_splits = {}

for corpus_name, summary_df in final_dtm_summaries.items():

    n_documents = int(
        summary_df.iloc[0]["Documents"]
    )

    split_result = subprocess.run(
        [
            str(RSCRIPT),
            "-e",
            (
                f"set.seed({RANDOM_SEED}); "
                f"n <- {n_documents}; "
                "train_id <- sample("
                "seq_len(n), "
                "size=floor(0.8*n), "
                "replace=FALSE"
                "); "
                'cat(train_id, sep=",")'
            ),
        ],
        capture_output=True,
        text=True,
        check=True,
    )

    # Keep R's 1-based indices because these will
    # subsequently be passed back to R topicmodels.
    train_id = np.fromstring(
        split_result.stdout.strip(),
        sep=",",
        dtype=int,
    )

    all_id = np.arange(
        1,
        n_documents + 1
    )

    test_id = np.setdiff1d(
        all_id,
        train_id
    )

    lda_splits[corpus_name] = {
        "train_id": train_id,
        "test_id": test_id,
    }

    print(corpus_name.upper())
    print("-" * len(corpus_name))

    print(
        f"Total documents    : "
        f"{n_documents:,}"
    )

    print(
        f"Training documents : "
        f"{len(train_id):,}"
    )

    print(
        f"Held-out documents : "
        f"{len(test_id):,}"
    )

    print(
        f"Overlap             : "
        f"{len(np.intersect1d(train_id, test_id))}"
    )

    print()

### 5.2 Coarse Topic-Number Search

A coarse search is performed to identify a plausible range for the
number of latent topics in each domain-filtered corpus. Short Gibbs
chains are used at this screening stage to limit computational cost.

The final corpus-specific vocabulary thresholds established in Section
4 are retained throughout model selection.

In [ ]:
K_COARSE = [
    5,
    10,
    15,
    20,
    25,
    30,
    40,
    50,
]

COARSE_BURN_IN = 50
COARSE_ITERATIONS = 100
COARSE_THIN = 10

MIN_DOC_PERCENT = 0.002

print("Coarse K values :", K_COARSE)
print("Burn-in         :", COARSE_BURN_IN)
print("Iterations      :", COARSE_ITERATIONS)
print("Thin            :", COARSE_THIN)

In [ ]:
R_COARSE_SEARCH_SCRIPT = (
    LDA_DIR / "domain_filtered_coarse_k_search.R"
)

r_coarse_search_code = r'''
args <- commandArgs(trailingOnly = TRUE)

processed_file <- args[1]
train_file     <- args[2]
output_file    <- args[3]
min_doc_freq   <- as.integer(args[4])

suppressPackageStartupMessages({
    library(tm)
    library(slam)
    library(topicmodels)
})

MIN_TERM_LENGTH <- 3
MIN_DOC_FREQ <- min_doc_freq

K_VALUES <- c(
    5, 10, 15, 20,
    25, 30, 40, 50
)

BURN_IN <- 50
ITERATIONS <- 100
THIN <- 10

# ------------------------------------------------------------
# Load domain-filtered processed corpus
# ------------------------------------------------------------

data <- read.csv(
    processed_file,
    stringsAsFactors = FALSE,
    check.names = FALSE,
    fileEncoding = "UTF-8"
)

processed <- data$processed_text

valid <- (
    !is.na(processed)
    & nzchar(trimws(processed))
)

processed <- processed[valid]

corpus <- VCorpus(
    VectorSource(processed)
)

# ------------------------------------------------------------
# Reconstruct FINAL DTM
# ------------------------------------------------------------

dtm <- DocumentTermMatrix(
    corpus,
    control = list(
        wordLengths = c(
            MIN_TERM_LENGTH,
            Inf
        )
    )
)

doc_freq <- slam::col_sums(
    dtm > 0
)

dtm <- dtm[
    ,
    doc_freq >= MIN_DOC_FREQ
]

# ------------------------------------------------------------
# Train / held-out split
# ------------------------------------------------------------

train_id <- read.csv(
    train_file
)$train_id

test_id <- setdiff(
    seq_len(dtm$nrow),
    train_id
)

dtm_train <- dtm[
    train_id,
]

dtm_test <- dtm[
    test_id,
]

# Retain terms represented in training.
train_terms <- (
    slam::col_sums(
        dtm_train > 0
    ) > 0
)

dtm_train <- dtm_train[
    ,
    train_terms
]

dtm_test <- dtm_test[
    ,
    train_terms
]

# Remove zero-token documents after training-vocabulary filtering.
train_nonempty <- (
    slam::row_sums(dtm_train) > 0
)

test_nonempty <- (
    slam::row_sums(dtm_test) > 0
)

n_empty_train <- sum(!train_nonempty)
n_empty_test <- sum(!test_nonempty)

dtm_train <- dtm_train[
    train_nonempty,
]

dtm_test <- dtm_test[
    test_nonempty,
]

cat(
    "Training documents:",
    dtm_train$nrow,
    "\n"
)

cat(
    "Held-out documents:",
    dtm_test$nrow,
    "\n"
)

cat(
    "Vocabulary:",
    dtm_train$ncol,
    "\n"
)

cat(
    "Minimum document frequency:",
    MIN_DOC_FREQ,
    "\n"
)

cat(
    "Empty training removed:",
    n_empty_train,
    "\n"
)

cat(
    "Empty held-out removed:",
    n_empty_test,
    "\n\n"
)

# ------------------------------------------------------------
# Coarse K search
# ------------------------------------------------------------

results <- data.frame(
    K = integer(),
    Perplexity = numeric(),
    Elapsed_seconds = numeric()
)

for (k in K_VALUES) {

    cat(
        "Fitting K =",
        k,
        "... "
    )

    flush.console()

    start_time <- Sys.time()

    lda_model <- topicmodels::LDA(
        dtm_train,
        k = k,
        method = "Gibbs",
        control = list(
            seed = 123,
            burnin = BURN_IN,
            iter = ITERATIONS,
            thin = THIN
        )
    )

    heldout_perplexity <- (
        topicmodels::perplexity(
            lda_model,
            newdata = dtm_test
        )
    )

    elapsed <- as.numeric(
        difftime(
            Sys.time(),
            start_time,
            units = "secs"
        )
    )

    results <- rbind(
        results,
        data.frame(
            K = k,
            Perplexity = heldout_perplexity,
            Elapsed_seconds = elapsed
        )
    )

    # Preserve completed K values.
    write.csv(
        results,
        output_file,
        row.names = FALSE
    )

    cat(
        sprintf(
            "perplexity = %.4f | %.2f s\n",
            heldout_perplexity,
            elapsed
        )
    )

    flush.console()
}
'''

R_COARSE_SEARCH_SCRIPT.write_text(
    r_coarse_search_code,
    encoding="utf-8",
)

print(
    "Created:",
    R_COARSE_SEARCH_SCRIPT
)

In [ ]:
import math

corpus_name = "overton"

processed_file = (
    R_PREPROCESS_DIR
    / f"{corpus_name}_domain_filtered_processed.csv"
)

train_file = (
    LDA_DIR
    / f"{corpus_name}_domain_filtered_train_indices.csv"
)

coarse_output = (
    LDA_DIR
    / f"{corpus_name}_domain_filtered_coarse_k_search.csv"
)

# Same proportional vocabulary rule used in Section 4.
n_documents = int(
    final_dtm_summaries[
        corpus_name
    ].iloc[0]["Documents"]
)

min_doc_freq = math.ceil(
    n_documents * MIN_DOC_PERCENT
)

print("Running domain-filtered Overton coarse K search...")
print("Documents       :", f"{n_documents:,}")
print("Minimum DF      :", min_doc_freq)
print("K values        :", K_COARSE)

coarse_run = subprocess.run(
    [
        str(RSCRIPT),
        str(R_COARSE_SEARCH_SCRIPT),
        str(processed_file),
        str(train_file),
        str(coarse_output),
        str(min_doc_freq),
    ],
    capture_output=True,
    text=True,
    check=False,
)

print(
    "Return code:",
    coarse_run.returncode
)

if coarse_run.stdout.strip():
    print("\nR output:")
    print(
        coarse_run.stdout
    )

if coarse_run.stderr.strip():
    print("\nR messages:")
    print(
        coarse_run.stderr
    )

# Load completed results.
if coarse_output.exists():

    overton_coarse_results = pd.read_csv(
        coarse_output
    )

    print(
        "\nCompleted K values:",
        overton_coarse_results["K"].tolist()
    )

    display(
        overton_coarse_results
    )

else:

    print(
        "\nNo completed K values were saved."
    )

#### 5.2.1 Extended Overton Search

Because held-out perplexity continued to decrease through \(K=50\),
the screening range is extended to \(K=60,70,80,100\). These models
retain the same short Gibbs-chain settings and are used only to
characterize the model-complexity trend.

In [ ]:
R_COARSE_SEARCH_SCRIPT = (
    LDA_DIR / "overton_domain_filtered_extended_k_search.R"
)

r_coarse_search_code = r'''
args <- commandArgs(trailingOnly = TRUE)

processed_file <- args[1]
train_file     <- args[2]
output_file    <- args[3]
min_doc_freq   <- as.integer(args[4])

suppressPackageStartupMessages({
    library(tm)
    library(slam)
    library(topicmodels)
})

MIN_TERM_LENGTH <- 3
MIN_DOC_FREQ <- min_doc_freq

K_VALUES <- c(
    60, 70, 80, 100
)

BURN_IN <- 50
ITERATIONS <- 100
THIN <- 10

# ------------------------------------------------------------
# Load domain-filtered processed corpus
# ------------------------------------------------------------

data <- read.csv(
    processed_file,
    stringsAsFactors = FALSE,
    check.names = FALSE,
    fileEncoding = "UTF-8"
)

processed <- data$processed_text

valid <- (
    !is.na(processed)
    & nzchar(trimws(processed))
)

processed <- processed[valid]

corpus <- VCorpus(
    VectorSource(processed)
)

# ------------------------------------------------------------
# Reconstruct FINAL DTM
# ------------------------------------------------------------

dtm <- DocumentTermMatrix(
    corpus,
    control = list(
        wordLengths = c(
            MIN_TERM_LENGTH,
            Inf
        )
    )
)

doc_freq <- slam::col_sums(
    dtm > 0
)

dtm <- dtm[
    ,
    doc_freq >= MIN_DOC_FREQ
]

# ------------------------------------------------------------
# Train / held-out split
# ------------------------------------------------------------

train_id <- read.csv(
    train_file
)$train_id

test_id <- setdiff(
    seq_len(dtm$nrow),
    train_id
)

dtm_train <- dtm[
    train_id,
]

dtm_test <- dtm[
    test_id,
]

# Retain terms represented in training.
train_terms <- (
    slam::col_sums(
        dtm_train > 0
    ) > 0
)

dtm_train <- dtm_train[
    ,
    train_terms
]

dtm_test <- dtm_test[
    ,
    train_terms
]

# Remove zero-token documents after training-vocabulary filtering.
train_nonempty <- (
    slam::row_sums(dtm_train) > 0
)

test_nonempty <- (
    slam::row_sums(dtm_test) > 0
)

n_empty_train <- sum(!train_nonempty)
n_empty_test <- sum(!test_nonempty)

dtm_train <- dtm_train[
    train_nonempty,
]

dtm_test <- dtm_test[
    test_nonempty,
]

cat(
    "Training documents:",
    dtm_train$nrow,
    "\n"
)

cat(
    "Held-out documents:",
    dtm_test$nrow,
    "\n"
)

cat(
    "Vocabulary:",
    dtm_train$ncol,
    "\n"
)

cat(
    "Minimum document frequency:",
    MIN_DOC_FREQ,
    "\n"
)

cat(
    "Empty training removed:",
    n_empty_train,
    "\n"
)

cat(
    "Empty held-out removed:",
    n_empty_test,
    "\n\n"
)

# ------------------------------------------------------------
# Coarse K search
# ------------------------------------------------------------

results <- data.frame(
    K = integer(),
    Perplexity = numeric(),
    Elapsed_seconds = numeric()
)

for (k in K_VALUES) {

    cat(
        "Fitting K =",
        k,
        "... "
    )

    flush.console()

    start_time <- Sys.time()

    lda_model <- topicmodels::LDA(
        dtm_train,
        k = k,
        method = "Gibbs",
        control = list(
            seed = 123,
            burnin = BURN_IN,
            iter = ITERATIONS,
            thin = THIN
        )
    )

    heldout_perplexity <- (
        topicmodels::perplexity(
            lda_model,
            newdata = dtm_test
        )
    )

    elapsed <- as.numeric(
        difftime(
            Sys.time(),
            start_time,
            units = "secs"
        )
    )

    results <- rbind(
        results,
        data.frame(
            K = k,
            Perplexity = heldout_perplexity,
            Elapsed_seconds = elapsed
        )
    )

    # Preserve completed K values.
    write.csv(
        results,
        output_file,
        row.names = FALSE
    )

    cat(
        sprintf(
            "perplexity = %.4f | %.2f s\n",
            heldout_perplexity,
            elapsed
        )
    )

    flush.console()
}
'''

R_COARSE_SEARCH_SCRIPT.write_text(
    r_coarse_search_code,
    encoding="utf-8",
)

print(
    "Created:",
    R_COARSE_SEARCH_SCRIPT
)

In [ ]:
import math

K_EXTENDED = [
    60,
    70,
    80,
    100,
]

corpus_name = "overton"

processed_file = (
    R_PREPROCESS_DIR
    / f"{corpus_name}_domain_filtered_processed.csv"
)

train_file = (
    LDA_DIR
    / f"{corpus_name}_domain_filtered_train_indices.csv"
)

# IMPORTANT:
# Save separately from the original K=5,...,50 coarse search.
extended_output = (
    LDA_DIR
    / f"{corpus_name}_domain_filtered_extended_k_search.csv"
)

# Same proportional vocabulary rule used in Section 4.
n_documents = int(
    final_dtm_summaries[
        corpus_name
    ].iloc[0]["Documents"]
)

min_doc_freq = math.ceil(
    n_documents * MIN_DOC_PERCENT
)

print(
    "Running domain-filtered Overton extended K search..."
)

print(
    "Documents       :",
    f"{n_documents:,}"
)

print(
    "Minimum DF      :",
    min_doc_freq
)

print(
    "K values        :",
    K_EXTENDED
)

extended_run = subprocess.run(
    [
        str(RSCRIPT),
        str(R_COARSE_SEARCH_SCRIPT),
        str(processed_file),
        str(train_file),
        str(extended_output),
        str(min_doc_freq),
    ],
    capture_output=True,
    text=True,
    check=False,
)

print(
    "Return code:",
    extended_run.returncode
)

if extended_run.stdout.strip():

    print("\nR output:")

    print(
        extended_run.stdout
    )

if extended_run.stderr.strip():

    print("\nR messages:")

    print(
        extended_run.stderr
    )

# Load completed extended-search results.
if extended_output.exists():

    overton_extended_results = pd.read_csv(
        extended_output
    )

    print(
        "\nCompleted K values:",
        overton_extended_results[
            "K"
        ].tolist()
    )

    display(
        overton_extended_results
    )

else:

    print(
        "\nNo completed extended K values were saved."
    )

In [ ]:
overton_k_screen = (
    pd.concat(
        [
            overton_coarse_results,
            overton_extended_results,
        ],
        ignore_index=True,
    )
    .drop_duplicates(
        subset="K"
    )
    .sort_values("K")
    .reset_index(drop=True)
)

display(overton_k_screen)

In [ ]:
fig, ax = plt.subplots(
    figsize=(8, 5)
)

ax.plot(
    overton_k_screen["K"],
    overton_k_screen["Perplexity"],
    marker="o",
)

ax.set_xlabel(
    "Number of Topics (K)"
)

ax.set_ylabel(
    "Held-Out Perplexity"
)

ax.set_title(
    "Overton LDA Topic-Number Screening"
)

ax.grid(
    alpha=0.3
)

plt.tight_layout()
plt.show()

### 5.3 Multi-Criterion Candidate Evaluation

Because held-out perplexity continued to decrease throughout the
screening range, perplexity alone does not provide a finite optimum
for the number of topics.

Candidate models at \(K=30,50,70,\) and \(100\) are therefore
re-estimated using longer Gibbs chains and evaluated using held-out
perplexity, semantic coherence, topic distinctiveness, and thematic
interpretability.

In [ ]:
K_CANDIDATES = [
    30,
    50,
    70,
    100,
]

CANDIDATE_BURN_IN = 500
CANDIDATE_ITERATIONS = 1000
CANDIDATE_THIN = 50

TOP_N_COHERENCE = 10

print("Candidate K values :", K_CANDIDATES)
print("Burn-in           :", CANDIDATE_BURN_IN)
print("Iterations        :", CANDIDATE_ITERATIONS)
print("Thin              :", CANDIDATE_THIN)
print("Coherence top-N   :", TOP_N_COHERENCE)

In [ ]:
R_CANDIDATE_SCRIPT = (
    LDA_DIR
    / "domain_filtered_candidate_evaluation.R"
)

r_candidate_code = r'''
args <- commandArgs(trailingOnly = TRUE)

processed_file <- args[1]
train_file     <- args[2]
output_dir     <- args[3]
min_doc_freq   <- as.integer(args[4])

suppressPackageStartupMessages({
    library(tm)
    library(slam)
    library(topicmodels)
})

MIN_TERM_LENGTH <- 3
MIN_DOC_FREQ <- min_doc_freq

K_VALUES <- c(
    30, 50, 70, 100
)

BURN_IN <- 500
ITERATIONS <- 1000
THIN <- 50

TOP_N <- 10

dir.create(
    output_dir,
    recursive = TRUE,
    showWarnings = FALSE
)

# ============================================================
# Load domain-filtered processed corpus
# ============================================================

data <- read.csv(
    processed_file,
    stringsAsFactors = FALSE,
    check.names = FALSE,
    fileEncoding = "UTF-8"
)

processed <- data$processed_text

valid <- (
    !is.na(processed)
    & nzchar(trimws(processed))
)

processed <- processed[valid]

corpus <- VCorpus(
    VectorSource(processed)
)

# ============================================================
# Reconstruct final DTM
# ============================================================

dtm <- DocumentTermMatrix(
    corpus,
    control = list(
        wordLengths = c(
            MIN_TERM_LENGTH,
            Inf
        )
    )
)

doc_freq <- slam::col_sums(
    dtm > 0
)

dtm <- dtm[
    ,
    doc_freq >= MIN_DOC_FREQ
]

# ============================================================
# Training / held-out split
# ============================================================

train_id <- read.csv(
    train_file
)$train_id

test_id <- setdiff(
    seq_len(dtm$nrow),
    train_id
)

dtm_train <- dtm[
    train_id,
]

dtm_test <- dtm[
    test_id,
]

# Vocabulary represented in training.
train_terms <- (
    slam::col_sums(
        dtm_train > 0
    ) > 0
)

dtm_train <- dtm_train[
    ,
    train_terms
]

dtm_test <- dtm_test[
    ,
    train_terms
]

# Remove empty documents.
train_nonempty <- (
    slam::row_sums(dtm_train) > 0
)

test_nonempty <- (
    slam::row_sums(dtm_test) > 0
)

n_empty_train <- sum(
    !train_nonempty
)

n_empty_test <- sum(
    !test_nonempty
)

dtm_train <- dtm_train[
    train_nonempty,
]

dtm_test <- dtm_test[
    test_nonempty,
]

cat(
    "Training documents:",
    dtm_train$nrow,
    "\n"
)

cat(
    "Held-out documents:",
    dtm_test$nrow,
    "\n"
)

cat(
    "Vocabulary:",
    dtm_train$ncol,
    "\n"
)

cat(
    "Minimum document frequency:",
    MIN_DOC_FREQ,
    "\n"
)

cat(
    "Empty training removed:",
    n_empty_train,
    "\n"
)

cat(
    "Empty held-out removed:",
    n_empty_test,
    "\n\n"
)

# ============================================================
# Binary training DTM for semantic coherence
# ============================================================

binary_train <- dtm_train
binary_train$v[] <- 1

term_doc_freq <- slam::col_sums(
    binary_train
)

# ============================================================
# Semantic coherence
# ============================================================

topic_coherence <- function(
    top_indices,
    binary_dtm,
    term_df
) {

    score <- 0

    for (m in 2:length(top_indices)) {

        for (l in 1:(m - 1)) {

            term_m <- top_indices[m]
            term_l <- top_indices[l]

            docs_m <- binary_dtm$i[
                binary_dtm$j == term_m
            ]

            docs_l <- binary_dtm$i[
                binary_dtm$j == term_l
            ]

            cooccur <- length(
                intersect(
                    docs_m,
                    docs_l
                )
            )

            score <- score + log(
                (cooccur + 1)
                / term_df[term_l]
            )
        }
    }

    score
}

# ============================================================
# Model-level results
# ============================================================

model_results <- data.frame(
    K = integer(),
    Perplexity = numeric(),
    Mean_Coherence = numeric(),
    Median_Coherence = numeric(),
    Min_Coherence = numeric(),
    Mean_Similarity = numeric(),
    Median_Similarity = numeric(),
    Max_Similarity = numeric(),
    Elapsed_seconds = numeric()
)

# ============================================================
# Fit candidate models
# ============================================================

for (k in K_VALUES) {

    cat(
        "Fitting K =",
        k,
        "...\n"
    )

    flush.console()

    start_time <- Sys.time()

    lda_model <- topicmodels::LDA(
        dtm_train,
        k = k,
        method = "Gibbs",
        control = list(
            seed = 123,
            burnin = BURN_IN,
            iter = ITERATIONS,
            thin = THIN
        )
    )

    # --------------------------------------------------------
    # Held-out perplexity
    # --------------------------------------------------------

    heldout_perplexity <- (
        topicmodels::perplexity(
            lda_model,
            newdata = dtm_test
        )
    )

    # --------------------------------------------------------
    # Topic-word probabilities
    # --------------------------------------------------------

    posterior_model <- topicmodels::posterior(
        lda_model
    )

    beta <- posterior_model$terms

    # --------------------------------------------------------
    # Coherence and top terms
    # --------------------------------------------------------

    coherence_values <- numeric(k)

    top_term_records <- list()

    for (topic_id in seq_len(k)) {

        top_indices <- order(
            beta[
                topic_id,
            ],
            decreasing = TRUE
        )[seq_len(TOP_N)]

        coherence_values[
            topic_id
        ] <- topic_coherence(
            top_indices,
            binary_train,
            term_doc_freq
        )

        top_term_records[[
            topic_id
        ]] <- data.frame(
            Topic = topic_id,
            Rank = seq_len(TOP_N),
            Term = colnames(beta)[
                top_indices
            ],
            Probability = beta[
                topic_id,
                top_indices
            ]
        )
    }

    top_terms <- do.call(
        rbind,
        top_term_records
    )

    # --------------------------------------------------------
    # Topic cosine similarity
    # --------------------------------------------------------

    beta_norm <- beta / sqrt(
        rowSums(
            beta^2
        )
    )

    similarity_matrix <- (
        beta_norm
        %*%
        t(beta_norm)
    )

    similarity_values <- (
        similarity_matrix[
            upper.tri(
                similarity_matrix
            )
        ]
    )

    # --------------------------------------------------------
    # Runtime
    # --------------------------------------------------------

    elapsed <- as.numeric(
        difftime(
            Sys.time(),
            start_time,
            units = "secs"
        )
    )

    # --------------------------------------------------------
    # Model-level diagnostics
    # --------------------------------------------------------

    model_results <- rbind(
        model_results,
        data.frame(
            K = k,
            Perplexity = heldout_perplexity,
            Mean_Coherence = mean(
                coherence_values
            ),
            Median_Coherence = median(
                coherence_values
            ),
            Min_Coherence = min(
                coherence_values
            ),
            Mean_Similarity = mean(
                similarity_values
            ),
            Median_Similarity = median(
                similarity_values
            ),
            Max_Similarity = max(
                similarity_values
            ),
            Elapsed_seconds = elapsed
        )
    )

    # --------------------------------------------------------
    # Save topic-level coherence
    # --------------------------------------------------------

    write.csv(
        data.frame(
            Topic = seq_len(k),
            Coherence = coherence_values
        ),
        file.path(
            output_dir,
            paste0(
                "coherence_K",
                k,
                ".csv"
            )
        ),
        row.names = FALSE
    )

    # --------------------------------------------------------
    # Save top terms
    # --------------------------------------------------------

    write.csv(
        top_terms,
        file.path(
            output_dir,
            paste0(
                "top_terms_K",
                k,
                ".csv"
            )
        ),
        row.names = FALSE
    )

    # --------------------------------------------------------
    # Save beta
    # --------------------------------------------------------

    beta_df <- data.frame(
        Topic = seq_len(k),
        beta,
        check.names = FALSE
    )

    write.csv(
        beta_df,
        file.path(
            output_dir,
            paste0(
                "beta_K",
                k,
                ".csv"
            )
        ),
        row.names = FALSE
    )

    # Save after every completed candidate.
    write.csv(
        model_results,
        file.path(
            output_dir,
            "candidate_diagnostics.csv"
        ),
        row.names = FALSE
    )

    cat(
        sprintf(
            paste0(
                "K=%d | ",
                "perplexity=%.4f | ",
                "mean coherence=%.4f | ",
                "mean similarity=%.4f | ",
                "%.2f s\n"
            ),
            k,
            heldout_perplexity,
            mean(coherence_values),
            mean(similarity_values),
            elapsed
        )
    )

    flush.console()
}
'''

R_CANDIDATE_SCRIPT.write_text(
    r_candidate_code,
    encoding="utf-8",
)

print(
    "Created:",
    R_CANDIDATE_SCRIPT
)

In [ ]:
corpus_name = "overton"

processed_file = (
    R_PREPROCESS_DIR
    / f"{corpus_name}_domain_filtered_processed.csv"
)

train_file = (
    LDA_DIR
    / f"{corpus_name}_domain_filtered_train_indices.csv"
)

candidate_output_dir = (
    LDA_DIR
    / "overton_domain_filtered_candidates"
)

candidate_output_dir.mkdir(
    parents=True,
    exist_ok=True,
)

n_documents = int(
    final_dtm_summaries[
        corpus_name
    ].iloc[0]["Documents"]
)

min_doc_freq = math.ceil(
    n_documents * MIN_DOC_PERCENT
)

print(
    "Running domain-filtered Overton candidate evaluation..."
)

print(
    "K values:",
    K_CANDIDATES
)

print(
    "Minimum DF:",
    min_doc_freq
)

candidate_run = subprocess.run(
    [
        str(RSCRIPT),
        str(R_CANDIDATE_SCRIPT),
        str(processed_file),
        str(train_file),
        str(candidate_output_dir),
        str(min_doc_freq),
    ],
    capture_output=True,
    text=True,
    check=False,
)

print(
    "Return code:",
    candidate_run.returncode
)

if candidate_run.stdout.strip():
    print("\nR output:")
    print(candidate_run.stdout)

if candidate_run.stderr.strip():
    print("\nR messages:")
    print(candidate_run.stderr)

In [ ]:
candidate_diagnostics_file = (
    candidate_output_dir
    / "candidate_diagnostics.csv"
)

print(
    "Diagnostics file:",
    candidate_diagnostics_file
)

if candidate_diagnostics_file.exists():

    overton_candidate_diagnostics = pd.read_csv(
        candidate_diagnostics_file
    )

    display(
        overton_candidate_diagnostics
    )

else:

    print(
        "No completed candidate diagnostics were found."
    )

In [ ]:
overton_model_comparison = (
    overton_candidate_diagnostics[
        [
            "K",
            "Perplexity",
            "Mean_Coherence",
            "Mean_Similarity",
        ]
    ]
    .copy()
)

# Lower perplexity is better.
overton_model_comparison[
    "Perplexity_Rank"
] = (
    overton_model_comparison[
        "Perplexity"
    ]
    .rank(
        ascending=True,
        method="min",
    )
)

# Higher / less-negative coherence is better.
overton_model_comparison[
    "Coherence_Rank"
] = (
    overton_model_comparison[
        "Mean_Coherence"
    ]
    .rank(
        ascending=False,
        method="min",
    )
)

# Lower inter-topic similarity is better.
overton_model_comparison[
    "Similarity_Rank"
] = (
    overton_model_comparison[
        "Mean_Similarity"
    ]
    .rank(
        ascending=True,
        method="min",
    )
)

overton_model_comparison[
    "Mean_Rank"
] = (
    overton_model_comparison[
        [
            "Perplexity_Rank",
            "Coherence_Rank",
            "Similarity_Rank",
        ]
    ]
    .mean(axis=1)
)

overton_model_comparison = (
    overton_model_comparison
    .sort_values(
        [
            "Mean_Rank",
            "K",
        ]
    )
    .reset_index(drop=True)
)

overton_model_comparison

#### 5.3.1 Topic Interpretability and Granularity

The numerical diagnostics reveal a trade-off between predictive
performance and semantic coherence. Candidate models are therefore
inspected for thematic interpretability and excessive topic
fragmentation before selecting the final number of topics.

In [ ]:
overton_candidate_top_terms = {}

for k in K_CANDIDATES:

    top_terms_file = (
        candidate_output_dir
        / f"top_terms_K{k}.csv"
    )

    top_terms_df = pd.read_csv(
        top_terms_file
    )

    overton_candidate_top_terms[k] = (
        top_terms_df
    )

    topic_summary = (
        top_terms_df[
            top_terms_df["Rank"] <= 10
        ]
        .groupby("Topic")["Term"]
        .apply(
            lambda terms: ", ".join(terms)
        )
        .reset_index(
            name="Top_Terms"
        )
    )

    print(f"\nK = {k}")
    print("-" * 20)

    display(topic_summary)

### 5.4 Scopus Topic-Number Selection

The same model-selection procedure is applied independently to the
domain-filtered Scopus corpus. A coarse topic-number search is first
performed using short Gibbs chains and held-out perplexity. The search
is subsequently extended if perplexity continues to decrease at the
upper boundary.

In [ ]:
R_SCOPUS_COARSE_SCRIPT = (
    LDA_DIR
    / "domain_filtered_coarse_k_search.R"
)

print(
    "Scopus coarse-search script:",
    R_SCOPUS_COARSE_SCRIPT
)

In [ ]:
corpus_name = "scopus"

processed_file = (
    R_PREPROCESS_DIR
    / f"{corpus_name}_domain_filtered_processed.csv"
)

train_file = (
    LDA_DIR
    / f"{corpus_name}_domain_filtered_train_indices.csv"
)

coarse_output = (
    LDA_DIR
    / f"{corpus_name}_domain_filtered_coarse_k_search.csv"
)

n_documents = int(
    final_dtm_summaries[
        corpus_name
    ].iloc[0]["Documents"]
)

min_doc_freq = math.ceil(
    n_documents * MIN_DOC_PERCENT
)

print(
    "Running domain-filtered Scopus coarse K search..."
)

print(
    "Documents       :",
    f"{n_documents:,}"
)

print(
    "Minimum DF      :",
    min_doc_freq
)

print(
    "K values        :",
    K_COARSE
)

scopus_coarse_run = subprocess.run(
    [
        str(RSCRIPT),
        str(R_SCOPUS_COARSE_SCRIPT),
        str(processed_file),
        str(train_file),
        str(coarse_output),
        str(min_doc_freq),
    ],
    capture_output=True,
    text=True,
    check=False,
)

print(
    "Return code:",
    scopus_coarse_run.returncode
)

if scopus_coarse_run.stdout.strip():

    print("\nR output:")
    print(
        scopus_coarse_run.stdout
    )

if scopus_coarse_run.stderr.strip():

    print("\nR messages:")
    print(
        scopus_coarse_run.stderr
    )

if coarse_output.exists():

    scopus_coarse_results = pd.read_csv(
        coarse_output
    )

    print(
        "\nCompleted K values:",
        scopus_coarse_results[
            "K"
        ].tolist()
    )

    display(
        scopus_coarse_results
    )

else:

    print(
        "\nNo completed Scopus K values were saved."
    )

extended

In [ ]:
R_SCOPUS_EXTENDED_SCRIPT = (
    LDA_DIR
    / "domain_filtered_extended_k_search.R"
)

In [ ]:
K_EXTENDED = [
    60,
    70,
    80,
    100,
]

corpus_name = "scopus"

processed_file = (
    R_PREPROCESS_DIR
    / f"{corpus_name}_domain_filtered_processed.csv"
)

train_file = (
    LDA_DIR
    / f"{corpus_name}_domain_filtered_train_indices.csv"
)

extended_output = (
    LDA_DIR
    / f"{corpus_name}_domain_filtered_extended_k_search.csv"
)

n_documents = int(
    final_dtm_summaries[
        corpus_name
    ].iloc[0]["Documents"]
)

min_doc_freq = math.ceil(
    n_documents * MIN_DOC_PERCENT
)

print(
    "Running domain-filtered Scopus extended K search..."
)

print(
    "Documents       :",
    f"{n_documents:,}"
)

print(
    "Minimum DF      :",
    min_doc_freq
)

print(
    "K values        :",
    K_EXTENDED
)

scopus_extended_run = subprocess.run(
    [
        str(RSCRIPT),
        str(R_SCOPUS_EXTENDED_SCRIPT),
        str(processed_file),
        str(train_file),
        str(extended_output),
        str(min_doc_freq),
    ],
    capture_output=True,
    text=True,
    check=False,
)

print(
    "Return code:",
    scopus_extended_run.returncode
)

if scopus_extended_run.stdout.strip():
    print("\nR output:")
    print(
        scopus_extended_run.stdout
    )

if scopus_extended_run.stderr.strip():
    print("\nR messages:")
    print(
        scopus_extended_run.stderr
    )

if extended_output.exists():

    scopus_extended_results = pd.read_csv(
        extended_output
    )

    print(
        "\nCompleted K values:",
        scopus_extended_results[
            "K"
        ].tolist()
    )

    display(
        scopus_extended_results
    )

else:

    print(
        "\nNo completed extended K values were saved."
    )

#### 5.4.1 Scopus Topic Interpretability and Granularity

The candidate Scopus models are inspected for thematic
interpretability and topic fragmentation. This complements the
quantitative comparison based on held-out perplexity, semantic
coherence, and inter-topic similarity.

In [ ]:
LDA_DIR = OUTPUT_DIR / "lda"

LDA_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

print("LDA directory:", LDA_DIR)

In [ ]:
K_CANDIDATES = [
    30,
    50,
    70,
    100,
]

scopus_candidate_output_dir = (
    LDA_DIR
    / "scopus_domain_filtered_candidates"
)

scopus_candidate_diagnostics = pd.read_csv(
    scopus_candidate_output_dir
    / "candidate_diagnostics.csv"
)

display(
    scopus_candidate_diagnostics
)

In [ ]:
scopus_candidate_top_terms = {}

scopus_candidate_output_dir = (
    LDA_DIR
    / "scopus_domain_filtered_candidates"
)

for k in K_CANDIDATES:

    top_terms_file = (
        scopus_candidate_output_dir
        / f"top_terms_K{k}.csv"
    )

    if not top_terms_file.exists():
        raise FileNotFoundError(
            f"Missing file: {top_terms_file}"
        )

    top_terms_df = pd.read_csv(
        top_terms_file
    )

    scopus_candidate_top_terms[
        k
    ] = top_terms_df

    topic_summary = (
        top_terms_df[
            top_terms_df["Rank"] <= 10
        ]
        .groupby(
            "Topic"
        )["Term"]
        .apply(
            lambda terms: ", ".join(terms)
        )
        .reset_index(
            name="Top_Terms"
        )
    )

    print(f"\nK = {k}")
    print("-" * 20)

    display(
        topic_summary
    )

### 5.5 Final Topic-Number Selection

For both corpora, increasing the number of topics improved held-out
perplexity and reduced mean inter-topic similarity, but progressively
reduced semantic coherence and produced increasingly fine-grained topic
fragmentation.

Inspection of candidate topic structures showed that the 30-topic
models combined several substantively distinct themes, whereas the
70- and 100-topic models increasingly divided established themes into
narrower or partially overlapping components. The 50-topic models
provided a suitable balance between predictive performance, semantic
coherence, topic distinctiveness, and substantive interpretability.

Accordingly, the final number of topics was selected independently as
\(K=50\) for both the Overton and Scopus corpora.

## 6. Final LDA Models

Following model selection, the final LDA models are estimated using all
documents in each domain-filtered corpus. The training/held-out split
used for model selection is no longer required at this stage.

Both final models use 50 topics and are estimated using longer Gibbs
chains to obtain more stable topic-word and document-topic
distributions.

In [2]:
import shutil
from pathlib import Path
import math
import pandas as pd
import subprocess

# ---------------------------------------------------------
# Project paths
# ---------------------------------------------------------

PROJECT_DIR = Path(
    "/nfs/mfirdausi/project/review_paper_2"
)

OUTPUT_DIR = (
    PROJECT_DIR
    / "output"
)

R_PREPROCESS_DIR = (
    OUTPUT_DIR
    / "r_preprocessing"
)

LDA_DIR = (
    OUTPUT_DIR
    / "lda"
)

# ---------------------------------------------------------
# R executable
# ---------------------------------------------------------

rscript_path = shutil.which("Rscript")

if rscript_path is None:
    raise FileNotFoundError(
        "Rscript was not found in PATH."
    )

RSCRIPT = Path(
    rscript_path
)

# ---------------------------------------------------------
# Final R script
# ---------------------------------------------------------

R_FINAL_LDA_SCRIPT = (
    LDA_DIR
    / "fit_final_domain_filtered_lda.R"
)

# ---------------------------------------------------------
# Final LDA configuration
# ---------------------------------------------------------

FINAL_K = {
    "overton": 50,
    "scopus": 50,
}

FINAL_BURN_IN = 2000
FINAL_ITERATIONS = 10000
FINAL_THIN = 100
FINAL_RANDOM_SEED = 123

# Final vocabulary rule:
# minimum document frequency = 0.2% of corpus documents.
MIN_DOC_PERCENT = 0.002

# ---------------------------------------------------------
# Validate directories/files
# ---------------------------------------------------------

required_paths = [
    PROJECT_DIR,
    OUTPUT_DIR,
    R_PREPROCESS_DIR,
    LDA_DIR,
    R_FINAL_LDA_SCRIPT,
]

for path in required_paths:

    if not path.exists():
        raise FileNotFoundError(
            f"Required path does not exist: {path}"
        )

# ---------------------------------------------------------
# Diagnostics
# ---------------------------------------------------------

print("Section 6 configuration")
print("-----------------------")

print(
    "Project directory :",
    PROJECT_DIR
)

print(
    "Output directory  :",
    OUTPUT_DIR
)

print(
    "Rscript           :",
    RSCRIPT
)

print(
    "R preprocessing   :",
    R_PREPROCESS_DIR
)

print(
    "LDA directory     :",
    LDA_DIR
)

print(
    "Final R script    :",
    R_FINAL_LDA_SCRIPT
)

print(
    "R script exists   :",
    R_FINAL_LDA_SCRIPT.exists()
)

print()

print(
    "Final K           :",
    FINAL_K
)

print(
    "Burn-in           :",
    FINAL_BURN_IN
)

print(
    "Iterations        :",
    FINAL_ITERATIONS
)

print(
    "Thin              :",
    FINAL_THIN
)

print(
    "Min DF fraction   :",
    MIN_DOC_PERCENT
)

Section 6 configuration
-----------------------
Project directory : /nfs/mfirdausi/project/review_paper_2
Output directory  : /nfs/mfirdausi/project/review_paper_2/output
Rscript           : /nfs/mfirdausi/miniconda3/envs/pytorch/bin/Rscript
R preprocessing   : /nfs/mfirdausi/project/review_paper_2/output/r_preprocessing
LDA directory     : /nfs/mfirdausi/project/review_paper_2/output/lda
Final R script    : /nfs/mfirdausi/project/review_paper_2/output/lda/fit_final_domain_filtered_lda.R
R script exists   : True

Final K           : {'overton': 50, 'scopus': 50}
Burn-in           : 2000
Iterations        : 10000
Thin              : 100
Min DF fraction   : 0.002

### 6.1 Final LDA configuration

In [3]:
FINAL_K = {
    "overton": 50,
    "scopus": 50,
}

FINAL_BURN_IN = 2000
FINAL_ITERATIONS = 10000
FINAL_THIN = 100
FINAL_RANDOM_SEED = 123

print("Final LDA configuration")
print("-----------------------")

for corpus_name, k in FINAL_K.items():
    print(
        f"{corpus_name.upper():8s} : K = {k}"
    )

print()
print("Burn-in    :", FINAL_BURN_IN)
print("Iterations :", FINAL_ITERATIONS)
print("Thin       :", FINAL_THIN)
print("Seed       :", FINAL_RANDOM_SEED)

Final LDA configuration
-----------------------
OVERTON  : K = 50
SCOPUS   : K = 50

Burn-in    : 2000
Iterations : 10000
Thin       : 100
Seed       : 123

### 6.2 Create the final R script

In [4]:
R_FINAL_LDA_SCRIPT = (
    LDA_DIR
    / "fit_final_domain_filtered_lda.R"
)

r_final_lda_code = r'''
args <- commandArgs(trailingOnly = TRUE)

processed_file <- args[1]
output_dir     <- args[2]
min_doc_freq   <- as.integer(args[3])
k              <- as.integer(args[4])

suppressPackageStartupMessages({
    library(tm)
    library(slam)
    library(topicmodels)
})

MIN_TERM_LENGTH <- 3

BURN_IN <- 2000
ITERATIONS <- 10000
THIN <- 100
RANDOM_SEED <- 123

TOP_N <- 20

dir.create(
    output_dir,
    recursive = TRUE,
    showWarnings = FALSE
)

# ============================================================
# Load complete processed corpus
# ============================================================

data <- read.csv(
    processed_file,
    stringsAsFactors = FALSE,
    check.names = FALSE,
    fileEncoding = "UTF-8"
)

processed <- data$processed_text

valid <- (
    !is.na(processed)
    & nzchar(trimws(processed))
)

original_id <- which(valid)

processed <- processed[
    valid
]

corpus <- VCorpus(
    VectorSource(processed)
)

# ============================================================
# Construct final DTM
# ============================================================

dtm <- DocumentTermMatrix(
    corpus,
    control = list(
        wordLengths = c(
            MIN_TERM_LENGTH,
            Inf
        )
    )
)

doc_freq <- slam::col_sums(
    dtm > 0
)

dtm <- dtm[
    ,
    doc_freq >= min_doc_freq
]

# Remove any documents that become empty after vocabulary filtering.
nonempty <- (
    slam::row_sums(dtm) > 0
)

original_id <- original_id[
    nonempty
]

dtm <- dtm[
    nonempty,
]

cat(
    "Documents:",
    dtm$nrow,
    "\n"
)

cat(
    "Vocabulary:",
    dtm$ncol,
    "\n"
)

cat(
    "Tokens:",
    sum(dtm$v),
    "\n"
)

cat(
    "K:",
    k,
    "\n"
)

cat(
    "Minimum DF:",
    min_doc_freq,
    "\n\n"
)

# ============================================================
# Final Gibbs LDA
# ============================================================

start_time <- Sys.time()

lda_model <- topicmodels::LDA(
    dtm,
    k = k,
    method = "Gibbs",
    control = list(
        seed = RANDOM_SEED,
        burnin = BURN_IN,
        iter = ITERATIONS,
        thin = THIN
    )
)

elapsed <- as.numeric(
    difftime(
        Sys.time(),
        start_time,
        units = "secs"
    )
)

posterior_model <- topicmodels::posterior(
    lda_model
)

beta <- posterior_model$terms
theta <- posterior_model$topics

# ============================================================
# Save beta
# ============================================================

beta_df <- data.frame(
    Topic = seq_len(k),
    beta,
    check.names = FALSE
)

write.csv(
    beta_df,
    file.path(
        output_dir,
        "beta.csv"
    ),
    row.names = FALSE
)

# ============================================================
# Save theta
# ============================================================

theta_df <- data.frame(
    document_id = original_id,
    theta,
    check.names = FALSE
)

write.csv(
    theta_df,
    file.path(
        output_dir,
        "theta.csv"
    ),
    row.names = FALSE
)

# ============================================================
# Top terms
# ============================================================

top_term_records <- list()

for (topic_id in seq_len(k)) {

    ord <- order(
        beta[
            topic_id,
        ],
        decreasing = TRUE
    )[seq_len(TOP_N)]

    top_term_records[[
        topic_id
    ]] <- data.frame(
        Topic = topic_id,
        Rank = seq_len(TOP_N),
        Term = colnames(beta)[
            ord
        ],
        Probability = beta[
            topic_id,
            ord
        ]
    )
}

top_terms <- do.call(
    rbind,
    top_term_records
)

write.csv(
    top_terms,
    file.path(
        output_dir,
        "top_terms.csv"
    ),
    row.names = FALSE
)

# ============================================================
# Dominant topic
# ============================================================

dominant_topic <- max.col(
    theta,
    ties.method = "first"
)

dominant_probability <- apply(
    theta,
    1,
    max
)

document_topics <- data.frame(
    document_id = original_id,
    Dominant_Topic = dominant_topic,
    Dominant_Probability = dominant_probability
)

write.csv(
    document_topics,
    file.path(
        output_dir,
        "document_topics.csv"
    ),
    row.names = FALSE
)

# ============================================================
# Topic prevalence
# ============================================================

topic_prevalence <- colMeans(
    theta
)

prevalence_df <- data.frame(
    Topic = seq_len(k),
    Mean_Probability = topic_prevalence
)

prevalence_df <- prevalence_df[
    order(
        prevalence_df$Mean_Probability,
        decreasing = TRUE
    ),
]

write.csv(
    prevalence_df,
    file.path(
        output_dir,
        "topic_prevalence.csv"
    ),
    row.names = FALSE
)

# ============================================================
# Final summary
# ============================================================

summary_df <- data.frame(
    Documents = dtm$nrow,
    Vocabulary = dtm$ncol,
    Tokens = sum(dtm$v),
    K = k,
    Minimum_DF = min_doc_freq,
    Burn_in = BURN_IN,
    Iterations = ITERATIONS,
    Thin = THIN,
    Seed = RANDOM_SEED,
    Elapsed_seconds = elapsed
)

write.csv(
    summary_df,
    file.path(
        output_dir,
        "model_summary.csv"
    ),
    row.names = FALSE
)

cat(
    "Final LDA completed in",
    round(elapsed, 2),
    "seconds.\n"
)
'''

R_FINAL_LDA_SCRIPT.write_text(
    r_final_lda_code,
    encoding="utf-8",
)

print(
    "Created:",
    R_FINAL_LDA_SCRIPT
)

Created: /nfs/mfirdausi/project/review_paper_2/output/lda/fit_final_domain_filtered_lda.R

### 6.3 Final Overton LDA Model

The final Overton LDA model is estimated on the complete
domain-filtered corpus using \(K=50\). The longer Gibbs chain is used
for final estimation after completion of topic-number selection.

In [5]:
corpus_name = "overton"

processed_file = (
    R_PREPROCESS_DIR
    / f"{corpus_name}_domain_filtered_processed.csv"
)

dtm_summary_file = (
    R_PREPROCESS_DIR
    / f"{corpus_name}_final_dtm_summary.csv"
)

final_output_dir = (
    LDA_DIR
    / "final_overton_k50"
)

final_output_dir.mkdir(
    parents=True,
    exist_ok=True,
)

# ---------------------------------------------------------
# Load final DTM information from disk
# ---------------------------------------------------------

dtm_summary = pd.read_csv(
    dtm_summary_file
)

n_documents = int(
    dtm_summary.loc[
        0,
        "Documents"
    ]
)

min_doc_freq = math.ceil(
    n_documents * MIN_DOC_PERCENT
)

k = FINAL_K[
    corpus_name
]

# ---------------------------------------------------------
# Validate required files
# ---------------------------------------------------------

for required_file in [
    processed_file,
    dtm_summary_file,
    R_FINAL_LDA_SCRIPT,
]:

    if not required_file.exists():
        raise FileNotFoundError(
            f"Missing required file: {required_file}"
        )

# ---------------------------------------------------------
# Final Overton LDA
# ---------------------------------------------------------

print("Running final Overton LDA...")
print("-----------------------------")
print("Documents  :", f"{n_documents:,}")
print("K          :", k)
print("Minimum DF :", min_doc_freq)
print("Burn-in    :", FINAL_BURN_IN)
print("Iterations :", FINAL_ITERATIONS)
print("Thin       :", FINAL_THIN)

final_overton_run = subprocess.run(
    [
        str(RSCRIPT),
        str(R_FINAL_LDA_SCRIPT),
        str(processed_file),
        str(final_output_dir),
        str(min_doc_freq),
        str(k),
    ],
    capture_output=True,
    text=True,
    check=False,
)

print(
    "\nReturn code:",
    final_overton_run.returncode
)

if final_overton_run.stdout.strip():

    print("\nR output:")
    print(
        final_overton_run.stdout
    )

if final_overton_run.stderr.strip():

    print("\nR messages:")
    print(
        final_overton_run.stderr
    )

Running final Overton LDA...
-----------------------------
Documents  : 5,045
K          : 50
Minimum DF : 11
Burn-in    : 2000
Iterations : 10000
Thin       : 100

Return code: 0

R output:
Documents: 5045
Vocabulary: 2865
Tokens: 512540
K: 50
Minimum DF: 11

Final LDA completed in 397.06 seconds.

### 6.4 Final Scopus LDA Model

The final Scopus LDA model is estimated on the complete
domain-filtered corpus using \(K=50\) and the same final Gibbs-sampling
configuration used for Overton.

In [8]:
corpus_name = "scopus"

processed_file = (
    R_PREPROCESS_DIR
    / f"{corpus_name}_domain_filtered_processed.csv"
)

dtm_summary_file = (
    R_PREPROCESS_DIR
    / f"{corpus_name}_final_dtm_summary.csv"
)

final_output_dir = (
    LDA_DIR
    / "final_scopus_k50"
)

final_output_dir.mkdir(
    parents=True,
    exist_ok=True,
)

# ---------------------------------------------------------
# Load final DTM information
# ---------------------------------------------------------

dtm_summary = pd.read_csv(
    dtm_summary_file
)

n_documents = int(
    dtm_summary.loc[
        0,
        "Documents"
    ]
)

min_doc_freq = math.ceil(
    n_documents * MIN_DOC_PERCENT
)

k = FINAL_K[
    corpus_name
]

# ---------------------------------------------------------
# Validate required files
# ---------------------------------------------------------

for required_file in [
    processed_file,
    dtm_summary_file,
    R_FINAL_LDA_SCRIPT,
]:

    if not required_file.exists():

        raise FileNotFoundError(
            f"Missing required file: {required_file}"
        )

# ---------------------------------------------------------
# Final Scopus LDA
# ---------------------------------------------------------

print("Running final Scopus LDA...")
print("----------------------------")
print("Documents  :", f"{n_documents:,}")
print("K          :", k)
print("Minimum DF :", min_doc_freq)
print("Burn-in    :", FINAL_BURN_IN)
print("Iterations :", FINAL_ITERATIONS)
print("Thin       :", FINAL_THIN)

final_scopus_run = subprocess.run(
    [
        str(RSCRIPT),
        str(R_FINAL_LDA_SCRIPT),
        str(processed_file),
        str(final_output_dir),
        str(min_doc_freq),
        str(k),
    ],
    capture_output=True,
    text=True,
    check=False,
)

print(
    "\nReturn code:",
    final_scopus_run.returncode
)

if final_scopus_run.stdout.strip():

    print("\nR output:")
    print(
        final_scopus_run.stdout
    )

if final_scopus_run.stderr.strip():

    print("\nR messages:")
    print(
        final_scopus_run.stderr
    )

Running final Scopus LDA...
----------------------------
Documents  : 12,042
K          : 50
Minimum DF : 25
Burn-in    : 2000
Iterations : 10000
Thin       : 100

Return code: 0

R output:
Documents: 12042
Vocabulary: 2737
Tokens: 1384122
K: 50
Minimum DF: 25

Final LDA completed in 1096.87 seconds.

## 7. Topic Analysis and Cross-Corpus Comparison

### 7.1 Topic Interpretation and Labeling

#### 7.1.1 Load Final LDA Outputs

In [9]:
# ---------------------------------------------------------
# Final model directories
# ---------------------------------------------------------

FINAL_MODEL_DIRS = {
    "overton": (
        LDA_DIR
        / "final_overton_k50"
    ),
    "scopus": (
        LDA_DIR
        / "final_scopus_k50"
    ),
}

final_lda = {}

for corpus_name, model_dir in FINAL_MODEL_DIRS.items():

    required_files = {
        "summary": model_dir / "model_summary.csv",
        "beta": model_dir / "beta.csv",
        "theta": model_dir / "theta.csv",
        "top_terms": model_dir / "top_terms.csv",
        "document_topics": model_dir / "document_topics.csv",
        "prevalence": model_dir / "topic_prevalence.csv",
    }

    # Check that all outputs exist.
    for name, file_path in required_files.items():

        if not file_path.exists():

            raise FileNotFoundError(
                f"Missing {corpus_name} {name}: "
                f"{file_path}"
            )

    final_lda[corpus_name] = {
        name: pd.read_csv(file_path)
        for name, file_path
        in required_files.items()
    }

    print(corpus_name.upper())
    print("-" * len(corpus_name))

    print(
        "Beta shape          :",
        final_lda[corpus_name]["beta"].shape
    )

    print(
        "Theta shape         :",
        final_lda[corpus_name]["theta"].shape
    )

    print(
        "Top-term rows       :",
        len(
            final_lda[
                corpus_name
            ]["top_terms"]
        )
    )

    print(
        "Document-topic rows :",
        len(
            final_lda[
                corpus_name
            ]["document_topics"]
        )
    )

    print(
        "Prevalence rows     :",
        len(
            final_lda[
                corpus_name
            ]["prevalence"]
        )
    )

    print()

OVERTON
-------
Beta shape          : (50, 2866)
Theta shape         : (5045, 51)
Top-term rows       : 1000
Document-topic rows : 5045
Prevalence rows     : 50

SCOPUS
------
Beta shape          : (50, 2738)
Theta shape         : (12042, 51)
Top-term rows       : 1000
Document-topic rows : 12042
Prevalence rows     : 50

#### 7.1.2 Validate Topic Distributions

In [10]:
for corpus_name, outputs in final_lda.items():

    beta = (
        outputs["beta"]
        .drop(
            columns=["Topic"]
        )
    )

    theta = (
        outputs["theta"]
        .drop(
            columns=["document_id"]
        )
    )

    beta_row_sums = (
        beta.sum(axis=1)
    )

    theta_row_sums = (
        theta.sum(axis=1)
    )

    print(corpus_name.upper())
    print("-" * len(corpus_name))

    print(
        "Beta row sums  :",
        f"{beta_row_sums.min():.6f}",
        "to",
        f"{beta_row_sums.max():.6f}",
    )

    print(
        "Theta row sums :",
        f"{theta_row_sums.min():.6f}",
        "to",
        f"{theta_row_sums.max():.6f}",
    )

    print()

OVERTON
-------
Beta row sums  : 1.000000 to 1.000000
Theta row sums : 1.000000 to 1.000000

SCOPUS
------
Beta row sums  : 1.000000 to 1.000000
Theta row sums : 1.000000 to 1.000000

#### 7.1.3 Top Terms

In [11]:
TOP_TERMS_DISPLAY = 10

final_topic_terms = {}

for corpus_name, outputs in final_lda.items():

    top_terms = (
        outputs["top_terms"]
        .copy()
    )

    topic_terms = (
        top_terms[
            top_terms["Rank"]
            <= TOP_TERMS_DISPLAY
        ]
        .sort_values(
            [
                "Topic",
                "Rank",
            ]
        )
        .groupby(
            "Topic"
        )["Term"]
        .apply(
            lambda x: ", ".join(x)
        )
        .reset_index(
            name="Top_Terms"
        )
    )

    final_topic_terms[
        corpus_name
    ] = topic_terms

    print()
    print(corpus_name.upper())
    print("=" * len(corpus_name))

    display(
        topic_terms
    )

OVERTON
=======

    Topic                                          Top_Terms
0       1  oper, system, flexibl, plan, integr, consid, c...
1       2  test, condit, result, use, wave, perform, expe...
2       3  effect, factor, rate, increas, depend, also, m...
3       4  design, effici, perform, can, improv, hybrid, ...
4       5  applic, develop, paper, standard, includ, new,...
5       6  term, main, author, relat, concept, take, one,...
6       7  approach, framework, can, present, process, st...
7       8  polici, electr, countri, sector, industri, sup...
8       9  develop, project, engin, research, nation, rig...
9      10  generat, reserv, unit, variabl, penetr, dispat...
10     11  grid, smart, communic, secur, network, attack,...
11     12  electr, vehicl, charg, transport, drive, stati...
12     13  provid, util, servic, regul, can, also, need, ...
13     14  differ, studi, result, type, consid, compar, c...
14     15  chang, climat, water, global, region, scenario...
15     16  challeng, integr, issu, address, solut, techni...
16     17  model, simul, dynam, interact, comput, valid, ...
17     18  impact, studi, analysi, assess, perform, evalu...
18     19  find, adopt, household, benefit, level, sugges...
19     20  distribut, microgrid, control, der, manag, ope...
20     21  system, paper, reliabl, ieee, provid, present,...
21     22  problem, optim, solut, propos, algorithm, comp...
22     23  time, variabl, year, hour, period, averag, hig...
23     24  storag, batteri, energi, generat, use, capac, ...
24     25  estim, state, measur, observ, robust, use, iee...
25     26  distribut, network, fault, ieee, voltag, feede...
26     27  load, meter, smart, consumpt, custom, cluster,...
27     28  technolog, develop, industri, deploy, role, ne...
28     29  demand, energi, build, heat, manag, electr, re...
29     30  research, review, discuss, literatur, recent, ...
30     31  market, electr, price, particip, mechan, trade...
31     32  frequenc, system, stabil, respons, dynam, gene...
32     33  wind, turbin, farm, wake, speed, offshor, blad...
33     34  forecast, predict, model, uncertainti, error, ...
34     35  solar, irradi, radiat, measur, use, cloud, sur...
35     36  method, propos, base, use, techniqu, appli, ap...
36     37  energi, transit, communiti, develop, local, st...
37     38  materi, hydrogen, cell, process, product, high...
38     39  transmiss, line, current, use, transform, high...
39     40  control, propos, strategi, scheme, can, simul,...
40     41  emiss, gas, fuel, carbon, reduc, environment, ...
41     42  energi, renew, sourc, resourc, increas, share,...
42     43  cost, reduc, valu, benefit, reduct, econom, re...
43     44  time, algorithm, use, perform, base, approach,...
44     45  voltag, convert, invert, current, ieee, presen...
45     46  will, need, futur, new, increas, requir, year,...
46     47  event, resili, failur, risk, reliabl, sever, e...
47     48  solar, plant, photovolta, instal, modul, loss,...
48     49  can, first, two, use, larg, second, allow, one...
49     50  data, use, detect, inform, avail, set, center,...

SCOPUS
======

    Topic                                          Top_Terms
0       1  network, neural, train, use, predict, deep, ar...
1       2  voltag, loss, reactiv, activ, bus, ieee, regul...
2       3  estim, state, measur, paramet, method, use, ac...
3       4  market, energi, price, electr, trade, mechan, ...
4       5  can, will, due, issu, one, also, howev, may, m...
5       6  model, develop, propos, simul, linear, datadri...
6       7  microgrid, oper, manag, system, generat, mode,...
7       8  system, reserv, ltd, engin, right, publish, te...
8       9  technolog, energi, intellig, sustain, artifici...
9      10  techniqu, use, differ, perform, various, sugge...
10     11  oper, flexibl, coordin, system, level, provid,...
11     12  framework, across, limit, practic, deploy, int...
12     13  system, optim, devic, locat, use, size, improv...
13     14  first, base, second, final, propos, stage, cha...
14     15  solar, photovolta, generat, capac, studi, plan...
15     16  forecast, predict, model, error, accuraci, mea...
16     17  grid, smart, provid, develop, challeng, increa...
17     18  algorithm, function, optim, object, problem, m...
18     19  energi, emiss, build, carbon, thermal, heat, g...
19     20  cost, reduc, optim, minim, reduct, achiev, tot...
20     21  distribut, direct, algorithm, altern, central,...
21     22  load, demand, electr, respons, peak, consumpt,...
22     23  comput, effici, time, complex, requir, solut, ...
23     24  use, result, present, case, time, two, test, o...
24     25  uncertainti, robust, scenario, stochast, propo...
25     26  system, attack, secur, detect, data, communic,...
26     27  electr, charg, vehicl, station, transport, str...
27     28  dispatch, schedul, oper, unit, generat, econom...
28     29  topolog, graph, physic, featur, structur, atte...
29     30  reinforc, deep, agent, polici, decis, realtim,...
30     31  distribut, network, der, resourc, node, activ,...
31     32  problem, solut, solv, opf, optim, constraint, ...
32     33  system, stabil, transient, dynam, analysi, ass...
33     34  system, plan, natur, author, oper, part, prese...
34     35  convert, current, qualiti, harmon, voltag, hig...
35     36  system, bus, ieee, transmiss, line, secur, tes...
36     37  energi, renew, sourc, integr, manag, system, r...
37     38  energi, storag, system, batteri, hybrid, manag...
38     39  enhanc, effici, challeng, address, signific, i...
39     40  reliabl, system, resili, assess, failur, risk,...
40     41  fault, protect, detect, classif, current, sche...
41     42  algorithm, problem, search, converg, optim, te...
42     43  applic, design, system, research, develop, pro...
43     44  method, propos, base, calcul, paper, can, effe...
44     45  adapt, dynam, condit, effici, improv, perform,...
45     46  control, frequenc, strategi, regul, scheme, sy...
46     47  wind, generat, output, use, speed, result, var...
47     48  propos, approach, result, novel, compar, simul...
48     49  data, cluster, use, process, analysi, inform, ...
49     50  research, review, applic, futur, provid, discu...

#### 7.1.4 Representative Documents

In [31]:
for corpus_name in [
    "overton",
    "scopus",
]:

    saved_abstracts_file = (
        R_PREPROCESS_DIR
        / f"{corpus_name}_domain_filtered_abstracts.csv"
    )

    # Exact abstracts originally supplied to R.
    saved_abstracts = pd.read_csv(
        saved_abstracts_file,
        keep_default_na=False,
    )

    # Metadata corpus reconstructed using the frozen
    # domain-relevance screening.
    reconstructed = (
        lda_corpora_filtered[
            corpus_name
        ]
        .reset_index(drop=True)
        .copy()
    )

    saved_text = (
        saved_abstracts["Abstract"]
        .fillna("")
        .astype(str)
        .str.strip()
        .reset_index(drop=True)
    )

    reconstructed_text = (
        reconstructed["Abstract"]
        .fillna("")
        .astype(str)
        .str.strip()
        .reset_index(drop=True)
    )

    same_length = (
        len(saved_text)
        == len(reconstructed_text)
    )

    if same_length:

        comparison = (
            saved_text
            == reconstructed_text
        )

        n_matching = int(
            comparison.sum()
        )

        n_different = int(
            (~comparison).sum()
        )

        exact_order_match = (
            n_different == 0
        )

    else:

        n_matching = 0
        n_different = abs(
            len(saved_text)
            - len(reconstructed_text)
        )

        exact_order_match = False

    print(corpus_name.upper())
    print("-" * len(corpus_name))

    print(
        f"Saved LDA abstracts : "
        f"{len(saved_text):,}"
    )

    print(
        f"Reconstructed       : "
        f"{len(reconstructed_text):,}"
    )

    print(
        f"Matching rows       : "
        f"{n_matching:,}"
    )

    print(
        f"Different rows      : "
        f"{n_different:,}"
    )

    print(
        "Exact order match   :",
        exact_order_match
    )

    print()

OVERTON
-------
Saved LDA abstracts : 5,045
Reconstructed       : 5,045
Matching rows       : 5,045
Different rows      : 0
Exact order match   : True

SCOPUS
------
Saved LDA abstracts : 12,042
Reconstructed       : 12,042
Matching rows       : 12,042
Different rows      : 0
Exact order match   : True

In [32]:
FILTERED_METADATA_DIR = (
    OUTPUT_DIR
    / "domain_filtered_metadata"
)

FILTERED_METADATA_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

final_metadata = {}

for corpus_name in [
    "overton",
    "scopus",
]:

    metadata = (
        lda_corpora_filtered[
            corpus_name
        ]
        .reset_index(drop=True)
        .copy()
    )

    # R uses 1-based document IDs.
    metadata[
        "document_id"
    ] = (
        metadata.index
        + 1
    )

    final_metadata[
        corpus_name
    ] = metadata

    output_file = (
        FILTERED_METADATA_DIR
        / f"{corpus_name}_domain_filtered_metadata.csv"
    )

    metadata.to_csv(
        output_file,
        index=False,
        encoding="utf-8",
    )

    print(corpus_name.upper())
    print("-" * len(corpus_name))

    print(
        f"Documents : "
        f"{len(metadata):,}"
    )

    print(
        "Saved     :",
        output_file
    )

    print()

OVERTON
-------
Documents : 5,045
Saved     : /nfs/mfirdausi/project/review_paper_2/output/domain_filtered_metadata/overton_domain_filtered_metadata.csv

SCOPUS
------
Documents : 12,042
Saved     : /nfs/mfirdausi/project/review_paper_2/output/domain_filtered_metadata/scopus_domain_filtered_metadata.csv

In [33]:
TOP_REPRESENTATIVE_DOCS = 5

representative_documents = {}

for corpus_name in [
    "overton",
    "scopus",
]:

    theta = (
        final_lda[
            corpus_name
        ]["theta"]
        .copy()
    )

    metadata = (
        final_metadata[
            corpus_name
        ]
        .copy()
    )

    # Topic-probability columns in theta.csv.
    topic_columns = [
        column
        for column in theta.columns
        if column != "document_id"
    ]

    records = []

    for topic_number, topic_column in enumerate(
        topic_columns,
        start=1,
    ):

        topic_scores = (
            theta[
                [
                    "document_id",
                    topic_column,
                ]
            ]
            .rename(
                columns={
                    topic_column:
                    "Topic_Probability"
                }
            )
        )

        topic_scores = (
            topic_scores
            .merge(
                metadata,
                on="document_id",
                how="left",
                validate="one_to_one",
            )
        )

        top_documents = (
            topic_scores
            .nlargest(
                TOP_REPRESENTATIVE_DOCS,
                "Topic_Probability",
            )
            .copy()
        )

        top_documents[
            "Topic"
        ] = topic_number

        top_documents[
            "Representative_Rank"
        ] = range(
            1,
            len(top_documents) + 1
        )

        records.append(
            top_documents
        )

    representative_df = (
        pd.concat(
            records,
            ignore_index=True,
        )
    )

    representative_documents[
        corpus_name
    ] = representative_df

    print(corpus_name.upper())
    print("-" * len(corpus_name))

    print(
        "Topics                  :",
        len(topic_columns)
    )

    print(
        "Documents/topic         :",
        TOP_REPRESENTATIVE_DOCS
    )

    print(
        "Representative doc rows :",
        len(representative_df)
    )

    print()

OVERTON
-------
Topics                  : 50
Documents/topic         : 5
Representative doc rows : 250

SCOPUS
------
Topics                  : 50
Documents/topic         : 5
Representative doc rows : 250

In [34]:
for corpus_name in [
    "overton",
    "scopus",
]:

    print()
    print(corpus_name.upper())
    print("=" * len(corpus_name))

    topic_1 = (
        representative_documents[
            corpus_name
        ]
        .query(
            "Topic == 1"
        )
    )

    display_columns = [
        column
        for column in [
            "Topic",
            "Representative_Rank",
            "Topic_Probability",
            "Title",
            "Year",
            "DOI",
        ]
        if column in topic_1.columns
    ]

    display(
        topic_1[
            display_columns
        ]
    )

OVERTON
=======

,Topic,Representative_Rank,Topic_Probability,Title,Year,DOI
0,1,1,0.242424,Understanding barriers to utilising flexibilit...,2023,10.1016/j.enpol.2023.113618
1,1,2,0.181818,Flexible distributed multienergy generation sy...,2016,10.1109/TSG.2015.2411392
2,1,3,0.167539,Alternatives No More: Wind and Solar Power Are...,2015,10.1109/MPE.2015.2462311
3,1,4,0.161290,Economic assessment of integrating fast-chargi...,2023,10.1016/j.segan.2023.101083
4,1,5,0.157576,Capacity Market Model Considering Flexible Res...,2018,10.1109/PESGM.2018.8586189

SCOPUS
======

,Topic,Representative_Rank,Topic_Probability,Title,Year,DOI
0,1,1,0.234043,Physics-informed machine learning with optimiz...,2024,10.1016/j.ijepes.2023.109741
1,1,2,0.209677,Enriching Neural Network Training Dataset to I...,2023,10.1109/PowerTech55446.2023.10202770
2,1,3,0.208861,FAULT DIAGNOSIS MODELLING OF POWER SYSTEM CONT...,2025,10.2316/J.2025.201-0437
3,1,4,0.207101,Physics-Informed Neural Networks for AC Optima...,2022,10.1016/j.epsr.2022.108412
4,1,5,0.206897,DeepOPF-AL: Augmented Learning for Solving AC-...,2023,10.1145/3575813.3576874

In [35]:
INTERPRETATION_DIR = (
    OUTPUT_DIR
    / "topic_interpretation"
)

INTERPRETATION_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

for corpus_name, representative_df in (
    representative_documents.items()
):

    output_file = (
        INTERPRETATION_DIR
        / f"{corpus_name}_representative_documents.csv"
    )

    representative_df.to_csv(
        output_file,
        index=False,
        encoding="utf-8",
    )

    print(
        f"{corpus_name.upper():8s}: "
        f"{output_file}"
    )

OVERTON : /nfs/mfirdausi/project/review_paper_2/output/topic_interpretation/overton_representative_documents.csv
SCOPUS  : /nfs/mfirdausi/project/review_paper_2/output/topic_interpretation/scopus_representative_documents.csv

#### 7.1.5 Topic Labeling

In [36]:
topic_interpretation_tables = {}

for corpus_name in [
    "overton",
    "scopus",
]:

    # ---------------------------------------------------------
    # Top terms
    # ---------------------------------------------------------

    terms = (
        final_topic_terms[
            corpus_name
        ]
        .copy()
    )

    # ---------------------------------------------------------
    # Representative documents
    # ---------------------------------------------------------

    reps = (
        representative_documents[
            corpus_name
        ]
        .copy()
    )

    representative_titles = (
        reps
        .sort_values(
            [
                "Topic",
                "Representative_Rank",
            ]
        )
        .groupby(
            "Topic"
        )["Title"]
        .apply(
            lambda titles:
            " | ".join(
                titles
                .fillna("")
                .astype(str)
            )
        )
        .reset_index(
            name="Representative_Titles"
        )
    )

    # ---------------------------------------------------------
    # Combine interpretation evidence
    # ---------------------------------------------------------

    interpretation = (
        terms
        .merge(
            representative_titles,
            on="Topic",
            how="left",
            validate="one_to_one",
        )
        .sort_values(
            "Topic"
        )
        .reset_index(drop=True)
    )

    # Labels will be assigned after interpretation.
    interpretation[
        "Topic_Label"
    ] = ""

    topic_interpretation_tables[
        corpus_name
    ] = interpretation

    print()
    print(corpus_name.upper())
    print("=" * len(corpus_name))

    display(
        interpretation
    )

OVERTON
=======

,Topic,Top_Terms,Representative_Titles,Topic_Label
0,1,"oper, system, flexibl, plan, integr, consid, c...",Understanding barriers to utilising flexibilit...,
1,2,"test, condit, result, use, wave, perform, expe...",PREDICTION OF HEAVE AND PITCH LOW FREQUENCY WA...,
2,3,"effect, factor, rate, increas, depend, also, m...",Digitalization as a trigger for a rebound effe...,
3,4,"design, effici, perform, can, improv, hybrid, ...",Design considerations of a transverse flux mac...,
4,5,"applic, develop, paper, standard, includ, new,...",OpenDSS and OpenDSS-PM open source libraries f...,
5,6,"term, main, author, relat, concept, take, one,...",Techniques to Locate the Origin of Power Quali...,
6,7,"approach, framework, can, present, process, st...",SNARKs for C: Verifying program executions suc...,
7,8,"polici, electr, countri, sector, industri, sup...",Political autonomy and resistance in electrici...,
8,9,"develop, project, engin, research, nation, rig...",Managing the NIH Bethesda Campus Capital Asset...,
9,10,"generat, reserv, unit, variabl, penetr, dispat...",An a priori analytical method for the determin...,
10,11,"grid, smart, communic, secur, network, attack,...",Smart grid - The new and improved power grid: ...,
11,12,"electr, vehicl, charg, transport, drive, stati...",Energy efficiency trade-offs in small to large...,
12,13,"provid, util, servic, regul, can, also, need, ...",Offering of Variable Resources in Regulation M...,
13,14,"differ, studi, result, type, consid, compar, c...",Short circuit current contribution for differe...,
14,15,"chang, climat, water, global, region, scenario...",A scenario-specific nexus modelling toolkit to...,
15,16,"challeng, integr, issu, address, solut, techni...",Multi-terminal VSC HVDC for the European super...,
16,17,"model, simul, dynam, interact, comput, valid, ...",Agent-based simulation of electricity markets:...,
17,18,"impact, studi, analysi, assess, perform, evalu...",Ecodesign perspectives of thin-film photovolta...,
18,19,"find, adopt, household, benefit, level, sugges...",Characterizing local rooftop solar adoption in...,
19,20,"distribut, microgrid, control, der, manag, ope...",Algorithms for distributed decision-making for...,
20,21,"system, paper, reliabl, ieee, provid, present,...",Reliability and availability modelling of comb...,
21,22,"problem, optim, solut, propos, algorithm, comp...",A Laplacian-Based Approach for Finding Near Gl...,
22,23,"time, variabl, year, hour, period, averag, hig...",Long-term spatial and temporal solar resource ...,
23,24,"storag, batteri, energi, generat, use, capac, ...",Research on Power Coordination Control Strateg...,
24,25,"estim, state, measur, observ, robust, use, iee...",A robust extended Kalman filter for power syst...,
25,26,"distribut, network, fault, ieee, voltag, feede...",Optimal distribution network reconfiguration w...,
26,27,"load, meter, smart, consumpt, custom, cluster,...",Fuzzy based clustering of smart meter data usi...,
27,28,"technolog, develop, industri, deploy, role, ne...",The Role of Renewable Energy Sources and Indus...,
28,29,"demand, energi, build, heat, manag, electr, re...",Reduction of heat pump induced peak electricit...,
29,30,"research, review, discuss, literatur, recent, ...",A systematic review on DC-microgrid protection...,
30,31,"market, electr, price, particip, mechan, trade...",Competitive electricity markets with consumer ...,
31,32,"frequenc, system, stabil, respons, dynam, gene...",Stability Evaluation of AC/DC Hybrid Microgrid...,
32,33,"wind, turbin, farm, wake, speed, offshor, blad...",Changing the rotational direction of a wind tu...,
33,34,"forecast, predict, model, uncertainti, error, ...",Ensemble solar forecasting using data-driven m...,
34,35,"solar, irradi, radiat, measur, use, cloud, sur...",A new database of global and direct solar radi...,
35,36,"method, propos, base, use, techniqu, appli, ap...",Efficient SPF approach based on regression and...,
36,37,"energi, transit, communiti, develop, local, st...",Multi-level functional analysis of developing ...,
37,38,"materi, hydrogen, cell, process, product, high...",Enhanced Catalyst Durability for Bio-Based Adi...,
38,39,"transmiss, line, current, use, transform, high...",Transmission line ampacity improvements of alt...,
39,40,"control, propos, strategi, scheme, can, simul,...",Hybrid power management for DC microgrid clust...,
40,41,"emiss, gas, fuel, carbon, reduc, environment, ...",A spatial and fleet disaggregated approach to ...,
41,42,"energi, renew, sourc, resourc, increas, share,...",Renewable energy from the ocean | Tidal energy...,
42,43,"cost, reduc, valu, benefit, reduct, econom, re...",Experience Curves for Operations and Maintenan...,
43,44,"time, algorithm, use, perform, base, approach,...",Fault diagnosis of photovoltaic panels using f...,
44,45,"voltag, convert, invert, current, ieee, presen...",Soft switching bidirectional converter for ref...,
45,46,"will, need, futur, new, increas, requir, year,...",Exploring Consumer Acceptance and Engagement w...,
46,47,"event, resili, failur, risk, reliabl, sever, e...",Cascading failures in complex infrastructure s...,
47,48,"solar, plant, photovolta, instal, modul, loss,...",Fundamentals of soiling processes on photovolt...,
48,49,"can, first, two, use, larg, second, allow, one...",Optimization of Matching Layers to Extend the ...,
49,50,"data, use, detect, inform, avail, set, center,...",Variability extraction and synthesis via multi...,

SCOPUS
======

,Topic,Top_Terms,Representative_Titles,Topic_Label
0,1,"network, neural, train, use, predict, deep, ar...",Physics-informed machine learning with optimiz...,
1,2,"voltag, loss, reactiv, activ, bus, ieee, regul...",Resource management with kernel-based approach...,
2,3,"estim, state, measur, paramet, method, use, ac...",Robust Matrix Completion State Estimation in D...,
3,4,"market, energi, price, electr, trade, mechan, ...",Peer-to-Peer Energy Trading Enabled Optimal De...,
4,5,"can, will, due, issu, one, also, howev, may, m...",A survey on power system blackout and cascadin...,
5,6,"model, develop, propos, simul, linear, datadri...",Data-Driven-Aided Linear Three-Phase Power Flo...,
6,7,"microgrid, oper, manag, system, generat, mode,...",Networked Microgrids Framework | Optimal gener...,
7,8,"system, reserv, ltd, engin, right, publish, te...",A distributed data-driven modelling framework ...,
8,9,"technolog, energi, intellig, sustain, artifici...",Digital technologies for a net-zero energy fut...,
9,10,"techniqu, use, differ, perform, various, sugge...",Optimized FACTS Devices for Power System Enhan...,
10,11,"oper, flexibl, coordin, system, level, provid,...","Tracing, Ranking and Valuation of Aggregated d...",
11,12,"framework, across, limit, practic, deploy, int...",STORM-OPF: Robustness Benchmarking for AC-OPF ...,
12,13,"system, optim, devic, locat, use, size, improv...",Optimal placement of multiple-type FACTS devic...,
13,14,"first, base, second, final, propos, stage, cha...",Research on a data-driven evaluation model for...,
14,15,"solar, photovolta, generat, capac, studi, plan...",Power Factor Analysis of Grid-Connected Solar ...,
15,16,"forecast, predict, model, error, accuraci, mea...",Electricity consumption forecasting using a no...,
16,17,"grid, smart, provid, develop, challeng, increa...",Smart Grids and Smart Buildings | Smart Grids ...,
17,18,"algorithm, function, optim, object, problem, m...",Multi-Objective Optimal Power Flow Solutions U...,
18,19,"energi, emiss, build, carbon, thermal, heat, g...",International Comparison of Weather and Emissi...,
19,20,"cost, reduc, optim, minim, reduct, achiev, tot...",Reducing Total Fuel Cost and Loss Cost for the...,
20,21,"distribut, direct, algorithm, altern, central,...",Impact of communication delay on asynchronous ...,
21,22,"load, demand, electr, respons, peak, consumpt,...",Intelligent Demand Side Management for Exhaust...,
22,23,"comput, effici, time, complex, requir, solut, ...",Limitations of Fault-Tolerant Quantum Linear S...,
23,24,"use, result, present, case, time, two, test, o...",Statistical analysis of power flows based on s...,
24,25,"uncertainti, robust, scenario, stochast, propo...",Bayesian Nonparametric Two-Stage Distributiona...,
25,26,"system, attack, secur, detect, data, communic,...",An Extended False Data Injection Attack via De...,
26,27,"electr, charg, vehicl, station, transport, str...",Intelligent Charging Navigation for Electric V...,
27,28,"dispatch, schedul, oper, unit, generat, econom...",A review of recent advances in dynamic economi...,
28,29,"topolog, graph, physic, featur, structur, atte...",IMPROVING GRAPH NEURAL NETWORKS BY LEARNING CO...,
29,30,"reinforc, deep, agent, polici, decis, realtim,...",Safe Reinforcement Learning for Energy Managem...,
30,31,"distribut, network, der, resourc, node, activ,...",Quantifying the Impact of Day-ahead Renewable ...,
31,32,"problem, solut, solv, opf, optim, constraint, ...",A non-convex alternating direction method of m...,
32,33,"system, stabil, transient, dynam, analysi, ass...",Design of firefly power system stabilizer for ...,
33,34,"system, plan, natur, author, oper, part, prese...",Challenges in ensuring reliability of renewabl...,
34,35,"convert, current, qualiti, harmon, voltag, hig...",Analysis and Design of a Cyclo-Active-Bridge I...,
35,36,"system, bus, ieee, transmiss, line, secur, tes...",An analysis of the security of multi-area powe...,
36,37,"energi, renew, sourc, integr, manag, system, r...",Advances in Modeling and Optimization of Intel...,
37,38,"energi, storag, system, batteri, hybrid, manag...",Optimal design and control of battery-ultracap...,
38,39,"enhanc, effici, challeng, address, signific, i...",Data-Driven Adequacy and Security Assessment: ...,
39,40,"reliabl, system, resili, assess, failur, risk,...",Cost-effective retrofits of power grids based ...,
40,41,"fault, protect, detect, classif, current, sche...",Component identification and defect detection ...,
41,42,"algorithm, problem, search, converg, optim, te...",An enhanced arithmetic optimization algorithm ...,
42,43,"applic, design, system, research, develop, pro...",Modern Power System Analysis | Sustainable Man...,
43,44,"method, propos, base, calcul, paper, can, effe...",Calculating theoretical line losses based on i...,
44,45,"adapt, dynam, condit, effici, improv, perform,...",MPP detection of a partially shaded PV array b...,
45,46,"control, frequenc, strategi, regul, scheme, sy...",Comparative Assessment of PSO-Tuned Hybrid Fuz...,
46,47,"wind, generat, output, use, speed, result, var...",Modeling and Analysis of Short-term Output Pre...,
47,48,"propos, approach, result, novel, compar, simul...",Stochastic voltage estimation for islanded DC ...,
48,49,"data, cluster, use, process, analysi, inform, ...",Big data clustering algorithm of power system ...,
49,50,"research, review, applic, futur, provid, discu...",The Rise of Particle Swarm Optimization: A Sys...,

In [37]:
def show_topic(
    corpus_name,
    topic_number,
):

    terms = (
        topic_interpretation_tables[
            corpus_name
        ]
        .query(
            "Topic == @topic_number"
        )
        .iloc[0]
    )

    reps = (
        representative_documents[
            corpus_name
        ]
        .query(
            "Topic == @topic_number"
        )
        .sort_values(
            "Representative_Rank"
        )
    )

    print(
        f"{corpus_name.upper()} — "
        f"Topic {topic_number}"
    )

    print("=" * 70)

    print("\nTop terms:")
    print(
        terms["Top_Terms"]
    )

    print(
        "\nRepresentative publications:"
    )

    for _, row in reps.iterrows():

        print(
            f"\n{int(row['Representative_Rank'])}. "
            f"{row['Title']}"
        )

        print(
            f"   Topic probability: "
            f"{row['Topic_Probability']:.4f}"
        )

In [38]:
show_topic(
    "overton",
    1,
)

OVERTON — Topic 1
======================================================================

Top terms:
oper, system, flexibl, plan, integr, consid, case, decis, level, requir

Representative publications:

1. Understanding barriers to utilising flexibility in operation and planning of the electricity distribution system – Classification frameworks with applications to Norway
   Topic probability: 0.2424

2. Flexible distributed multienergy generation system expansion planning under uncertainty
   Topic probability: 0.1818

3. Alternatives No More: Wind and Solar Power Are Mainstays of a Clean, Reliable, Affordable Grid
   Topic probability: 0.1675

4. Economic assessment of integrating fast-charging stations and energy communities in grid planning
   Topic probability: 0.1613

5. Capacity Market Model Considering Flexible Resource Requirements
   Topic probability: 0.1576

In [39]:
show_topic(
    "scopus",
    1,
)

SCOPUS — Topic 1
======================================================================

Top terms:
network, neural, train, use, predict, deep, artifici, accuraci, ann, approach

Representative publications:

1. Physics-informed machine learning with optimization-based guarantees: Applications to AC power flow
   Topic probability: 0.2340

2. Enriching Neural Network Training Dataset to Improve Worst-Case Performance Guarantees
   Topic probability: 0.2097

3. FAULT DIAGNOSIS MODELLING OF POWER SYSTEM CONTROLLER BASED ON PLC TECHNOLOGY
   Topic probability: 0.2089

4. Physics-Informed Neural Networks for AC Optimal Power Flow
   Topic probability: 0.2071

5. DeepOPF-AL: Augmented Learning for Solving AC-OPF Problems with a Multi-Valued Load-Solution Mapping
   Topic probability: 0.2069

In [40]:
INTERPRETATION_DIR = (
    OUTPUT_DIR
    / "topic_interpretation"
)

for corpus_name, table in (
    topic_interpretation_tables.items()
):

    output_file = (
        INTERPRETATION_DIR
        / f"{corpus_name}_topic_interpretation.csv"
    )

    table.to_csv(
        output_file,
        index=False,
        encoding="utf-8",
    )

    print(
        f"{corpus_name.upper():8s}: "
        f"{output_file}"
    )

OVERTON : /nfs/mfirdausi/project/review_paper_2/output/topic_interpretation/overton_topic_interpretation.csv
SCOPUS  : /nfs/mfirdausi/project/review_paper_2/output/topic_interpretation/scopus_topic_interpretation.csv

In [42]:
def show_topic_range(
    corpus_name,
    start_topic,
    end_topic,
):

    for topic_number in range(
        start_topic,
        end_topic + 1,
    ):

        show_topic(
            corpus_name,
            topic_number,
        )

        print("\n")

In [43]:
show_topic_range(
    "overton",
    2,
    10,
)

OVERTON — Topic 2
======================================================================

Top terms:
test, condit, result, use, wave, perform, experi, present, evalu, simul

Representative publications:

1. PREDICTION OF HEAVE AND PITCH LOW FREQUENCY WAVE FORCES AND MOTIONS OF A SEMI-SUBMERSIBLE FLOATING WIND TURBINE AND COMPARISON WITH MODEL TEST DATA
   Topic probability: 0.3665

2. MARINET experiment KNSWING testing an I-Beam OWC attenuator
   Topic probability: 0.3385

3. Real-time hybrid model testing of a braceless semi-submersible wind turbine. Part II: Experimental results
   Topic probability: 0.3082

4. Optimization-based calibration of hydrodynamic drag coefficients for a semisubmersible platform using experimental data of an irregular sea state
   Topic probability: 0.3041

5. Uncertainty assessment of CFD investigation of the nonlinear difference-frequency wave loads on a semisubmersible FOWT platform
   Topic probability: 0.2905


OVERTON — Topic 3
======================================================================

Top terms:
effect, factor, rate, increas, depend, also, may, signific, influenc, result

Representative publications:

1. Digitalization as a trigger for a rebound effect of electricity use
   Topic probability: 0.1961

2. The energy rebound effect of digital development: Evidence from 285 cities in China
   Topic probability: 0.1951

3. Annoyance of residents induced by wind turbine obstruction lights: A cross-country comparison of impact factors
   Topic probability: 0.1871

4. Long-term wind speed trends over Australia
   Topic probability: 0.1845

5. An investigation into the potential for wind turbines to cause barotrauma in bats
   Topic probability: 0.1754


OVERTON — Topic 4
======================================================================

Top terms:
design, effici, perform, can, improv, hybrid, high, compon, result, achiev

Representative publications:

1. Design considerations of a transverse flux machine for direct-drive wind turbine applications
   Topic probability: 0.2574

2. MADE3D: Enabling the next generation of high-torque density wind generators by additive design and 3D printing; [MADE3D: Ermöglichung der nächsten Generation von Windgeneratoren mit hoher Drehmomentdichte durch additives Design und 3D‑Druck]
   Topic probability: 0.2000

3. Wind Generator Impedance Matching in Small-Scale Passive Wind Energy Systems
   Topic probability: 0.1921

4. A new shape optimization approach for lightweighting electric machines inspired by additive manufacturing
   Topic probability: 0.1902

5. Additive manufacturing: A new paradigm for the next generation of high-power-density direct-drive electric generators
   Topic probability: 0.1675


OVERTON — Topic 5
======================================================================

Top terms:
applic, develop, paper, standard, includ, new, implement, use, function, describ

Representative publications:

1. OpenDSS and OpenDSS-PM open source libraries for NI LabVIEW
   Topic probability: 0.2953

2. Overview of IEC 61850 and benefits
   Topic probability: 0.2857

3. iTesla Power Systems Library (iPSL): A Modelica library for phasor time-domain simulations
   Topic probability: 0.2500

4. Distributed power system automation with IEC 61850, IEC 61499, and intelligent control
   Topic probability: 0.2243

5. Future-oriented generic grid code regarding wind power plants in Europe
   Topic probability: 0.2159


OVERTON — Topic 6
======================================================================

Top terms:
term, main, author, relat, concept, take, one, possibl, well, common

Representative publications:

1. Techniques to Locate the Origin of Power Quality Disturbances in a Power System: A Review
   Topic probability: 0.1594

2. Characterizing positive energy district (Ped) through a preliminary review of 60 existing projects in europe
   Topic probability: 0.1570

3. Positive energy districts: Mainstreaming energy transition in urban areas
   Topic probability: 0.1568

4. A study of wind turbine performance decline with age through operation data analysis
   Topic probability: 0.1525

5. Distributed generation: Definition, benefits and issues
   Topic probability: 0.1504


OVERTON — Topic 7
======================================================================

Top terms:
approach, framework, can, present, process, structur, demonstr, activ, work, practic

Representative publications:

1. SNARKs for C: Verifying program executions succinctly and in zero knowledge
   Topic probability: 0.2464

2. Foundational property-based testing
   Topic probability: 0.2014

3. Symbolic state-space exploration and numerical analysis of state-sharing composed models
   Topic probability: 0.1963

4. Invertible Neural Networks for Airfoil Design
   Topic probability: 0.1698

5. Can Large Language Models Be Trusted as Evolutionary Optimizers for Network-Structured Combinatorial Problems?
   Topic probability: 0.1636


OVERTON — Topic 8
======================================================================

Top terms:
polici, electr, countri, sector, industri, suppli, invest, european, develop, govern

Representative publications:

1. Political autonomy and resistance in electricity sector liberalization in Africa
   Topic probability: 0.3767

2. Contentious implementation and retrenchment in neoliberal policy reform: The global electric power industry, 1989-2001
   Topic probability: 0.3642

3. Electricity sector reform in Cameroon: Is privatization the solution?
   Topic probability: 0.3439

4. Policy Reform and the Problem of Private Investment: Evidence from the Power Sector
   Topic probability: 0.2993

5. Interactions between renewable energy policy and renewable energy industrial policy: A critical analysis of china's policy approach to renewable energies
   Topic probability: 0.2948


OVERTON — Topic 9
======================================================================

Top terms:
develop, project, engin, research, nation, right, institut, facil, initi, scienc

Representative publications:

1. Managing the NIH Bethesda Campus Capital Assets for Success in a Highly Competitive Global Biomedical Research Environment
   Topic probability: 0.3927

2. Final Report of the Committee on a Strategic Plan for U.S. BURNING PLASMA RESEARCH
   Topic probability: 0.3924

3. The fusion nuclear science facility, the critical step in the pathway to fusion energy
   Topic probability: 0.3271

4. AN ASSESSMENT OF THE PROSPECTS FOR: INERTIAL FUSION ENERGY
   Topic probability: 0.3208

5. Nuclear power in the 21st century: Challenges and possibilities
   Topic probability: 0.2847


OVERTON — Topic 10
======================================================================

Top terms:
generat, reserv, unit, variabl, penetr, dispatch, balanc, increas, oper, requir

Representative publications:

1. An a priori analytical method for the determination of operating reserve requirements
   Topic probability: 0.2548

2. Impacts of wind power forecast errors on the real-time balancing need: A Nordic case study
   Topic probability: 0.2547

3. Impacts of industrial baseline errors in demand side management enabled enterprise control
   Topic probability: 0.2315

4. Flexibility Reserve in Power Systems: Definition and Stochastic Multi-Fidelity Optimization
   Topic probability: 0.2284

5. Stochastic Multi-Timescale Power System Operations with Variable Wind Generation
   Topic probability: 0.2235

In [44]:
show_topic_range(
    "scopus",
    2,
    10,
)

SCOPUS — Topic 2
======================================================================

Top terms:
voltag, loss, reactiv, activ, bus, ieee, regul, deviat, load, profil

Representative publications:

1. Resource management with kernel-based approaches for grid-connected solar photovoltaic systems
   Topic probability: 0.2583

2. Minimization of L-index using genetic algorithm for improvement of voltage profile in power systems
   Topic probability: 0.2460

3. A Zonal Volt/VAR Control Mechanism for High PV Penetration Distribution Systems
   Topic probability: 0.2273

4. A multi-objective volt-var control strategy for distribution networks with high PV penetration
   Topic probability: 0.2229

5. Long-Term Voltage Stability Bifurcation Analysis and Control Considering OLTC Adjustment and Photovoltaic Power Station
   Topic probability: 0.2199


SCOPUS — Topic 3
======================================================================

Top terms:
estim, state, measur, paramet, method, use, accur, identif, accuraci, condit

Representative publications:

1. Robust Matrix Completion State Estimation in Distribution Systems
   Topic probability: 0.3812

2. An Optimal Framework for Trade-off between Strategic Placement of PMUs and Enhanced State Estimation Accuracy
   Topic probability: 0.3190

3. Replicating Power Flow Constraints Using only Smart Meter Data for Coordinating Flexible Sources in Distribution Network
   Topic probability: 0.2825

4. Complex-Variable Weighted Least Modulus State Estimation
   Topic probability: 0.2680

5. Widely-Linear MMSE Estimation of Complex-Valued Graph Signals
   Topic probability: 0.2531


SCOPUS — Topic 4
======================================================================

Top terms:
market, energi, price, electr, trade, mechan, particip, prosum, communiti, aggreg

Representative publications:

1. Peer-to-Peer Energy Trading Enabled Optimal Decentralized Operation of Smart Distribution Grids
   Topic probability: 0.3030

2. Pricing mechanisms for peer-to-peer energy trading: Towards an integrated understanding of energy and network service pricing mechanisms
   Topic probability: 0.3017

3. An agent mechanism for sharing users’ integrated energy considering contribution rate
   Topic probability: 0.2989

4. An Energy Sharing Mechanism Considering Network Constraints and Market Power Limitation
   Topic probability: 0.2970

5. A model-based comparative study of peer-to-peer market designs
   Topic probability: 0.2969


SCOPUS — Topic 5
======================================================================

Top terms:
can, will, due, issu, one, also, howev, may, mani, chang

Representative publications:

1. A survey on power system blackout and cascading events: Research motivations and challenges
   Topic probability: 0.2169

2. Assessing Protection Systems for Solar PV Penetration Across Different Locations to Enhance Grid Stability and Reliability
   Topic probability: 0.2020

3. The IoT Solution for Reliable Transformer Condition Monitoring and Maintenance
   Topic probability: 0.1982

4. Energy transition technology comes with new process safety challenges and risks
   Topic probability: 0.1727

5. Successive zooming optimization and its application to voltage stability problem
   Topic probability: 0.1520


SCOPUS — Topic 6
======================================================================

Top terms:
model, develop, propos, simul, linear, datadriven, establish, dynam, paramet, studi

Representative publications:

1. Data-Driven-Aided Linear Three-Phase Power Flow Model for Distribution Power Systems
   Topic probability: 0.2407

2. Gray-Box Modeling for Distribution Systems With Inverter-Based Resources: Integrating Physics-Based and Data-Driven Approaches
   Topic probability: 0.2095

3. Extended matrix modeling of integrated energy systems considering network dynamic characteristics and source–load uncertainty
   Topic probability: 0.1885

4. Modular Linear Power Flow Model Against Large Fluctuations
   Topic probability: 0.1829

5. Accurate and Efficient Linear Surrogate Models for Conversion Losses in Hybrid AC/DC Microgrids based on Hard Constrained Neural Networks
   Topic probability: 0.1813


SCOPUS — Topic 7
======================================================================

Top terms:
microgrid, oper, manag, system, generat, mode, strategi, island, mgs, util

Representative publications:

1. Networked Microgrids Framework
   Topic probability: 0.3054

2. Optimal generation and distribution planning in smart microgrids under conditions of multi-microgrid disconnection using a hierarchical control strategy
   Topic probability: 0.2152

3. Advancements in DC Microgrids: Integrating Machine Learning and Communication Technologies for a Decentralized Future
   Topic probability: 0.2028

4. Artificial Intelligence Applications for Energy Management in Microgrid
   Topic probability: 0.1986

5. Intelligent fault detection architecture for ring-connected AC microgrid clusters
   Topic probability: 0.1967


SCOPUS — Topic 8
======================================================================

Top terms:
system, reserv, ltd, engin, right, publish, technolog, elsevi, studi, institut

Representative publications:

1. A distributed data-driven modelling framework for power flow estimation in power distribution systems
   Topic probability: 0.1667

2. Performance enhancement of grid-connected photovoltaic systems using Ant Lion optimisation and Genetic Algorithm-based optimisation techniques
   Topic probability: 0.1592

3. A reference architecture for the American Multi-Modal Energy System enterprise
   Topic probability: 0.1494

4. Enhancing Resilience in Power Distribution Systems
   Topic probability: 0.1488

5. Power System Harmonics and Passive Filter Designs
   Topic probability: 0.1485


SCOPUS — Topic 9
======================================================================

Top terms:
technolog, energi, intellig, sustain, artifici, advanc, digit, manag, integr, challeng

Representative publications:

1. Digital technologies for a net-zero energy future: A comprehensive review
   Topic probability: 0.3901

2. Energy Management and Smart Grid Communication
   Topic probability: 0.3750

3. Clean and Smart Energy Technologies for Agricultural Energy Internet Systems: A Comprehensive Review and Future Perspectives
   Topic probability: 0.3598

4. Digital Platforms for the Built Environment: A Systematic Review Across Sectors and Scales
   Topic probability: 0.3333

5. Comprehensive review of artificial intelligence applications in renewable energy systems: current implementations and emerging trends
   Topic probability: 0.3288


SCOPUS — Topic 10
======================================================================

Top terms:
techniqu, use, differ, perform, various, suggest, studi, also, work, term

Representative publications:

1. Optimized FACTS Devices for Power System Enhancement: Applications and Solving Methods
   Topic probability: 0.1762

2. An Enhanced Slime Mould Optimizer That Uses Chaotic Behavior and an Elitist Group for Solving Engineering Problems
   Topic probability: 0.1711

3. A modified PSO technique for the coordination problem in presence of DG
   Topic probability: 0.1551

4. Energy management system of microgrids in grid-tied mode: A hybrid approach
   Topic probability: 0.1523

5. Review and Comparison of Genetic Algorithm and Particle Swarm Optimization in the Optimal Power Flow Problem
   Topic probability: 0.1519

In [46]:
show_topic_range(
    "overton",
    11,
    20,
)

OVERTON — Topic 11
======================================================================

Top terms:
grid, smart, communic, secur, network, attack, infrastructur, ieee, inform, manag

Representative publications:

1. Smart grid - The new and improved power grid: A survey
   Topic probability: 0.2941

2. An analysis of smart grid attacks and countermeasures
   Topic probability: 0.2689

3. Current and Future Communication Solutions for Smart Grids: A Review
   Topic probability: 0.2577

4. Heterogeneous communication architecture for the smart grid
   Topic probability: 0.2516

5. A survey on smart power grid: frameworks, tools, security issues, and solutions
   Topic probability: 0.2361


OVERTON — Topic 12
======================================================================

Top terms:
electr, vehicl, charg, transport, drive, station, pev, batteri, infrastructur, plugin

Representative publications:

1. Energy efficiency trade-offs in small to large electric vehicles
   Topic probability: 0.3135

2. Traffic impacts on energy consumption of electric and conventional vehicles
   Topic probability: 0.3066

3. Quantifying the change of brake wear particulate matter emissions through powertrain electrification in passenger vehicles
   Topic probability: 0.2872

4. The hidden cost of road maintenance due to the increased weight of battery and hydrogen trucks and buses—a perspective
   Topic probability: 0.2850

5. Charging Infrastructure for Commercial Electric Vehicles: Challenges and Future Works
   Topic probability: 0.2795


OVERTON — Topic 13
======================================================================

Top terms:
provid, util, servic, regul, can, also, need, resourc, qualiti, paper

Representative publications:

1. Offering of Variable Resources in Regulation Markets With Performance Targets: An Analysis
   Topic probability: 0.2568

2. How demand response from commercial buildings will provide the regulation needs of the grid
   Topic probability: 0.1921

3. Performance Analysis of a 10 MW Wind Farm in Providing Secondary Frequency Regulation: Experimental Aspects
   Topic probability: 0.1868

4. Providing Ancillary Services with Photovoltaic Generation in Multi-Timescale Grid Operation
   Topic probability: 0.1799

5. HPC Data Center Participation in Demand Response: An Adaptive Policy with QoS Assurance
   Topic probability: 0.1688


OVERTON — Topic 14
======================================================================

Top terms:
differ, studi, result, type, consid, compar, case, base, three, two

Representative publications:

1. Short circuit current contribution for different wind turbine generator types
   Topic probability: 0.1234

2. Understanding the energy yield of photovoltaic modules in different climates by linear performance loss analysis of the module performance ratio
   Topic probability: 0.1228

3. Reviewing optimisation criteria for energy systems analyses of renewable energy integration
   Topic probability: 0.1159

4. Load representation for dynamic performance analysis ieee task force on load representation for dynamic performance
   Topic probability: 0.1136

5. Fulfillment of net-zero energy building (NZEB) with four metrics in a single family house with different heating alternatives
   Topic probability: 0.1132


OVERTON — Topic 15
======================================================================

Top terms:
chang, climat, water, global, region, scenario, potenti, resourc, impact, increas

Representative publications:

1. A scenario-specific nexus modelling toolkit to identify trade-offs in the promotion of sustainable irrigated agriculture in Ecuador, a Belt and Road country
   Topic probability: 0.4130

2. A global water scarcity assessment under Shared Socio-economic Pathways - Part 2: Water availability and scarcity
   Topic probability: 0.3692

3. Climate change impacts on renewable energy supply
   Topic probability: 0.3427

4. Integrated modelling of the impacts of hydropower projects on the water-food-energy nexus in a transboundary Himalayan river basin
   Topic probability: 0.3058

5. Economic impacts of climate change on water resources in the coterminous United States
   Topic probability: 0.3048


OVERTON — Topic 16
======================================================================

Top terms:
challeng, integr, issu, address, solut, technic, howev, need, requir, potenti

Representative publications:

1. Multi-terminal VSC HVDC for the European supergrid: Obstacles
   Topic probability: 0.1971

2. Microgrids: Experiences, barriers and success factors
   Topic probability: 0.1942

3. The challenges of achieving a 100% renewable electricity system in the United States
   Topic probability: 0.1667

4. DC Microgrids: Benefits, Architectures, Perspectives and Challenges
   Topic probability: 0.1584

5. Challenges and solution technologies for the integration of variable renewable energy sources—a review
   Topic probability: 0.1512


OVERTON — Topic 17
======================================================================

Top terms:
model, simul, dynam, interact, comput, valid, physic, studi, develop, repres

Representative publications:

1. Agent-based simulation of electricity markets: A survey of tools
   Topic probability: 0.2126

2. Coupling visualization, simulation, and deep learning for ensemble steering of complex energy models
   Topic probability: 0.2085

3. Hybrid RANS-LES of the Atmospheric Boundary Layer for Wind Farm Simulations
   Topic probability: 0.2025

4. Dynamic Co-Simulation Methods for Combined Transmission-Distribution System with Integration Time Step Impact on Convergence
   Topic probability: 0.1775

5. Towards a theory of voltage collapse in electric power systems
   Topic probability: 0.1765


OVERTON — Topic 18
======================================================================

Top terms:
impact, studi, analysi, assess, perform, evalu, result, use, potenti, methodolog

Representative publications:

1. Ecodesign perspectives of thin-film photovoltaic technologies: A review of life cycle assessment studies
   Topic probability: 0.1829

2. Environmental life cycle assessment of emerging solid-state batteries: A review
   Topic probability: 0.1745

3. Flow battery production: Materials selection and environmental impact
   Topic probability: 0.1684

4. Life cycle assessment of microalgae-derived biodiesel
   Topic probability: 0.1618

5. Life cycle assessment of concentrated solar power (CSP) and the influence of hybridising with natural gas
   Topic probability: 0.1530


OVERTON — Topic 19
======================================================================

Top terms:
find, adopt, household, benefit, level, suggest, access, group, public, inform

Representative publications:

1. Characterizing local rooftop solar adoption inequity in the US
   Topic probability: 0.3265

2. Diffusion into new markets: Evolving customer segments in the solar photovoltaics market
   Topic probability: 0.3218

3. The impact of policies and business models on income equity in rooftop solar adoption
   Topic probability: 0.3182

4. Willingness to share information for energy efficiency: exploring differences and drivers across the Nordic countries
   Topic probability: 0.3164

5. Socioeconomic and demographic disparities in residential battery storage adoption: Evidence from California
   Topic probability: 0.3148


OVERTON — Topic 20
======================================================================

Top terms:
distribut, microgrid, control, der, manag, oper, coordin, system, local, central

Representative publications:

1. Algorithms for distributed decision-making for multi-agent microgrid power management
   Topic probability: 0.3684

2. Multi-Agent System (MAS) for short-term generation scheduling of a microgrid
   Topic probability: 0.3614

3. Agent-based power management of microgrids including renewable energy power generation
   Topic probability: 0.3439

4. Evaluation of Data-Enhanced Hierarchical Control for Distribution Feeders With High PV Penetration
   Topic probability: 0.3029

5. Multi-agent system for the operation of an integrated microgrid
   Topic probability: 0.3023

In [47]:
show_topic_range(
    "scopus",
    11,
    20,
)

SCOPUS — Topic 11
======================================================================

Top terms:
oper, flexibl, coordin, system, level, provid, framework, resourc, can, increas

Representative publications:

1. Tracing, Ranking and Valuation of Aggregated der Flexibility in Active Distribution Networks
   Topic probability: 0.2340

2. A hierarchical scheduling framework for DSO and shiftable load aggregator
   Topic probability: 0.2126

3. TensorConvolutionPlus: A python package for distribution system flexibility area estimation
   Topic probability: 0.2059

4. Tso-dso coordination schemes to facilitate distributed resources integration
   Topic probability: 0.1946

5. Comprehensive review of transmission system operators–Distribution system operators collaboration for flexible grid operations
   Topic probability: 0.1919


SCOPUS — Topic 12
======================================================================

Top terms:
framework, across, limit, practic, deploy, integr, remain, scalabl, evalu, valid

Representative publications:

1. STORM-OPF: Robustness Benchmarking for AC-OPF Methods
   Topic probability: 0.2409

2. From Pareto Front to Preferred Design: Human-in-the-Loop Preference-Guided Decision Making in Multi-Objective Energy Systems Optimization—A Scoping Review
   Topic probability: 0.2299

3. A high-dimensional steady-state structural framework for regional transmission interface capacity planning using physics-embedded graph representation learning
   Topic probability: 0.2232

4. From systematic evidence to agentic architectures: A systematic review and framework for large language model–driven smart grids
   Topic probability: 0.2171

5. An analytical framework for line loss density measurement and criticality assessment in radial distribution systems
   Topic probability: 0.2169


SCOPUS — Topic 13
======================================================================

Top terms:
system, optim, devic, locat, use, size, improv, fact, determin, perform

Representative publications:

1. Optimal placement of multiple-type FACTS devices to maximize power system loadability using a generic graphical user interface
   Topic probability: 0.3855

2. Optimal location of UPFC in power systems for increasing loadability by genetic algorithm
   Topic probability: 0.3730

3. Optimal location of FACTS devices for improving performance of the power systems
   Topic probability: 0.3423

4. Application of evolutionary optimization techniques for optimal location and parameters setting of multiple UPFC devices
   Topic probability: 0.3418

5. Optimal location of multi-type FACTS devices in a power system by means of genetic algorithms
   Topic probability: 0.3361


SCOPUS — Topic 14
======================================================================

Top terms:
first, base, second, final, propos, stage, characterist, construct, effect, establish

Representative publications:

1. Research on a data-driven evaluation model for assessing the capacity of distribution grids to accommodate distributed photovoltaic connections
   Topic probability: 0.2000

2. Research on collaborative optimization of active distribution networks under the background of new power system construction: A review
   Topic probability: 0.1959

3. Research on multifactor coupling mechanism analysis methods for voltage quality in distribution networks
   Topic probability: 0.1844

4. Hierarchical Control Architecture Regulation Device Based on Mixed Integer Programming Algorithm
   Topic probability: 0.1750

5. A new two-step matching method and loss-allocation method based on the profit proportional sharing principle applied in the trans-regional transaction
   Topic probability: 0.1714


SCOPUS — Topic 15
======================================================================

Top terms:
solar, photovolta, generat, capac, studi, plant, use, analysi, product, factor

Representative publications:

1. Power Factor Analysis of Grid-Connected Solar Inverter under Different Irradiance Levels throughout the Day
   Topic probability: 0.2431

2. Assessment of the wind energy potential and economic viability of selected sites along Nigeria’s coastal and offshore locations
   Topic probability: 0.2419

3. Modeling and sensitivity analysis of grid-connected hybrid green microgrid system
   Topic probability: 0.2361

4. Renewable Solar Energy Facilities in South America—The Road to a Low-Carbon Sustainable Energy Matrix: A Systematic Review
   Topic probability: 0.2344

5. A GIS-based fermatean fuzzy MCDM approach for identifying the optimal sites for solar power plant installation in Kermanshah Province
   Topic probability: 0.2252


SCOPUS — Topic 16
======================================================================

Top terms:
forecast, predict, model, error, accuraci, mean, shortterm, accur, perform, regress

Representative publications:

1. Electricity consumption forecasting using a novel homogeneous and heterogeneous ensemble learning
   Topic probability: 0.3789

2. Loss Prediction of Ultrahigh Voltage Transmission Lines Based on EEMD–LSTM–SVR Algorithm
   Topic probability: 0.3279

3. Hybrid TKNN-PCA-LSTM Model for Hourly Solar Irradiance Forecasting
   Topic probability: 0.3269

4. A dynamic ensemble method for residential short-term load forecasting
   Topic probability: 0.3086

5. Combined multi-component composite time series power prediction model for distributed energy systems based on STL data decomposition
   Topic probability: 0.2978


SCOPUS — Topic 17
======================================================================

Top terms:
grid, smart, provid, develop, challeng, increas, advanc, support, enabl, need

Representative publications:

1. Smart Grids and Smart Buildings
   Topic probability: 0.3636

2. Smart Grids and Smart Buildings
   Topic probability: 0.3430

3. Smart Grid Fault Mitigation and Cybersecurity with Wide-Area Measurement Systems: A Review
   Topic probability: 0.2320

4. Control and Optimisation of Power Grids Using Smart Meter Data: A Review
   Topic probability: 0.2169

5. Smart grid concept and technologies for smart cities
   Topic probability: 0.2156


SCOPUS — Topic 18
======================================================================

Top terms:
algorithm, function, optim, object, problem, multiobject, solut, genet, swarm, particl

Representative publications:

1. Multi-Objective Optimal Power Flow Solutions Using Improved Multi-Objective Mayfly Algorithm (IMOMA)
   Topic probability: 0.3382

2. Recurrent multi-objective differential evolution approach for reactive power management
   Topic probability: 0.2876

3. Dynamic economic emission dispatch of combined heat and power system based on multi-objective differential evolution algorithm
   Topic probability: 0.2695

4. Multi objective optimization of microgrid based on Improved Multi-objective Particle Swarm Optimization
   Topic probability: 0.2661

5. An improved mayfly algorithm based optimal power flow solution for regulated electric power network
   Topic probability: 0.2647


SCOPUS — Topic 19
======================================================================

Top terms:
energi, emiss, build, carbon, thermal, heat, gas, consumpt, environment, integr

Representative publications:

1. International Comparison of Weather and Emission Predictive Building Control
   Topic probability: 0.3136

2. The role of carbon capture and storage to achieve net-zero energy systems: Trade-offs between economics and the environment
   Topic probability: 0.3122

3. Heating energy-saving potentials in HVAC system of swimming halls: A review
   Topic probability: 0.2871

4. Reducing Carbon Emissions from Transport Sector: Experience and Policy Design Considerations
   Topic probability: 0.2857

5. Addressing building related energy burden, air pollution, and carbon emissions of a low-income community in Southern California
   Topic probability: 0.2849


SCOPUS — Topic 20
======================================================================

Top terms:
cost, reduc, optim, minim, reduct, achiev, total, loss, result, compar

Representative publications:

1. Reducing Total Fuel Cost and Loss Cost for the IEEE 30-Bus Transmission Power System by Optimizing the Location of Wind Power Plants
   Topic probability: 0.1834

2. Advanced microgrid optimization using price-elastic demand response and greedy rat swarm optimization for economic and environmental efficiency
   Topic probability: 0.1660

3. Machine-learning techniques for enhancing electricity theft detection considering transformer reliability and supply interruptions
   Topic probability: 0.1658

4. An application of teaching–learning-based optimization for solving the optimal power flow problem with stochastic wind and solar power generators
   Topic probability: 0.1655

5. Dynamic multi-period optimal power flow considering renewable energy degradation and temperature derating
   Topic probability: 0.1636

In [48]:
overton_topic_labels = {
    1: "Power-System Flexibility and Grid Planning",
    2: "Offshore Wind and Marine Energy Modeling",
    3: "Energy and Environmental Impact Factors",
    4: "Electric Machine and Wind Generator Design",
    5: "Power-System Modeling Standards and Software Tools",
    6: "Energy-System Concepts and Technology Assessment",
    7: "Computational Frameworks and Algorithmic Methods",
    8: "Electricity-Sector Policy and Market Reform",
    9: "Energy Research Infrastructure and Nuclear/Fusion Technology",
    10: "Operating Reserves and Renewable Balancing",
}

scopus_topic_labels = {
    1: "Neural Networks and Physics-Informed Learning",
    2: "Voltage and Reactive Power Control",
    3: "Power-System State Estimation",
    4: "Electricity Markets and Peer-to-Peer Energy Trading",
    5: "Grid Reliability, Risk, and Stability Challenges",
    6: "Data-Driven and Linear Power-Flow Modeling",
    7: "Microgrid Operation and Energy Management",
    8: "Power-System Engineering Applications",
    9: "Digitalization and Intelligent Energy Systems",
    10: "Metaheuristic Optimization Methods",
}

overton_topic_labels.update({
    11: "Smart-Grid Communications and Cybersecurity",
    12: "Electric Vehicles and Charging Infrastructure",
    13: "Ancillary Services and Demand-Side Flexibility",
    14: "Comparative Energy-System Performance Analysis",
    15: "Climate Change and Water-Energy Nexus",
    16: "Renewable and Distributed Grid Integration Challenges",
    17: "Power-System Modeling and Simulation",
    18: "Life-Cycle and Environmental Impact Assessment",
    19: "Distributed-Energy Adoption and Energy Equity",
    20: "Distributed Microgrid Control and Multi-Agent Systems",
})

scopus_topic_labels.update({
    11: "Grid Flexibility and TSO-DSO Coordination",
    12: "Power-System Optimization Frameworks and Validation",
    13: "FACTS Device Placement and Optimization",
    14: "Distribution-System Planning and Evaluation Methods",
    15: "Renewable Generation and Siting Assessment",
    16: "Energy and Power Forecasting",
    17: "Smart-Grid Technologies and Applications",
    18: "Multi-Objective and Evolutionary Optimization",
    19: "Energy Efficiency and Decarbonization",
    20: "Cost and Loss Optimization in Power Systems",
})

In [49]:
show_topic_range(
    "overton",
    21,
    30,
)

OVERTON — Topic 21
======================================================================

Top terms:
system, paper, reliabl, ieee, provid, present, integr, interconnect, becom, overal

Representative publications:

1. Reliability and availability modelling of combined heat and power (CHP) systems
   Topic probability: 0.1515

2. Framework of a benchmark testbed for power system cyber-physical reliability studies
   Topic probability: 0.1379

3. Reliability of power system considering replacement of conventional power plants with renewables
   Topic probability: 0.1295

4. Excitation system models for power system stability studies: IEEE committee report
   Topic probability: 0.1203

5. Coarse-grained distributed optimal power flow
   Topic probability: 0.1190


OVERTON — Topic 22
======================================================================

Top terms:
problem, optim, solut, propos, algorithm, comput, solv, formul, ieee, constraint

Representative publications:

1. A Laplacian-Based Approach for Finding Near Globally Optimal Solutions to OPF Problems
   Topic probability: 0.3933

2. Semidefinite programming for optimal power flow problems
   Topic probability: 0.3629

3. Convex Relaxations of Optimal Power Flow Problems: An Illustrative Example
   Topic probability: 0.3533

4. AC OPF in radial distribution networks – Part I: On the limits of the branch flow convexification and the alternating direction method of multipliers
   Topic probability: 0.3045

5. Implementation of a large-scale optimal power flow solver based on semidefinite programming
   Topic probability: 0.2966


OVERTON — Topic 23
======================================================================

Top terms:
time, variabl, year, hour, period, averag, high, region, annual, correl

Representative publications:

1. Long-term spatial and temporal solar resource variability over America using the NSRDB version 3 (1998–2017)
   Topic probability: 0.3626

2. Simulation of PV Variability as a Function of PV Generation and Plant Size
   Topic probability: 0.2526

3. Assessing variability of wind speed: Comparison and validation of 27 methodologies
   Topic probability: 0.2410

4. Scales of spatial and temporal variation of solar irradiance on Reunion tropical island
   Topic probability: 0.2403

5. Long-term variability of solar direct and global radiation derived from ISCCP data and comparison with reanalysis data
   Topic probability: 0.2323


OVERTON — Topic 24
======================================================================

Top terms:
storag, batteri, energi, generat, use, capac, grid, limit, fluctuat, degrad

Representative publications:

1. Research on Power Coordination Control Strategy of Microgrid Based on Reconfigurable Energy Storage
   Topic probability: 0.2363

2. Analysis of solar photovoltaic-battery system for off-grid DC load application
   Topic probability: 0.2287

3. A review of available methods and development on energy storage; Technology update
   Topic probability: 0.2240

4. Evaluation of grid-level adaptability for stationary battery energy storage system applications in Europe
   Topic probability: 0.2222

5. Levelised Cost of Storage for Pumped Heat Energy Storage in comparison with other energy storage technologies
   Topic probability: 0.2203


OVERTON — Topic 25
======================================================================

Top terms:
estim, state, measur, observ, robust, use, ieee, paper, unit, algorithm

Representative publications:

1. A robust extended Kalman filter for power system dynamic state estimation using PMU measurements
   Topic probability: 0.4217

2. LAV based robust state estimation for systems measured by PMUs
   Topic probability: 0.3563

3. Robust Matrix Completion State Estimation in Distribution Systems
   Topic probability: 0.3558

4. Observability analysis and bad data processing for state estimation with equality constraints
   Topic probability: 0.3037

5. Diagnosis of Outliers and Cyber Attacks in Dynamic PMU-Based Power State Estimation
   Topic probability: 0.2994


OVERTON — Topic 26
======================================================================

Top terms:
distribut, network, fault, ieee, voltag, feeder, protect, locat, test, propos

Representative publications:

1. Optimal distribution network reconfiguration with penetration of distributed energy resources
   Topic probability: 0.2950

2. Optimal protection coordination for meshed distribution systems with DG using dual setting directional over-current relays
   Topic probability: 0.2893

3. Incorporating earth fault location in management-control scheme for distribution networks
   Topic probability: 0.2848

4. Optimal Coordination of Directional Overcurrent Relays Using a New Time-Current-Voltage Characteristic
   Topic probability: 0.2748

5. Impact of distributed generation on Volt/Var control in distribution networks
   Topic probability: 0.2733


OVERTON — Topic 27
======================================================================

Top terms:
load, meter, smart, consumpt, custom, cluster, data, profil, applianc, aggreg

Representative publications:

1. Fuzzy based clustering of smart meter data using real power and THD patterns
   Topic probability: 0.3642

2. PALDi: Online load disaggregation via particle filtering
   Topic probability: 0.3356

3. A hybrid machine learning model for electricity consumer categorization using smart meter data
   Topic probability: 0.3202

4. Clustering and Analysis of Household Power Load Based on HMM and Multi-factors
   Topic probability: 0.3120

5. Smart meter data taxonomy for demand side management in smart grids
   Topic probability: 0.3049


OVERTON — Topic 28
======================================================================

Top terms:
technolog, develop, industri, deploy, role, new, advanc, key, emerg, innov

Representative publications:

1. The Role of Renewable Energy Sources and Industry 4.0 Focus for Africa: A Review
   Topic probability: 0.3034

2. To decarbonize industry, we must decarbonize heat
   Topic probability: 0.2638

3. The Power of Change: Innovation for Development and Deployment of Increasingly Clean Electric Power Technologies
   Topic probability: 0.2558

4. Technology Framework, Application Status and Prospects on Electric Power Artificial Intelligence; [电力人工智能技术研究框架、应用现状及展望]
   Topic probability: 0.2290

5. Comprehensive review of artificial intelligence applications in renewable energy systems: current implementations and emerging trends
   Topic probability: 0.1963


OVERTON — Topic 29
======================================================================

Top terms:
demand, energi, build, heat, manag, electr, respons, effici, thermal, peak

Representative publications:

1. Reduction of heat pump induced peak electricity use and required generation capacity through thermal energy storage and demand response
   Topic probability: 0.2890

2. Quantifying the impact of residential space heating electrification on the Texas electric grid
   Topic probability: 0.2704

3. Community-scale interaction of energy efficiency and demand flexibility in residential buildings
   Topic probability: 0.2689

4. Exploiting district cooling network and urban building energy modeling for large-scale integrated energy conservation analyses
   Topic probability: 0.2500

5. Residential natural gas demand response potential during extreme cold events in electricity-gas coupled energy systems
   Topic probability: 0.2459


OVERTON — Topic 30
======================================================================

Top terms:
research, review, discuss, literatur, recent, futur, present, paper, provid, comprehens

Representative publications:

1. A systematic review on DC-microgrid protection and grounding techniques: Issues, challenges and future perspective
   Topic probability: 0.2265

2. Comprehensive review of the dynamic thermal rating system for sustainable electrical power systems
   Topic probability: 0.2242

3. Hybrid AC-DC Microgrid: Systematic Evaluation of Control Strategies
   Topic probability: 0.2014

4. A review on peak load shaving strategies
   Topic probability: 0.1986

5. A survey on state estimation techniques and challenges in smart distribution systems
   Topic probability: 0.1927

In [50]:
show_topic_range(
    "scopus",
    21,
    30,
)

SCOPUS — Topic 21
======================================================================

Top terms:
distribut, direct, algorithm, altern, central, local, converg, decentr, method, propos

Representative publications:

1. Impact of communication delay on asynchronous distributed optimal power flow using ADMM
   Topic probability: 0.3476

2. A Fully-Decentralized Consensus-Based ADMM Approach for DC-OPF with Demand Response
   Topic probability: 0.3350

3. A fully distributed asynchronous approach for multi-area coordinated network-constrained unit commitment
   Topic probability: 0.3178

4. Distributed Energy Optimization in MAS-based Microgrids using Asynchronous ADMM
   Topic probability: 0.2835

5. Consensus ADMM and Proximal ADMM for economic dispatch and AC OPF with SOCP relaxation
   Topic probability: 0.2832


SCOPUS — Topic 22
======================================================================

Top terms:
load, demand, electr, respons, peak, consumpt, suppli, util, manag, use

Representative publications:

1. Intelligent Demand Side Management for Exhaustive Techno-Economic Analysis of Microgrid System
   Topic probability: 0.3187

2. Tolerance-Based Demand-Side Management for Load Shifting in Rural Areas of Southern Brazil
   Topic probability: 0.2798

3. Demand Response for Optimal Power Usage Scheduling Considering Time and Power Flexibility of Load in Smart Grid
   Topic probability: 0.2561

4. A comprehensive review of smart metering design, demand side management and load forecasting in smart grid
   Topic probability: 0.2190

5. Distributed coordination framework for on-line scheduling and power demand balancing of households communities
   Topic probability: 0.2190


SCOPUS — Topic 23
======================================================================

Top terms:
comput, effici, time, complex, requir, solut, approach, larg, quantum, high

Representative publications:

1. Limitations of Fault-Tolerant Quantum Linear System Solvers for Quantum Power Flow
   Topic probability: 0.2751

2. Quantum–classical co-simulation for smart grids: a proof-of-concept study on feasibility and obstacles
   Topic probability: 0.2670

3. Quantum-Assisted Multi-Output Gaussian Processes for Line Parameter Estimation in Power Systems
   Topic probability: 0.2623

4. Power flow analysis using quantum and digital annealers: a discrete combinatorial optimization approach
   Topic probability: 0.2418

5. Quantum optimization approach based on Qibo framework for DC-OPF
   Topic probability: 0.2397


SCOPUS — Topic 24
======================================================================

Top terms:
use, result, present, case, time, two, test, obtain, order, valu

Representative publications:

1. Statistical analysis of power flows based on system marginal price differentials between two power systems
   Topic probability: 0.1935

2. Forecasting Power Quality Parameters Using Decision Tree and KNN Algorithms in a Small-Scale Off-Grid Platform
   Topic probability: 0.1929

3. Multi-Objective Feature Selection Using HPWOA for Improved BMS Fault Diagnosis in Electric Vehicles
   Topic probability: 0.1881

4. N − k Static Security Assessment for Power Transmission System Planning Using Machine Learning
   Topic probability: 0.1856

5. A real time approach to identify actions to prevent voltage collapse using genetic algorithms and neural networks
   Topic probability: 0.1818


SCOPUS — Topic 25
======================================================================

Top terms:
uncertainti, robust, scenario, stochast, propos, model, probabilist, probabl, generat, uncertain

Representative publications:

1. Bayesian Nonparametric Two-Stage Distributionally Robust Unit Commitment Optimization: From Global Multimodality to Local Trimming-Wasserstein Ambiguity
   Topic probability: 0.2655

2. Considering the Probabilistic Section Limit Transmission Capacity Calculation Method for the Confidence Interval of New Energy Output
   Topic probability: 0.2611

3. Multivariate Uncertainty Set Based Robust Operation of Integrated Electricity and Heating Systems with Variable Mass Flow
   Topic probability: 0.2483

4. Short-term power load probability density forecasting based on Yeo-Johnson transformation quantile regression and Gaussian kernel function
   Topic probability: 0.2360

5. A novel conditional diffusion model for joint source-load scenario generation considering both diversity and controllability
   Topic probability: 0.2333


SCOPUS — Topic 26
======================================================================

Top terms:
system, attack, secur, detect, data, communic, inject, integr, ieee, threat

Representative publications:

1. An Extended False Data Injection Attack via Deep Reinforcement Learning: Attack Model and Countermeasures in Cyber-Physical Power Systems
   Topic probability: 0.3599

2. False Data Injection Attack with Max-Min Optimization in Smart Grid
   Topic probability: 0.3380

3. Novel Data-Driven Models for Detecting and Mitigating False Data Injection Attacks in Automatic Generation Control Considering Nonlinearities
   Topic probability: 0.3234

4. Breaking the flow and the bank: Stealthy cyberattacks on water network hydraulics
   Topic probability: 0.3161

5. Simulation of multi-stage attack and defense mechanisms in smart grids
   Topic probability: 0.3055


SCOPUS — Topic 27
======================================================================

Top terms:
electr, charg, vehicl, station, transport, strategi, develop, batteri, demand, drive

Representative publications:

1. Intelligent Charging Navigation for Electric Vehicles Based on Reservation Charging Service
   Topic probability: 0.3252

2. Dynamic pricing and demand management of PEV charging station using multi-agent deep deterministic policy gradient based charging coordination algorithm
   Topic probability: 0.3043

3. Electric automobile route scheduling with time setting using machine learning methods
   Topic probability: 0.2914

4. Optimal charging strategy for Plug-in Hybrid Electric Vehicle using evolutionary algorithm
   Topic probability: 0.2640

5. Urban public charging infrastructure planning for electric vehicles: A continuum approximation approach
   Topic probability: 0.2628


SCOPUS — Topic 28
======================================================================

Top terms:
dispatch, schedul, oper, unit, generat, econom, constraint, problem, optim, propos

Representative publications:

1. A review of recent advances in dynamic economic dispatch
   Topic probability: 0.2550

2. Hydro thermal scheduling using particle swarm optimization
   Topic probability: 0.2381

3. A Hybrid Particle Swarm Optimization employing Genetic Algorithm for unit commitment problem
   Topic probability: 0.2215

4. An efficient technique to solve combined economic and emission dispatch problem using modified Ant colony optimization
   Topic probability: 0.2159

5. Constrained optimization using evolutionary programming for dynamic economic dispatch of power systems
   Topic probability: 0.2121


SCOPUS — Topic 29
======================================================================

Top terms:
topolog, graph, physic, featur, structur, attent, exist, mechan, spatial, task

Representative publications:

1. IMPROVING GRAPH NEURAL NETWORKS BY LEARNING CONTINUOUS EDGE DIRECTIONS
   Topic probability: 0.3663

2. PINN-Inspired Topology-Aware Learning for Harmonic State Recognition in Multi-Node Coupled Systems
   Topic probability: 0.2851

3. Source-Load-Topo Joint Scenario Generation Based on Graph Variational Auto-Encoder
   Topic probability: 0.2723

4. Heterogeneous Graph Neural Network with Local and Global Message Passing for AC-Optimal Power Flow Solutions
   Topic probability: 0.2484

5. Physics-guided Chebyshev graph convolution network for optimal power flow
   Topic probability: 0.2430


SCOPUS — Topic 30
======================================================================

Top terms:
reinforc, deep, agent, polici, decis, realtim, action, process, train, drl

Representative publications:

1. Safe Reinforcement Learning for Energy Management of Electrified Vehicle With Novel Physics-Informed Exploration Strategy
   Topic probability: 0.3034

2. Safe deep reinforcement learning-based constrained optimal control scheme for active distribution networks
   Topic probability: 0.2947

3. DistFlow Safe Reinforcement Learning Algorithm for Voltage Magnitude Regulation in Distribution Networks
   Topic probability: 0.2892

4. Multi-Agent Reinforcement Learning with Safety Layer for Active Voltage Control
   Topic probability: 0.2749

5. Model-Data Hybrid-Driven Real-Time Optimal Power Flow: A Physics-Informed Reinforcement Learning Approach
   Topic probability: 0.2530

In [51]:
overton_topic_labels.update({
    21: "Power-System Reliability and Stability",
    22: "Convex Relaxations and Mathematical Programming for OPF",
    23: "Wind and Solar Resource Variability",
    24: "Energy Storage Technologies and Grid Integration",
    25: "Power-System State Estimation and Observability",
    26: "Distribution-System Protection and Reconfiguration",
    27: "Smart-Meter Analytics and Load Profiling",
    28: "Energy Technology Innovation and Deployment",
    29: "Building Energy Flexibility and Demand Response",
    30: "Power-System Review and Synthesis Studies",
})

scopus_topic_labels.update({
    21: "Distributed Optimization and ADMM",
    22: "Demand-Side Management and Demand Response",
    23: "Quantum Computing for Power-System Optimization",
    24: "Data-Driven Power-System Analysis and Security Assessment",
    25: "Robust, Stochastic, and Probabilistic Optimization",
    26: "Cybersecurity and False-Data Injection Attacks",
    27: "Electric-Vehicle Charging and Infrastructure Planning",
    28: "Economic Dispatch and Unit Scheduling",
    29: "Graph Neural Networks and Topology-Aware Learning",
    30: "Safe and Physics-Informed Reinforcement Learning",
})

In [52]:
show_topic_range(
    "overton",
    31,
    40,
)

OVERTON — Topic 31
======================================================================

Top terms:
market, electr, price, particip, mechan, trade, competit, paper, consum, prosum

Representative publications:

1. Competitive electricity markets with consumer subscription service in a smart grid
   Topic probability: 0.3182

2. Bid Forwarding as a Way to Connect Sequential Markets: Opportunities and Barriers
   Topic probability: 0.3061

3. Wind energy aggregation: A coalitional game approach
   Topic probability: 0.2857

4. Smart contract-based campus demonstration of decentralized transactive energy auctions
   Topic probability: 0.2792

5. Nash equilibria in electricity markets with discrete prices
   Topic probability: 0.2765


OVERTON — Topic 32
======================================================================

Top terms:
frequenc, system, stabil, respons, dynam, generat, island, transient, mode, synchron

Representative publications:

1. Stability Evaluation of AC/DC Hybrid Microgrids Considering Bidirectional Power Flow through the Interlinking Converters
   Topic probability: 0.2671

2. Coherent swing instability of power grids
   Topic probability: 0.2619

3. Interarea Oscillation Damping Controls for Wind Power Plants
   Topic probability: 0.2579

4. Placement and Implementation of Grid-Forming and Grid-Following Virtual Inertia and Fast Frequency Response
   Topic probability: 0.2536

5. Trade-off analysis of virtual inertia and fast primary frequency control during frequency transients in a converter dominated network
   Topic probability: 0.2533


OVERTON — Topic 33
======================================================================

Top terms:
wind, turbin, farm, wake, speed, offshor, blade, rotor, product, ltd

Representative publications:

1. Changing the rotational direction of a wind turbine under veering inflow: A parameter study
   Topic probability: 0.4636

2. Does the rotational direction of a wind turbine impact the wake in a stably stratified atmospheric boundary layer?
   Topic probability: 0.4233

3. Results from a wake-steering experiment at a commercial wind plant: Investigating the wind speed dependence of wake-steering performance
   Topic probability: 0.4033

4. Three-dimensional structure of wind turbine wakes as measured by scanning lidar
   Topic probability: 0.3961

5. Effects of upstream rotor tilt on a downstream floating wind turbine
   Topic probability: 0.3699


OVERTON — Topic 34
======================================================================

Top terms:
forecast, predict, model, uncertainti, error, weather, use, probabilist, improv, accuraci

Representative publications:

1. Ensemble solar forecasting using data-driven models with probabilistic post-processing through GAMLSS
   Topic probability: 0.4242

2. An objective methodology for configuring and down-selecting an NWP ensemble for low-level wind prediction
   Topic probability: 0.3922

3. A benchmark of statistical regression methods for short-term forecasting of photovoltaic electricity production. Part II: Probabilistic forecast of daily production
   Topic probability: 0.3478

4. Probabilistic solar power forecasting using bayesian model averaging
   Topic probability: 0.3396

5. Comparison of intraday probabilistic forecasting of solar irradiance using only endogenous data
   Topic probability: 0.3360


OVERTON — Topic 35
======================================================================

Top terms:
solar, irradi, radiat, measur, use, cloud, surfac, direct, dni, atmospher

Representative publications:

1. A new database of global and direct solar radiation using the eastern meteosat satellite, models and validation
   Topic probability: 0.4759

2. Intercomparison of 51 radiometers for determining global horizontal irradiance and direct normal irradiance measurements
   Topic probability: 0.4735

3. Performance evaluation of radiation sensors for the solar energy sector
   Topic probability: 0.4481

4. Generating synthetic five-minute solar irradiance values from hourly observations
   Topic probability: 0.4472

5. Shadow camera system for the generation of solar irradiance maps
   Topic probability: 0.4466


OVERTON — Topic 36
======================================================================

Top terms:
method, propos, base, use, techniqu, appli, approach, result, novel, paper

Representative publications:

1. Efficient SPF approach based on regression and correction models for active distribution systems
   Topic probability: 0.1939

2. Challenges and solutions in determining dilution ratios and emission factors from chase measurements of passenger vehicles
   Topic probability: 0.1806

3. A Novel Hybrid Islanding Detection Method for Inverter-Based DGs Using SFS and ROCOF
   Topic probability: 0.1765

4. A new power system transient stability assessment method based on Type-2 fuzzy neural network estimation
   Topic probability: 0.1574

5. Regional forecasts and smoothing effect of photovoltaic power generation in Japan: An approach with principal component analysis
   Topic probability: 0.1505


OVERTON — Topic 37
======================================================================

Top terms:
energi, transit, communiti, develop, local, studi, sustain, identifi, urban, within

Representative publications:

1. Multi-level functional analysis of developing prosumers and energy communities with value creation framework
   Topic probability: 0.3556

2. The food water energy nexus in an urban context: Connecting theory and practice for nexus governance
   Topic probability: 0.3405

3. Who's fighting for justice?: Advocacy in energy justice and just transition scholarship
   Topic probability: 0.3208

4. A Qualitative Based Causal-Loop Diagram for Understanding Policy Design Challenges for a Sustainable Transition Pathway: The Case of Tees Valley Region, UK
   Topic probability: 0.2667

5. Towards impactful energy justice research: Transforming the power of academic engagement
   Topic probability: 0.2632


OVERTON — Topic 38
======================================================================

Top terms:
materi, hydrogen, cell, process, product, high, cycl, temperatur, devic, recycl

Representative publications:

1. Enhanced Catalyst Durability for Bio-Based Adipic Acid Production by Atomic Layer Deposition
   Topic probability: 0.4157

2. Role of Electronic Passivation in Stabilizing the Lithium-LixPOy Nz Solid-Electrolyte Interphase
   Topic probability: 0.3953

3. MgxZn1−xO contact to CuGa3Se5 absorber for photovoltaic and photoelectrochemical devices
   Topic probability: 0.3704

4. SiO2 is wasted space in single-nanometer-scale silicon nanoparticle-based composite anodes for Li-ion electrochemical energy storage
   Topic probability: 0.3484

5. Intermediate temperature fuel cells: Via an ion-pair coordinated polymer electrolyte
   Topic probability: 0.3440


OVERTON — Topic 39
======================================================================

Top terms:
transmiss, line, current, use, transform, high, limit, connect, capac, larg

Representative publications:

1. Transmission line ampacity improvements of altalink wind plant overhead tie-lines using weather-based dynamic line rating
   Topic probability: 0.2919

2. Review of dynamic line rating systems for wind power integration
   Topic probability: 0.2821

3. Optimal management of power networks using a dynamic line rating approach
   Topic probability: 0.2819

4. A Review of Dynamic Thermal Line Rating Methods with Forecasting
   Topic probability: 0.2619

5. Dynamic hosting capacity analysis for distributed photovoltaic resources—Framework and case study
   Topic probability: 0.2328


OVERTON — Topic 40
======================================================================

Top terms:
control, propos, strategi, scheme, can, simul, paper, regul, realtim, effect

Representative publications:

1. Hybrid power management for DC microgrid cluster
   Topic probability: 0.2581

2. Dual mode linguistic hedge fuzzy logic controller for an isolated wind-diesel hybrid power system with superconducting magnetic energy storage unit
   Topic probability: 0.2312

3. Adaptive fuzzy control for wind-Diesel weak power systems
   Topic probability: 0.2230

4. Control of Modular Multilevel Converters for integration of distributed generation sources into the power grid
   Topic probability: 0.2128

5. Active and Passive Control of a Dual Rotor Wind Turbine Generator for DC Grids
   Topic probability: 0.2055

In [53]:
show_topic_range(
    "scopus",
    31,
    40,
)

SCOPUS — Topic 31
======================================================================

Top terms:
distribut, network, der, resourc, node, activ, ieee, feeder, reconfigur, radial

Representative publications:

1. Quantifying the Impact of Day-ahead Renewable Forecasts on DER Hosting Capacity Estimation
   Topic probability: 0.2071

2. Analysis on the Reactive Power Regulation of Inverter and Voltage in Distribution Network
   Topic probability: 0.1975

3. Distributed control of active distribution networks to support voltage control in subtransmission networks
   Topic probability: 0.1925

4. Network reconfiguration at the power distribution system with dispersed generations for loss reduction
   Topic probability: 0.1866

5. Artificial Intelligence for Hosting Capacity Analysis: A Systematic Literature Review
   Topic probability: 0.1705


SCOPUS — Topic 32
======================================================================

Top terms:
problem, solut, solv, opf, optim, constraint, program, formul, feasibl, linear

Representative publications:

1. A non-convex alternating direction method of multipliers heuristic for optimal power flow
   Topic probability: 0.3534

2. Eigenvalue-Based Hidden Convexity Algorithm for Radial Distribution Network Optimization with Non-Convex Power Flow Equations
   Topic probability: 0.3416

3. GPU-Accelerated DCOPF using Gradient-Based Optimization
   Topic probability: 0.2986

4. Dynamic optimal power flow using interior point method and benders decomposition considering active and reactive constraints
   Topic probability: 0.2949

5. Dual Conic Proxy for Semidefinite Relaxation of AC Optimal Power Flow
   Topic probability: 0.2932


SCOPUS — Topic 33
======================================================================

Top terms:
system, stabil, transient, dynam, analysi, assess, simul, condit, oscil, damp

Representative publications:

1. Design of firefly power system stabilizer for stability improvement of multi machine system under contingency
   Topic probability: 0.2982

2. Effective optimization technique for power system stabilization using Artificial Bee Colony
   Topic probability: 0.2660

3. Design of the PI–UPFC–POD and PSS Damping Controllers Using an Artificial Bee Colony Algorithm
   Topic probability: 0.2517

4. Transient stability assessment and enhancement of hydropower plant using artificial neural network
   Topic probability: 0.2452

5. Performance investigation of SVR for evaluating Voltage Stability Margin in a Power utility
   Topic probability: 0.2331


SCOPUS — Topic 34
======================================================================

Top terms:
system, plan, natur, author, oper, part, present, springer, electr, exclus

Representative publications:

1. Challenges in ensuring reliability of renewable energy grids: evaluation strategies
   Topic probability: 0.1970

2. Introduction
   Topic probability: 0.1714

3. Operational planning of distribution networks based on utility planning concepts
   Topic probability: 0.1586

4. A comprehensive review of optimization, market strategies, and AI applications in energy storage systems
   Topic probability: 0.1548

5. Power distribution system planning framework (A comprehensive review)
   Topic probability: 0.1548


SCOPUS — Topic 35
======================================================================

Top terms:
convert, current, qualiti, harmon, voltag, high, modul, switch, effici, sourc

Representative publications:

1. Analysis and Design of a Cyclo-Active-Bridge Inverter for Single-Stage Three-Phase Grid Interface
   Topic probability: 0.3657

2. A Multilevel Three-Phase Integrated AC–DC Bidirectional Resonant Converter for BESS
   Topic probability: 0.3642

3. An innovative 11-level multilevel inverter topology with rotating trapezoidal SPWM for industrial and renewable applications
   Topic probability: 0.3486

4. Single Stage Three Phase Module and Modulation with Current stress Minimisation for Solid State Transformer based Fast Charging Stations
   Topic probability: 0.3389

5. Bidirectional Current-Fed CLLC Resonant Converter Employing Asymmetric PWM
   Topic probability: 0.3130


SCOPUS — Topic 36
======================================================================

Top terms:
system, bus, ieee, transmiss, line, secur, test, conting, generat, congest

Representative publications:

1. An analysis of the security of multi-area power transmission lines using fuzzy-ACO
   Topic probability: 0.2609

2. Combined learning and analytical model based early warning algorithm for real-time congestion management
   Topic probability: 0.2431

3. Static available transfer capability calculation using real coded genetic algorithm
   Topic probability: 0.2342

4. Study of Static Security Assessment Accuracy Results using Random Forest with Various Types of Training and Test Datasets
   Topic probability: 0.2300

5. Power system contingency classification using machine learning technique
   Topic probability: 0.2276


SCOPUS — Topic 37
======================================================================

Top terms:
energi, renew, sourc, integr, manag, system, resourc, res, increas, intermitt

Representative publications:

1. Advances in Modeling and Optimization of Intelligent Power Systems Integrating Renewable Energy in the Industrial Sector: A Multi-Perspective Review
   Topic probability: 0.1955

2. Energy Management Systems for Hybrid Renewable Energy Systems: A Comprehensive Review
   Topic probability: 0.1879

3. Forecast of renewable energy penetration potential in the goal of carbon peaking and carbon neutrality in China
   Topic probability: 0.1749

4. Enhancing the Performance of Hybrid Microgrids through Turbulent Flow-Based Optimization
   Topic probability: 0.1714

5. Optimal Operation of Integrated Energy Systems Under Uncertainties: Distributionally Robust and Stochastic Methods
   Topic probability: 0.1714


SCOPUS — Topic 38
======================================================================

Top terms:
energi, storag, system, batteri, hybrid, manag, strategi, hydrogen, cell, fuel

Representative publications:

1. Optimal design and control of battery-ultracapacitor hybrid energy storage system for BEV operating at extreme temperatures
   Topic probability: 0.3093

2. An Integrated Super Capacitor and Li-Ion Battery-based Hybrid Energy Storage Design: An Application for Electric Vehicles
   Topic probability: 0.2362

3. Modeling and Mitigating the Cycle Aging Cost of Vehicle Batteries in Energy Transportation Nexus
   Topic probability: 0.2270

4. Simultaneous energy management and optimal components sizing of a zero-emission ferry boat
   Topic probability: 0.2237

5. Optimizing Electric Vehicles efficiency with hybrid energy storage: Comparative analysis of rule-based and neural network power management systems
   Topic probability: 0.2211


SCOPUS — Topic 39
======================================================================

Top terms:
enhanc, effici, challeng, address, signific, integr, reliabl, offer, ensur, introduc

Representative publications:

1. Data-Driven Adequacy and Security Assessment: Machine Learning Trends for Reliable Smart Energy Networks
   Topic probability: 0.2078

2. Data-Driven Distributed Energy Management in Interconnected Smart Grids/Microgrids: A Critical Review of ADMM and Related Optimization Algorithms
   Topic probability: 0.2029

3. Enhanced Automated Deep Learning Application for Short-Term Load Forecasting
   Topic probability: 0.2018

4. AI and Expert Insights for Sustainable Energy Future
   Topic probability: 0.1758

5. A Multi-Local Search-Based SHADE for Wind Farm Layout Optimization
   Topic probability: 0.1757


SCOPUS — Topic 40
======================================================================

Top terms:
reliabl, system, resili, assess, failur, risk, evalu, event, impact, outag

Representative publications:

1. Cost-effective retrofits of power grids based on critical cascading failure scenarios identified by multi-group non-dominated sorting genetic algorithm
   Topic probability: 0.2890

2. Coordination of preventive, emergency and restoration dispatch against cascading failures for resilience enhancement
   Topic probability: 0.2880

3. Enhanced voltage stability assessment and remedial action schemes for resilient power systems under cascading contingencies
   Topic probability: 0.2819

4. Hardening critical components to enhance grid resilience by fusing the data of power networks and natural disasters
   Topic probability: 0.2784

5. Resilient Power Systems against Wildfire Risks: Towards a Human-Centric and Secure Future
   Topic probability: 0.2740

In [54]:
overton_topic_labels.update({
    31: "Electricity Markets and Transactive Energy",
    32: "Frequency Stability and Converter-Dominated Grid Dynamics",
    33: "Wind-Turbine Wakes and Wind-Farm Aerodynamics",
    34: "Probabilistic Renewable-Energy Forecasting",
    35: "Solar Irradiance Measurement and Resource Assessment",
    36: "Power-System Computational and Assessment Methods",
    37: "Energy Transition, Communities, and Energy Justice",
    38: "Energy Materials, Batteries, and Electrochemical Technologies",
    39: "Dynamic Line Rating and Transmission Capacity",
    40: "Microgrid and Converter Control Strategies",
})

scopus_topic_labels.update({
    31: "Active Distribution Networks and DER Integration",
    32: "Mathematical Programming and OPF Solution Methods",
    33: "Power-System Stability and Oscillation Control",
    34: "Power-System Planning and Reliability Studies",
    35: "Power Electronics and Converter Systems",
    36: "Transmission Security and Contingency Assessment",
    37: "Renewable-Energy Integration and Management",
    38: "Battery and Hybrid Energy Storage Systems",
    39: "Data-Driven Smart-Energy Methods",
    40: "Grid Resilience and Cascading-Failure Risk",
})

In [55]:
show_topic_range(
    "overton",
    41,
    50,
)

OVERTON — Topic 41
======================================================================

Top terms:
emiss, gas, fuel, carbon, reduc, environment, reduct, fossil, product, decarbon

Representative publications:

1. A spatial and fleet disaggregated approach to calculating the NOX emissions inventory for non-road mobile machinery in London
   Topic probability: 0.4286

2. Decarbonizing maritime transport: The importance of engine technology and regulations for LNG to serve as a transition fuel
   Topic probability: 0.4175

3. Environmental sustainability of cooking fuels in remote communities: Life cycle and local impacts
   Topic probability: 0.3233

4. Total Methane and CO2Emissions from Liquefied Natural Gas Carrier Ships: The First Primary Measurements
   Topic probability: 0.3214

5. Sustainability implications of different carbon dioxide removal technologies in the context of Europe's climate neutrality goal
   Topic probability: 0.3085


OVERTON — Topic 42
======================================================================

Top terms:
energi, renew, sourc, resourc, increas, share, elsevi, sustain, res, effici

Representative publications:

1. Renewable energy from the ocean
   Topic probability: 0.2556

2. Tidal energy update 2009
   Topic probability: 0.2105

3. Interactions between renewable energy policy and renewable energy industrial policy: A critical analysis of china's policy approach to renewable energies
   Topic probability: 0.1908

4. Renewable energy in eastern Asia: Renewable energy policy review and comparative SWOT analysis for promoting renewable energy in Japan, South Korea, and Taiwan
   Topic probability: 0.1892

5. Wind energy: Trends and enabling technologies
   Topic probability: 0.1875


OVERTON — Topic 43
======================================================================

Top terms:
cost, reduc, valu, benefit, reduct, econom, result, lower, level, compar

Representative publications:

1. Experience Curves for Operations and Maintenance Costs of Renewable Energy Technologies
   Topic probability: 0.2028

2. Are coupled renewable-battery power plants more valuable than independently sited installations?
   Topic probability: 0.2000

3. Projecting the Future Levelized Cost of Electricity Storage Technologies
   Topic probability: 0.1979

4. A stochastic operational planning model for a zero emission building with emission compensation
   Topic probability: 0.1799

5. Analytical approach to quantitative risk assessment for solar power projects
   Topic probability: 0.1796


OVERTON — Topic 44
======================================================================

Top terms:
time, algorithm, use, perform, base, approach, result, featur, paramet, compar

Representative publications:

1. Fault diagnosis of photovoltaic panels using full I–V characteristics and machine learning techniques
   Topic probability: 0.2949

2. Fully Unsupervised Deepfake Video Detection Via Enhanced Contrastive Learning
   Topic probability: 0.2540

3. Feature selection of power system transient stability assessment based on random forest and recursive feature elimination
   Topic probability: 0.2538

4. A new BVM based approach to transient security assessment
   Topic probability: 0.2406

5. TS-benchmark: A benchmark for time series databases
   Topic probability: 0.2312


OVERTON — Topic 45
======================================================================

Top terms:
voltag, convert, invert, current, ieee, present, paper, devic, output, reactiv

Representative publications:

1. Soft switching bidirectional converter for reflex charger with minimum switches
   Topic probability: 0.3667

2. Large-Signal Impedance-Based Modeling and Mitigation of Resonance of Converter-Grid Systems
   Topic probability: 0.3439

3. A Two-Stage DC-DC Isolated Converter for Battery-Charging Applications
   Topic probability: 0.3410

4. A Two-Stage Isolated Resonant DC-DC Converter for Wide Voltage Range Operation
   Topic probability: 0.3403

5. Transformerless inverter with virtual DC bus concept for cost-effective grid-connected PV power systems
   Topic probability: 0.3375


OVERTON — Topic 46
======================================================================

Top terms:
will, need, futur, new, increas, requir, year, mani, like, make

Representative publications:

1. Exploring Consumer Acceptance and Engagement with “Smart Meters”
   Topic probability: 0.1812

2. Enabled by high power electronics - Energy efficiency, renewables and smart grids
   Topic probability: 0.1703

3. The migrate project: The challenges of operating a transmission grid with only inverter-based generation. A grid-forming control improvement with transient current-limiting control
   Topic probability: 0.1615

4. Demand dispatch
   Topic probability: 0.1604

5. Data center growth in the United States: Decoupling the demand for services from electricity use
   Topic probability: 0.1442


OVERTON — Topic 47
======================================================================

Top terms:
event, resili, failur, risk, reliabl, sever, extrem, critic, can, outag

Representative publications:

1. Cascading failures in complex infrastructure systems
   Topic probability: 0.3191

2. Boosting the Power Grid Resilience to Extreme Weather Events Using Defensive Islanding
   Topic probability: 0.3174

3. Enhancing the RESILIENCE of the Nation’s Electricity System
   Topic probability: 0.2857

4. Social vulnerability and power loss mitigation: A case study of Puerto Rico
   Topic probability: 0.2840

5. Enhancing The Resilence Of The Nations Electricity System
   Topic probability: 0.2573


OVERTON — Topic 48
======================================================================

Top terms:
solar, plant, photovolta, instal, modul, loss, concentr, can, yield, panel

Representative publications:

1. Fundamentals of soiling processes on photovoltaic modules
   Topic probability: 0.3594

2. Self-cleaning solar mirrors using electrodynamic dust shield: Prospects and progress
   Topic probability: 0.3249

3. Power loss due to soiling on solar panel: A review
   Topic probability: 0.3018

4. Development of self-cleaning solar collectors for minimizing energy yield loss caused by dust deposi1tion
   Topic probability: 0.2935

5. Computer-based management of mirror-washing in utility-scale solar thermal plants
   Topic probability: 0.2791


OVERTON — Topic 49
======================================================================

Top terms:
can, first, two, use, larg, second, allow, one, point, step

Representative publications:

1. Optimization of Matching Layers to Extend the Usable Frequency Band for Underwater Single-Crystal Piezocomposite Transducers
   Topic probability: 0.1774

2. Identifying DQ-Domain Admittance Models of a 2.3-MVA Commercial Grid-Following Inverter via Frequency-Domain and Time-Domain Data
   Topic probability: 0.1439

3. On the scaling of wind turbine rotors
   Topic probability: 0.1429

4. Centralized self-healing scheme for electrical distribution systems
   Topic probability: 0.1341

5. Considerations when using utility-scale battery storage to black start a gas turbine generator
   Topic probability: 0.1295


OVERTON — Topic 50
======================================================================

Top terms:
data, use, detect, inform, avail, set, center, monitor, sensor, collect

Representative publications:

1. Variability extraction and synthesis via multi-resolution analysis using distribution transformer high-speed power data
   Topic probability: 0.3077

2. Big data analytics in smart grids: a review
   Topic probability: 0.2458

3. Fault and anomaly detection in district heating substations: A survey on methodology and data sets
   Topic probability: 0.2384

4. Validation of Synthetic U.S. Electric Power Distribution System Data Sets
   Topic probability: 0.2119

5. An anomaly detection framework for dynamic systems using a Bayesian hierarchical framework
   Topic probability: 0.2103

In [56]:
show_topic_range(
    "scopus",
    41,
    50,
)

SCOPUS — Topic 41
======================================================================

Top terms:
fault, protect, detect, classif, current, scheme, featur, transform, accuraci, time

Representative publications:

1. Component identification and defect detection in transmission lines based on deep learning
   Topic probability: 0.2978

2. Fault location of distribution network with distributed generation based on Karrenbauer transform and support vector machine regression
   Topic probability: 0.2865

3. SVM and DWT based Detection and Classification of Microgrid Faults using Single Point Measurement
   Topic probability: 0.2857

4. Decentralized cooperative protection strategy for smart distribution grid using Multi-Agent System
   Topic probability: 0.2848

5. Detection and Classification of Faults Using Intelligent Approach in Microgrid Network
   Topic probability: 0.2733


SCOPUS — Topic 42
======================================================================

Top terms:
algorithm, problem, search, converg, optim, test, metaheurist, hybrid, compar, solv

Representative publications:

1. An enhanced arithmetic optimization algorithm for optimal control of reactive power
   Topic probability: 0.4268

2. Modified Archimedes optimization algorithm for global optimization problems: a comparative study
   Topic probability: 0.3925

3. Real Power loss reduction by hybrid pan troglodytes optimization: extreme learning machine based augmented sine: cosine algorithms
   Topic probability: 0.3604

4. Modified random-oppositional chaotic artificial rabbit optimization algorithm for solving structural problems and optimal sizing of hybrid renewable energy system
   Topic probability: 0.3503

5. Real Power Loss Reduction by Extreme Learning Machine, Chaotic, Quantum and Opposition based California Condor Optimization Algorithms
   Topic probability: 0.3478


SCOPUS — Topic 43
======================================================================

Top terms:
applic, design, system, research, develop, provid, includ, practic, industri, engin

Representative publications:

1. Modern Power System Analysis
   Topic probability: 0.3539

2. Sustainable Manufacturing Systems: An Energy Perspective
   Topic probability: 0.3052

3. Microgrids Design and Operation Guiding Insights and Best Practices for Microgrids Development
   Topic probability: 0.2857

4. Advances in District Heating Systems and Integrating Renewables: Fundamentals, Experiments, and Applications
   Topic probability: 0.2822

5. Signal processing and networking for big data applications
   Topic probability: 0.2803


SCOPUS — Topic 44
======================================================================

Top terms:
method, propos, base, calcul, paper, can, effect, improv, result, tradit

Representative publications:

1. Calculating theoretical line losses based on improved minimum enclosing ball vector machine
   Topic probability: 0.1824

2. Simultaneous Allocation of Multi-Type Distributed Generations and Capacitors Using Generic Analytical Expressions
   Topic probability: 0.1678

3. Fast Probabilistic Energy Flow Calculation for Natural Gas Systems: A Convex Multiparametric Programming Approach
   Topic probability: 0.1630

4. Distributed Slack-Bus Based DC Optimal Power Flow with Transmission Loss: A Second-Order Cone Programming Approach and Sufficient Conditions
   Topic probability: 0.1491

5. A power flow calculation method for over-zone power supply in electrified railways connected to weak external power grids
   Topic probability: 0.1429


SCOPUS — Topic 45
======================================================================

Top terms:
adapt, dynam, condit, effici, improv, perform, enhanc, demonstr, achiev, convent

Representative publications:

1. MPP detection of a partially shaded PV array by continuous GA and hybrid PSO
   Topic probability: 0.2791

2. Soft Actor-Critic-Based MPPT Control of Solar PV Systems Under Partial Shading Conditions
   Topic probability: 0.2525

3. A comprehensive comparison of advanced metaheuristic photovoltaic maximum power tracking algorithms during dynamic and static environmental conditions
   Topic probability: 0.2517

4. Application of bio-inspired algorithms in maximum power point tracking for PV systems under partial shading conditions – A review
   Topic probability: 0.2353

5. Application of TD3-optimized improved active disturbance rejection control in MPPT of photovoltaic power generation
   Topic probability: 0.2319


SCOPUS — Topic 46
======================================================================

Top terms:
control, frequenc, strategi, regul, scheme, system, perform, fuzzi, design, paramet

Representative publications:

1. Comparative Assessment of PSO-Tuned Hybrid Fuzzy Controllers for Load Frequency Control in a Two-Area Hybrid Power System Under Nonlinear and Parametric Uncertainty
   Topic probability: 0.2857

2. A CrOA-tuned cascaded (2DOF-PDf)–(LTI) controller for coordinated LFC–AVR regulation in interconnected power systems
   Topic probability: 0.2694

3. Variable structure fuzzy gain scheduling based load frequency controller for multi source multi area hydro thermal system
   Topic probability: 0.2683

4. A multi-energy inertia-based coordinated voltage and frequency regulation in isolated hybrid power system using PI-TISMC
   Topic probability: 0.2461

5. Secondary frequency regulation strategy with fuzzy logic method and self-adaptive modification of state of charge
   Topic probability: 0.2456


SCOPUS — Topic 47
======================================================================

Top terms:
wind, generat, output, use, speed, result, variabl, turbin, propos, farm

Representative publications:

1. Modeling and Analysis of Short-term Output Prediction for Wind Farm Considering Convergence Effect and Wake Effect
   Topic probability: 0.3174

2. Spatio-temporal wind speed prediction based on Clayton Copula function with deep learning fusion
   Topic probability: 0.2959

3. Optimization of the Offshore Wind Turbines Layout Using Cuckoo Search Algorithm
   Topic probability: 0.2723

4. Modeling and Simulation of Large-Scale Wind Power Base Output Considering the Clustering Characteristics and Correlation of Wind Farms
   Topic probability: 0.2710

5. A global sensitivity analysis method applied to wind farm power output estimation models
   Topic probability: 0.2376


SCOPUS — Topic 48
======================================================================

Top terms:
propos, approach, result, novel, compar, simul, demonstr, valid, effect, perform

Representative publications:

1. Stochastic voltage estimation for islanded DC grids
   Topic probability: 0.1408

2. Deep Reinforcement Learning Based Unit Commitment Scheduling under Load and Wind Power Uncertainty
   Topic probability: 0.1341

3. Analytical Hybrid Particle Swarm Optimization Algorithm for Optimal Siting and Sizing of Distributed Generation in Smart Grid
   Topic probability: 0.1325

4. A new hybrid approach for the solution of nonconvex economic dispatch problem with valve-point effects
   Topic probability: 0.1307

5. Comparison of Linear Regression and Neural Networks for Model-Free Voltage Estimation of Low Voltage Distribution Networks with High Penetration of Residential Rooftop Solar
   Topic probability: 0.1262


SCOPUS — Topic 49
======================================================================

Top terms:
data, cluster, use, process, analysi, inform, dataset, sampl, histor, set

Representative publications:

1. Big data clustering algorithm of power system user load characteristics based on K-means and SOM neural network
   Topic probability: 0.2477

2. A review of data augmentation and evaluation for lithium-ion batteries from a temporal perspective
   Topic probability: 0.2189

3. Method for Generating Labeled Sample Sets for Power System Load Flow Relationship Learning
   Topic probability: 0.2128

4. Artificial Load Profiles and PV Generation in Renewable Energy Communities Using Generative Adversarial Networks
   Topic probability: 0.1985

5. Differentially Private Algorithms for Synthetic Power System Datasets
   Topic probability: 0.1880


SCOPUS — Topic 50
======================================================================

Top terms:
research, review, applic, futur, provid, discuss, comprehens, paper, literatur, studi

Representative publications:

1. The Rise of Particle Swarm Optimization: A Systematic Bibliometric & Thematic Review (1995–2025)
   Topic probability: 0.3152

2. Research landscape and hot topics of rooftop PV: A bibliometric and network analysis
   Topic probability: 0.3140

3. Electricity system resilience: An integrated bibliometric and systematic literature review
   Topic probability: 0.3084

4. Scientometric analysis of building integrated photovoltaics research: development, themes, and main trends
   Topic probability: 0.3068

5. Five Decades of Genetic Algorithms: A Systematic and Bibliometric Review (1975–2025)
   Topic probability: 0.2945

In [57]:
overton_topic_labels.update({
    41: "Carbon Emissions, Fuels, and Decarbonization",
    42: "Renewable-Energy Technologies and Policy",
    43: "Energy-System Costs and Economic Assessment",
    44: "Machine Learning for Power-System Monitoring and Assessment",
    45: "Power Electronics and Converter Technologies",
    46: "Future Grid Technologies and Electricity Demand",
    47: "Grid Resilience and Extreme-Event Risk",
    48: "Solar-PV Performance, Soiling, and Maintenance",
    49: "Grid Technology and System Integration Methods",
    50: "Energy Data Analytics and Anomaly Detection",
})

scopus_topic_labels.update({
    41: "Fault Detection, Classification, and Protection",
    42: "Metaheuristic Optimization Algorithms",
    43: "Power-System Engineering and Technology Applications",
    44: "Power-Flow and Network Calculation Methods",
    45: "Photovoltaic MPPT and Adaptive Control",
    46: "Load-Frequency Control and Frequency Regulation",
    47: "Wind-Power Modeling and Prediction",
    48: "Hybrid Computational Optimization Methods",
    49: "Power-System Data Analytics and Synthetic Data",
    50: "Bibliometric and Systematic Review Studies",
})

In [58]:
print(
    "Overton labels:",
    len(overton_topic_labels)
)

print(
    "Scopus labels :",
    len(scopus_topic_labels)
)

print(
    "Missing Overton:",
    sorted(
        set(range(1, 51))
        - set(overton_topic_labels)
    )
)

print(
    "Missing Scopus :",
    sorted(
        set(range(1, 51))
        - set(scopus_topic_labels)
    )
)

Overton labels: 50
Scopus labels : 50
Missing Overton: []
Missing Scopus : []

In [59]:
topic_label_maps = {
    "overton": overton_topic_labels,
    "scopus": scopus_topic_labels,
}

for corpus_name in [
    "overton",
    "scopus",
]:

    interpretation = (
        topic_interpretation_tables[
            corpus_name
        ]
        .copy()
    )

    interpretation[
        "Topic_Label"
    ] = (
        interpretation["Topic"]
        .map(
            topic_label_maps[
                corpus_name
            ]
        )
    )

    topic_interpretation_tables[
        corpus_name
    ] = interpretation

    print()
    print(corpus_name.upper())
    print("=" * len(corpus_name))

    display(
        interpretation[
            [
                "Topic",
                "Topic_Label",
                "Top_Terms",
            ]
        ]
    )

OVERTON
=======

,Topic,Topic_Label,Top_Terms
0,1,Power-System Flexibility and Grid Planning,"oper, system, flexibl, plan, integr, consid, c..."
1,2,Offshore Wind and Marine Energy Modeling,"test, condit, result, use, wave, perform, expe..."
2,3,Energy and Environmental Impact Factors,"effect, factor, rate, increas, depend, also, m..."
3,4,Electric Machine and Wind Generator Design,"design, effici, perform, can, improv, hybrid, ..."
4,5,Power-System Modeling Standards and Software T...,"applic, develop, paper, standard, includ, new,..."
5,6,Energy-System Concepts and Technology Assessment,"term, main, author, relat, concept, take, one,..."
6,7,Computational Frameworks and Algorithmic Methods,"approach, framework, can, present, process, st..."
7,8,Electricity-Sector Policy and Market Reform,"polici, electr, countri, sector, industri, sup..."
8,9,Energy Research Infrastructure and Nuclear/Fus...,"develop, project, engin, research, nation, rig..."
9,10,Operating Reserves and Renewable Balancing,"generat, reserv, unit, variabl, penetr, dispat..."
10,11,Smart-Grid Communications and Cybersecurity,"grid, smart, communic, secur, network, attack,..."
11,12,Electric Vehicles and Charging Infrastructure,"electr, vehicl, charg, transport, drive, stati..."
12,13,Ancillary Services and Demand-Side Flexibility,"provid, util, servic, regul, can, also, need, ..."
13,14,Comparative Energy-System Performance Analysis,"differ, studi, result, type, consid, compar, c..."
14,15,Climate Change and Water-Energy Nexus,"chang, climat, water, global, region, scenario..."
15,16,Renewable and Distributed Grid Integration Cha...,"challeng, integr, issu, address, solut, techni..."
16,17,Power-System Modeling and Simulation,"model, simul, dynam, interact, comput, valid, ..."
17,18,Life-Cycle and Environmental Impact Assessment,"impact, studi, analysi, assess, perform, evalu..."
18,19,Distributed-Energy Adoption and Energy Equity,"find, adopt, household, benefit, level, sugges..."
19,20,Distributed Microgrid Control and Multi-Agent ...,"distribut, microgrid, control, der, manag, ope..."
20,21,Power-System Reliability and Stability,"system, paper, reliabl, ieee, provid, present,..."
21,22,Convex Relaxations and Mathematical Programmin...,"problem, optim, solut, propos, algorithm, comp..."
22,23,Wind and Solar Resource Variability,"time, variabl, year, hour, period, averag, hig..."
23,24,Energy Storage Technologies and Grid Integration,"storag, batteri, energi, generat, use, capac, ..."
24,25,Power-System State Estimation and Observability,"estim, state, measur, observ, robust, use, iee..."
25,26,Distribution-System Protection and Reconfigura...,"distribut, network, fault, ieee, voltag, feede..."
26,27,Smart-Meter Analytics and Load Profiling,"load, meter, smart, consumpt, custom, cluster,..."
27,28,Energy Technology Innovation and Deployment,"technolog, develop, industri, deploy, role, ne..."
28,29,Building Energy Flexibility and Demand Response,"demand, energi, build, heat, manag, electr, re..."
29,30,Power-System Review and Synthesis Studies,"research, review, discuss, literatur, recent, ..."
30,31,Electricity Markets and Transactive Energy,"market, electr, price, particip, mechan, trade..."
31,32,Frequency Stability and Converter-Dominated Gr...,"frequenc, system, stabil, respons, dynam, gene..."
32,33,Wind-Turbine Wakes and Wind-Farm Aerodynamics,"wind, turbin, farm, wake, speed, offshor, blad..."
33,34,Probabilistic Renewable-Energy Forecasting,"forecast, predict, model, uncertainti, error, ..."
34,35,Solar Irradiance Measurement and Resource Asse...,"solar, irradi, radiat, measur, use, cloud, sur..."
35,36,Power-System Computational and Assessment Methods,"method, propos, base, use, techniqu, appli, ap..."
36,37,"Energy Transition, Communities, and Energy Jus...","energi, transit, communiti, develop, local, st..."
37,38,"Energy Materials, Batteries, and Electrochemic...","materi, hydrogen, cell, process, product, high..."
38,39,Dynamic Line Rating and Transmission Capacity,"transmiss, line, current, use, transform, high..."
39,40,Microgrid and Converter Control Strategies,"control, propos, strategi, scheme, can, simul,..."
40,41,"Carbon Emissions, Fuels, and Decarbonization","emiss, gas, fuel, carbon, reduc, environment, ..."
41,42,Renewable-Energy Technologies and Policy,"energi, renew, sourc, resourc, increas, share,..."
42,43,Energy-System Costs and Economic Assessment,"cost, reduc, valu, benefit, reduct, econom, re..."
43,44,Machine Learning for Power-System Monitoring a...,"time, algorithm, use, perform, base, approach,..."
44,45,Power Electronics and Converter Technologies,"voltag, convert, invert, current, ieee, presen..."
45,46,Future Grid Technologies and Electricity Demand,"will, need, futur, new, increas, requir, year,..."
46,47,Grid Resilience and Extreme-Event Risk,"event, resili, failur, risk, reliabl, sever, e..."
47,48,"Solar-PV Performance, Soiling, and Maintenance","solar, plant, photovolta, instal, modul, loss,..."
48,49,Grid Technology and System Integration Methods,"can, first, two, use, larg, second, allow, one..."
49,50,Energy Data Analytics and Anomaly Detection,"data, use, detect, inform, avail, set, center,..."

SCOPUS
======

,Topic,Topic_Label,Top_Terms
0,1,Neural Networks and Physics-Informed Learning,"network, neural, train, use, predict, deep, ar..."
1,2,Voltage and Reactive Power Control,"voltag, loss, reactiv, activ, bus, ieee, regul..."
2,3,Power-System State Estimation,"estim, state, measur, paramet, method, use, ac..."
3,4,Electricity Markets and Peer-to-Peer Energy Tr...,"market, energi, price, electr, trade, mechan, ..."
4,5,"Grid Reliability, Risk, and Stability Challenges","can, will, due, issu, one, also, howev, may, m..."
5,6,Data-Driven and Linear Power-Flow Modeling,"model, develop, propos, simul, linear, datadri..."
6,7,Microgrid Operation and Energy Management,"microgrid, oper, manag, system, generat, mode,..."
7,8,Power-System Engineering Applications,"system, reserv, ltd, engin, right, publish, te..."
8,9,Digitalization and Intelligent Energy Systems,"technolog, energi, intellig, sustain, artifici..."
9,10,Metaheuristic Optimization Methods,"techniqu, use, differ, perform, various, sugge..."
10,11,Grid Flexibility and TSO-DSO Coordination,"oper, flexibl, coordin, system, level, provid,..."
11,12,Power-System Optimization Frameworks and Valid...,"framework, across, limit, practic, deploy, int..."
12,13,FACTS Device Placement and Optimization,"system, optim, devic, locat, use, size, improv..."
13,14,Distribution-System Planning and Evaluation Me...,"first, base, second, final, propos, stage, cha..."
14,15,Renewable Generation and Siting Assessment,"solar, photovolta, generat, capac, studi, plan..."
15,16,Energy and Power Forecasting,"forecast, predict, model, error, accuraci, mea..."
16,17,Smart-Grid Technologies and Applications,"grid, smart, provid, develop, challeng, increa..."
17,18,Multi-Objective and Evolutionary Optimization,"algorithm, function, optim, object, problem, m..."
18,19,Energy Efficiency and Decarbonization,"energi, emiss, build, carbon, thermal, heat, g..."
19,20,Cost and Loss Optimization in Power Systems,"cost, reduc, optim, minim, reduct, achiev, tot..."
20,21,Distributed Optimization and ADMM,"distribut, direct, algorithm, altern, central,..."
21,22,Demand-Side Management and Demand Response,"load, demand, electr, respons, peak, consumpt,..."
22,23,Quantum Computing for Power-System Optimization,"comput, effici, time, complex, requir, solut, ..."
23,24,Data-Driven Power-System Analysis and Security...,"use, result, present, case, time, two, test, o..."
24,25,"Robust, Stochastic, and Probabilistic Optimiza...","uncertainti, robust, scenario, stochast, propo..."
25,26,Cybersecurity and False-Data Injection Attacks,"system, attack, secur, detect, data, communic,..."
26,27,Electric-Vehicle Charging and Infrastructure P...,"electr, charg, vehicl, station, transport, str..."
27,28,Economic Dispatch and Unit Scheduling,"dispatch, schedul, oper, unit, generat, econom..."
28,29,Graph Neural Networks and Topology-Aware Learning,"topolog, graph, physic, featur, structur, atte..."
29,30,Safe and Physics-Informed Reinforcement Learning,"reinforc, deep, agent, polici, decis, realtim,..."
30,31,Active Distribution Networks and DER Integration,"distribut, network, der, resourc, node, activ,..."
31,32,Mathematical Programming and OPF Solution Methods,"problem, solut, solv, opf, optim, constraint, ..."
32,33,Power-System Stability and Oscillation Control,"system, stabil, transient, dynam, analysi, ass..."
33,34,Power-System Planning and Reliability Studies,"system, plan, natur, author, oper, part, prese..."
34,35,Power Electronics and Converter Systems,"convert, current, qualiti, harmon, voltag, hig..."
35,36,Transmission Security and Contingency Assessment,"system, bus, ieee, transmiss, line, secur, tes..."
36,37,Renewable-Energy Integration and Management,"energi, renew, sourc, integr, manag, system, r..."
37,38,Battery and Hybrid Energy Storage Systems,"energi, storag, system, batteri, hybrid, manag..."
38,39,Data-Driven Smart-Energy Methods,"enhanc, effici, challeng, address, signific, i..."
39,40,Grid Resilience and Cascading-Failure Risk,"reliabl, system, resili, assess, failur, risk,..."
40,41,"Fault Detection, Classification, and Protection","fault, protect, detect, classif, current, sche..."
41,42,Metaheuristic Optimization Algorithms,"algorithm, problem, search, converg, optim, te..."
42,43,Power-System Engineering and Technology Applic...,"applic, design, system, research, develop, pro..."
43,44,Power-Flow and Network Calculation Methods,"method, propos, base, calcul, paper, can, effe..."
44,45,Photovoltaic MPPT and Adaptive Control,"adapt, dynam, condit, effici, improv, perform,..."
45,46,Load-Frequency Control and Frequency Regulation,"control, frequenc, strategi, regul, scheme, sy..."
46,47,Wind-Power Modeling and Prediction,"wind, generat, output, use, speed, result, var..."
47,48,Hybrid Computational Optimization Methods,"propos, approach, result, novel, compar, simul..."
48,49,Power-System Data Analytics and Synthetic Data,"data, cluster, use, process, analysi, inform, ..."
49,50,Bibliometric and Systematic Review Studies,"research, review, applic, futur, provid, discu..."

In [60]:
for corpus_name, interpretation in (
    topic_interpretation_tables.items()
):

    output_file = (
        INTERPRETATION_DIR
        / f"{corpus_name}_topic_interpretation_labeled.csv"
    )

    interpretation.to_csv(
        output_file,
        index=False,
        encoding="utf-8",
    )

    print(
        f"{corpus_name.upper():8s}: "
        f"{output_file}"
    )

OVERTON : /nfs/mfirdausi/project/review_paper_2/output/topic_interpretation/overton_topic_interpretation_labeled.csv
SCOPUS  : /nfs/mfirdausi/project/review_paper_2/output/topic_interpretation/scopus_topic_interpretation_labeled.csv

### 7.2 Topic Prevalence

Topic prevalence is calculated from the complete document-topic
probability distribution. For topic \(k\), prevalence is defined as
the mean topic probability across all documents in the corresponding
corpus. This probability-weighted measure preserves the mixed-membership
structure of LDA rather than assigning each publication exclusively to
its dominant topic.

In [61]:
topic_prevalence_tables = {}

for corpus_name in [
    "overton",
    "scopus",
]:

    prevalence = (
        final_lda[
            corpus_name
        ]["prevalence"]
        .copy()
    )

    # Add human-readable topic labels.
    prevalence[
        "Topic_Label"
    ] = (
        prevalence["Topic"]
        .map(
            topic_label_maps[
                corpus_name
            ]
        )
    )

    # Convert mean probability to percentage.
    prevalence[
        "Prevalence_Percent"
    ] = (
        prevalence[
            "Mean_Probability"
        ]
        * 100
    )

    prevalence = (
        prevalence
        .sort_values(
            "Prevalence_Percent",
            ascending=False,
        )
        .reset_index(drop=True)
    )

    prevalence[
        "Rank"
    ] = (
        prevalence.index
        + 1
    )

    prevalence = prevalence[
        [
            "Rank",
            "Topic",
            "Topic_Label",
            "Mean_Probability",
            "Prevalence_Percent",
        ]
    ]

    topic_prevalence_tables[
        corpus_name
    ] = prevalence

    print()
    print(corpus_name.upper())
    print("=" * len(corpus_name))

    print(
        "Total prevalence:",
        f"{prevalence['Prevalence_Percent'].sum():.6f}%"
    )

    display(
        prevalence.head(15)
    )

OVERTON
=======
Total prevalence: 100.000000%

,Rank,Topic,Topic_Label,Mean_Probability,Prevalence_Percent
0,1,22,Convex Relaxations and Mathematical Programmin...,0.022991,2.299056
1,2,26,Distribution-System Protection and Reconfigura...,0.022732,2.273240
2,3,33,Wind-Turbine Wakes and Wind-Farm Aerodynamics,0.022186,2.218621
3,4,30,Power-System Review and Synthesis Studies,0.022112,2.211217
4,5,35,Solar Irradiance Measurement and Resource Asse...,0.021932,2.193161
5,6,45,Power Electronics and Converter Technologies,0.021335,2.133460
6,7,42,Renewable-Energy Technologies and Policy,0.021218,2.121834
7,8,11,Smart-Grid Communications and Cybersecurity,0.021180,2.117991
8,9,25,Power-System State Estimation and Observability,0.021153,2.115275
9,10,17,Power-System Modeling and Simulation,0.020848,2.084812
10,11,20,Distributed Microgrid Control and Multi-Agent ...,0.020840,2.083982
11,12,8,Electricity-Sector Policy and Market Reform,0.020556,2.055617
12,13,27,Smart-Meter Analytics and Load Profiling,0.020521,2.052129
13,14,38,"Energy Materials, Batteries, and Electrochemic...",0.020458,2.045782
14,15,28,Energy Technology Innovation and Deployment,0.020441,2.044082

SCOPUS
======
Total prevalence: 100.000000%

,Rank,Topic,Topic_Label,Mean_Probability,Prevalence_Percent
0,1,50,Bibliometric and Systematic Review Studies,0.024941,2.494135
1,2,32,Mathematical Programming and OPF Solution Methods,0.024178,2.417817
2,3,9,Digitalization and Intelligent Energy Systems,0.022733,2.273343
3,4,42,Metaheuristic Optimization Algorithms,0.022492,2.249235
4,5,37,Renewable-Energy Integration and Management,0.021736,2.173618
5,6,39,Data-Driven Smart-Energy Methods,0.021723,2.172327
6,7,21,Distributed Optimization and ADMM,0.021484,2.148377
7,8,16,Energy and Power Forecasting,0.021466,2.146579
8,9,18,Multi-Objective and Evolutionary Optimization,0.021435,2.143512
9,10,5,"Grid Reliability, Risk, and Stability Challenges",0.021154,2.115357
10,11,31,Active Distribution Networks and DER Integration,0.020784,2.078429
11,12,12,Power-System Optimization Frameworks and Valid...,0.020640,2.064008
12,13,46,Load-Frequency Control and Frequency Regulation,0.020527,2.052659
13,14,24,Data-Driven Power-System Analysis and Security...,0.020486,2.048619
14,15,43,Power-System Engineering and Technology Applic...,0.020109,2.010860

In [62]:
PREVALENCE_DIR = (
    OUTPUT_DIR
    / "topic_prevalence"
)

PREVALENCE_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

for corpus_name, prevalence in (
    topic_prevalence_tables.items()
):

    output_file = (
        PREVALENCE_DIR
        / f"{corpus_name}_topic_prevalence.csv"
    )

    prevalence.to_csv(
        output_file,
        index=False,
        encoding="utf-8",
    )

    print(
        f"{corpus_name.upper():8s}: "
        f"{output_file}"
    )

OVERTON : /nfs/mfirdausi/project/review_paper_2/output/topic_prevalence/overton_topic_prevalence.csv
SCOPUS  : /nfs/mfirdausi/project/review_paper_2/output/topic_prevalence/scopus_topic_prevalence.csv

In [63]:
for corpus_name, prevalence in (
    topic_prevalence_tables.items()
):

    print()
    print(corpus_name.upper())
    print("-" * len(corpus_name))

    for n in [
        5,
        10,
        20,
    ]:

        cumulative_share = (
            prevalence[
                "Prevalence_Percent"
            ]
            .head(n)
            .sum()
        )

        print(
            f"Top {n:2d} topics : "
            f"{cumulative_share:.2f}%"
        )

    print(
        "\nLargest topic  :",
        f"{prevalence['Prevalence_Percent'].max():.2f}%"
    )

    print(
        "Smallest topic :",
        f"{prevalence['Prevalence_Percent'].min():.2f}%"
    )

    print(
        "Mean topic     :",
        f"{prevalence['Prevalence_Percent'].mean():.2f}%"
    )

    print(
        "Median topic   :",
        f"{prevalence['Prevalence_Percent'].median():.2f}%"
    )

OVERTON
-------
Top  5 topics : 11.20%
Top 10 topics : 21.77%
Top 20 topics : 42.22%

Largest topic  : 2.30%
Smallest topic : 1.83%
Mean topic     : 2.00%
Median topic   : 1.97%

SCOPUS
------
Top  5 topics : 11.61%
Top 10 topics : 22.33%
Top 20 topics : 42.58%

Largest topic  : 2.49%
Smallest topic : 1.79%
Mean topic     : 2.00%
Median topic   : 1.97%

In [64]:
overton_top10 = (
    topic_prevalence_tables[
        "overton"
    ]
    .head(10)
    [
        [
            "Rank",
            "Topic",
            "Topic_Label",
            "Prevalence_Percent",
        ]
    ]
    .copy()
)

scopus_top10 = (
    topic_prevalence_tables[
        "scopus"
    ]
    .head(10)
    [
        [
            "Rank",
            "Topic",
            "Topic_Label",
            "Prevalence_Percent",
        ]
    ]
    .copy()
)

print("OVERTON — Top 10 Topics")
display(
    overton_top10
)

print("SCOPUS — Top 10 Topics")
display(
    scopus_top10
)

OVERTON — Top 10 Topics

,Rank,Topic,Topic_Label,Prevalence_Percent
0,1,22,Convex Relaxations and Mathematical Programmin...,2.299056
1,2,26,Distribution-System Protection and Reconfigura...,2.273240
2,3,33,Wind-Turbine Wakes and Wind-Farm Aerodynamics,2.218621
3,4,30,Power-System Review and Synthesis Studies,2.211217
4,5,35,Solar Irradiance Measurement and Resource Asse...,2.193161
5,6,45,Power Electronics and Converter Technologies,2.133460
6,7,42,Renewable-Energy Technologies and Policy,2.121834
7,8,11,Smart-Grid Communications and Cybersecurity,2.117991
8,9,25,Power-System State Estimation and Observability,2.115275
9,10,17,Power-System Modeling and Simulation,2.084812

SCOPUS — Top 10 Topics

,Rank,Topic,Topic_Label,Prevalence_Percent
0,1,50,Bibliometric and Systematic Review Studies,2.494135
1,2,32,Mathematical Programming and OPF Solution Methods,2.417817
2,3,9,Digitalization and Intelligent Energy Systems,2.273343
3,4,42,Metaheuristic Optimization Algorithms,2.249235
4,5,37,Renewable-Energy Integration and Management,2.173618
5,6,39,Data-Driven Smart-Energy Methods,2.172327
6,7,21,Distributed Optimization and ADMM,2.148377
7,8,16,Energy and Power Forecasting,2.146579
8,9,18,Multi-Objective and Evolutionary Optimization,2.143512
9,10,5,"Grid Reliability, Risk, and Stability Challenges",2.115357

### 7.3 Cross-Corpus Meta-Theme Mapping

Because the Overton and Scopus LDA models were estimated independently,
topic identifiers and thematic boundaries are not directly comparable
across corpora. The 50 latent topics from each corpus are therefore
mapped to a common set of higher-level research meta-themes based on
their interpreted topic labels, top terms, and representative
publications.

The latent-topic probabilities are subsequently aggregated within each
meta-theme, preserving the complete mixed-membership topic
distributions while enabling direct comparison between the
policy-facing and academic corpora.

In [70]:
META_THEMES = [
    "Optimization and Computational Methods",
    "Machine Learning and Data-Driven Methods",
    "Power-System Operation, Stability, and Reliability",
    "Distribution Systems, Microgrids, and Smart Grids",
    "Renewable Energy and Resource Integration",
    "Energy Storage and Electric Vehicles",
    "Markets, Flexibility, and Demand Response",
    "Power Electronics and Grid Technologies",
    "Climate, Environment, and Decarbonization",
    "Policy, Society, and Energy Transition",
    "Cross-Cutting and Review Studies",
]

print(
    "Number of common meta-themes:",
    len(META_THEMES)
)

for i, theme in enumerate(
    META_THEMES,
    start=1,
):
    print(
        f"{i:2d}. {theme}"
    )

Number of common meta-themes: 11
 1. Optimization and Computational Methods
 2. Machine Learning and Data-Driven Methods
 3. Power-System Operation, Stability, and Reliability
 4. Distribution Systems, Microgrids, and Smart Grids
 5. Renewable Energy and Resource Integration
 6. Energy Storage and Electric Vehicles
 7. Markets, Flexibility, and Demand Response
 8. Power Electronics and Grid Technologies
 9. Climate, Environment, and Decarbonization
10. Policy, Society, and Energy Transition
11. Cross-Cutting and Review Studies

In [71]:
overton_meta_theme_map = {

    # -----------------------------------------------------
    # Optimization and computational methods
    # -----------------------------------------------------
    7: "Optimization and Computational Methods",
    22: "Optimization and Computational Methods",
    36: "Optimization and Computational Methods",

    # -----------------------------------------------------
    # Machine learning and data-driven methods
    # -----------------------------------------------------
    27: "Machine Learning and Data-Driven Methods",
    44: "Machine Learning and Data-Driven Methods",
    50: "Machine Learning and Data-Driven Methods",

    # -----------------------------------------------------
    # Operation, stability and reliability
    # -----------------------------------------------------
    10: "Power-System Operation, Stability, and Reliability",
    17: "Power-System Operation, Stability, and Reliability",
    21: "Power-System Operation, Stability, and Reliability",
    25: "Power-System Operation, Stability, and Reliability",
    32: "Power-System Operation, Stability, and Reliability",
    47: "Power-System Operation, Stability, and Reliability",

    # -----------------------------------------------------
    # Distribution, microgrids and smart grids
    # -----------------------------------------------------
    5: "Distribution Systems, Microgrids, and Smart Grids",
    11: "Distribution Systems, Microgrids, and Smart Grids",
    20: "Distribution Systems, Microgrids, and Smart Grids",
    26: "Distribution Systems, Microgrids, and Smart Grids",

    # -----------------------------------------------------
    # Renewable energy and resource integration
    # -----------------------------------------------------
    2: "Renewable Energy and Resource Integration",
    16: "Renewable Energy and Resource Integration",
    23: "Renewable Energy and Resource Integration",
    33: "Renewable Energy and Resource Integration",
    34: "Renewable Energy and Resource Integration",
    35: "Renewable Energy and Resource Integration",
    42: "Renewable Energy and Resource Integration",
    48: "Renewable Energy and Resource Integration",

    # -----------------------------------------------------
    # Storage and electric vehicles
    # -----------------------------------------------------
    12: "Energy Storage and Electric Vehicles",
    24: "Energy Storage and Electric Vehicles",
    38: "Energy Storage and Electric Vehicles",

    # -----------------------------------------------------
    # Markets, flexibility and demand response
    # -----------------------------------------------------
    1: "Markets, Flexibility, and Demand Response",
    13: "Markets, Flexibility, and Demand Response",
    29: "Markets, Flexibility, and Demand Response",
    31: "Markets, Flexibility, and Demand Response",
    43: "Markets, Flexibility, and Demand Response",

    # -----------------------------------------------------
    # Power electronics and grid technologies
    # -----------------------------------------------------
    4: "Power Electronics and Grid Technologies",
    39: "Power Electronics and Grid Technologies",
    40: "Power Electronics and Grid Technologies",
    45: "Power Electronics and Grid Technologies",
    49: "Power Electronics and Grid Technologies",

    # -----------------------------------------------------
    # Climate/environment/decarbonization
    # -----------------------------------------------------
    3: "Climate, Environment, and Decarbonization",
    15: "Climate, Environment, and Decarbonization",
    18: "Climate, Environment, and Decarbonization",
    41: "Climate, Environment, and Decarbonization",

    # -----------------------------------------------------
    # Policy, society and transition
    # -----------------------------------------------------
    8: "Policy, Society, and Energy Transition",
    9: "Policy, Society, and Energy Transition",
    19: "Policy, Society, and Energy Transition",
    28: "Policy, Society, and Energy Transition",
    37: "Policy, Society, and Energy Transition",
    46: "Policy, Society, and Energy Transition",

    # -----------------------------------------------------
    # Cross-cutting/reviews
    # -----------------------------------------------------
    6: "Cross-Cutting and Review Studies",
    14: "Cross-Cutting and Review Studies",
    30: "Cross-Cutting and Review Studies",
}

In [76]:
scopus_meta_theme_map = {

    # -----------------------------------------------------
    # Optimization and computational methods
    # -----------------------------------------------------
    10: "Optimization and Computational Methods",
    12: "Optimization and Computational Methods",
    13: "Optimization and Computational Methods",
    18: "Optimization and Computational Methods",
    20: "Optimization and Computational Methods",
    21: "Optimization and Computational Methods",
    23: "Optimization and Computational Methods",
    25: "Optimization and Computational Methods",
    28: "Optimization and Computational Methods",
    32: "Optimization and Computational Methods",
    42: "Optimization and Computational Methods",
    44: "Optimization and Computational Methods",
    48: "Optimization and Computational Methods",

    # -----------------------------------------------------
    # Machine learning and data-driven methods
    # -----------------------------------------------------
    1: "Machine Learning and Data-Driven Methods",
    3: "Machine Learning and Data-Driven Methods",
    6: "Machine Learning and Data-Driven Methods",
    16: "Machine Learning and Data-Driven Methods",
    24: "Machine Learning and Data-Driven Methods",
    29: "Machine Learning and Data-Driven Methods",
    30: "Machine Learning and Data-Driven Methods",
    39: "Machine Learning and Data-Driven Methods",
    49: "Machine Learning and Data-Driven Methods",

    # -----------------------------------------------------
    # Operation, stability and reliability
    # -----------------------------------------------------
    2: "Power-System Operation, Stability, and Reliability",
    5: "Power-System Operation, Stability, and Reliability",
    33: "Power-System Operation, Stability, and Reliability",
    36: "Power-System Operation, Stability, and Reliability",
    40: "Power-System Operation, Stability, and Reliability",
    41: "Power-System Operation, Stability, and Reliability",
    46: "Power-System Operation, Stability, and Reliability",
    26: "Power-System Operation, Stability, and Reliability",

    # -----------------------------------------------------
    # Distribution, microgrids and smart grids
    # -----------------------------------------------------
    7: "Distribution Systems, Microgrids, and Smart Grids",
    17: "Distribution Systems, Microgrids, and Smart Grids",
    31: "Distribution Systems, Microgrids, and Smart Grids",

    # -----------------------------------------------------
    # Renewable energy and resource integration
    # -----------------------------------------------------
    15: "Renewable Energy and Resource Integration",
    37: "Renewable Energy and Resource Integration",
    45: "Renewable Energy and Resource Integration",
    47: "Renewable Energy and Resource Integration",

    # -----------------------------------------------------
    # Storage and EV
    # -----------------------------------------------------
    27: "Energy Storage and Electric Vehicles",
    38: "Energy Storage and Electric Vehicles",

    # -----------------------------------------------------
    # Markets/flexibility/demand response
    # -----------------------------------------------------
    4: "Markets, Flexibility, and Demand Response",
    11: "Markets, Flexibility, and Demand Response",
    22: "Markets, Flexibility, and Demand Response",

    # -----------------------------------------------------
    # Power electronics/grid technologies
    # -----------------------------------------------------
    35: "Power Electronics and Grid Technologies",

    # -----------------------------------------------------
    # Climate/environment/decarbonization
    # -----------------------------------------------------
    19: "Climate, Environment, and Decarbonization",

    # -----------------------------------------------------
    # Policy/society/transition
    # -----------------------------------------------------
    9: "Policy, Society, and Energy Transition",

    # -----------------------------------------------------
    # Cross-cutting/reviews
    # -----------------------------------------------------
    8: "Cross-Cutting and Review Studies",
    14: "Cross-Cutting and Review Studies",
    34: "Cross-Cutting and Review Studies",
    43: "Cross-Cutting and Review Studies",
    50: "Cross-Cutting and Review Studies",
}

In [77]:
meta_theme_maps = {
    "overton": overton_meta_theme_map,
    "scopus": scopus_meta_theme_map,
}

for corpus_name, mapping in (
    meta_theme_maps.items()
):

    expected_topics = set(
        range(1, 51)
    )

    mapped_topics = set(
        mapping.keys()
    )

    missing = sorted(
        expected_topics
        - mapped_topics
    )

    extra = sorted(
        mapped_topics
        - expected_topics
    )

    print(corpus_name.upper())
    print("-" * len(corpus_name))

    print(
        "Mapped topics :",
        len(mapped_topics)
    )

    print(
        "Missing       :",
        missing
    )

    print(
        "Extra         :",
        extra
    )

    print()

OVERTON
-------
Mapped topics : 50
Missing       : []
Extra         : []

SCOPUS
------
Mapped topics : 50
Missing       : []
Extra         : []

In [78]:
# ---------------------------------------------------------
# Create mapping tables
# ---------------------------------------------------------

meta_theme_mapping_tables = {}

for corpus_name in [
    "overton",
    "scopus",
]:

    mapping_df = (
        topic_interpretation_tables[
            corpus_name
        ][
            [
                "Topic",
                "Topic_Label",
            ]
        ]
        .copy()
    )

    mapping_df[
        "Meta_Theme"
    ] = (
        mapping_df["Topic"]
        .map(
            meta_theme_maps[
                corpus_name
            ]
        )
    )

    mapping_df = (
        mapping_df
        .sort_values(
            [
                "Meta_Theme",
                "Topic",
            ]
        )
        .reset_index(drop=True)
    )

    meta_theme_mapping_tables[
        corpus_name
    ] = mapping_df


# ---------------------------------------------------------
# Save mappings
# ---------------------------------------------------------

META_THEME_DIR = (
    OUTPUT_DIR
    / "meta_theme_analysis"
)

META_THEME_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

for corpus_name, mapping_df in (
    meta_theme_mapping_tables.items()
):

    output_file = (
        META_THEME_DIR
        / f"{corpus_name}_topic_to_meta_theme.csv"
    )

    mapping_df.to_csv(
        output_file,
        index=False,
        encoding="utf-8",
    )

    print(
        f"{corpus_name.upper():8s}: "
        f"{len(mapping_df)} topics saved"
    )

    print(
        "  ",
        output_file
    )

OVERTON : 50 topics saved
   /nfs/mfirdausi/project/review_paper_2/output/meta_theme_analysis/overton_topic_to_meta_theme.csv
SCOPUS  : 50 topics saved
   /nfs/mfirdausi/project/review_paper_2/output/meta_theme_analysis/scopus_topic_to_meta_theme.csv

In [79]:
for corpus_name in [
    "overton",
    "scopus",
]:

    saved_file = (
        META_THEME_DIR
        / f"{corpus_name}_topic_to_meta_theme.csv"
    )

    check_df = pd.read_csv(
        saved_file
    )

    print(
        f"{corpus_name.upper():8s} | "
        f"Rows: {len(check_df)} | "
        f"Missing labels: "
        f"{check_df['Topic_Label'].isna().sum()} | "
        f"Missing meta-themes: "
        f"{check_df['Meta_Theme'].isna().sum()}"
    )

OVERTON  | Rows: 50 | Missing labels: 0 | Missing meta-themes: 0
SCOPUS   | Rows: 50 | Missing labels: 0 | Missing meta-themes: 0

In [80]:
meta_theme_prevalence = {}

for corpus_name in [
    "overton",
    "scopus",
]:

    # Topic-level prevalence
    prevalence = (
        topic_prevalence_tables[
            corpus_name
        ][
            [
                "Topic",
                "Topic_Label",
                "Prevalence_Percent",
            ]
        ]
        .copy()
    )

    # Topic -> meta-theme mapping
    mapping = (
        meta_theme_mapping_tables[
            corpus_name
        ][
            [
                "Topic",
                "Meta_Theme",
            ]
        ]
        .copy()
    )

    # -----------------------------------------------------
    # Merge
    # -----------------------------------------------------

    merged = (
        prevalence
        .merge(
            mapping,
            on="Topic",
            how="left",
            validate="one_to_one",
        )
    )

    if merged["Meta_Theme"].isna().any():
        raise ValueError(
            f"Missing meta-theme assignments "
            f"for {corpus_name}"
        )

    # -----------------------------------------------------
    # Aggregate prevalence
    # -----------------------------------------------------

    aggregated = (
        merged
        .groupby(
            "Meta_Theme",
            as_index=False,
        )["Prevalence_Percent"]
        .sum()
        .rename(
            columns={
                "Prevalence_Percent":
                "Meta_Theme_Prevalence"
            }
        )
        .sort_values(
            "Meta_Theme_Prevalence",
            ascending=False,
        )
        .reset_index(drop=True)
    )

    aggregated["Rank"] = (
        aggregated.index + 1
    )

    meta_theme_prevalence[
        corpus_name
    ] = aggregated

    print()
    print(corpus_name.upper())
    print("=" * len(corpus_name))

    print(
        "Total prevalence:",
        f"{aggregated['Meta_Theme_Prevalence'].sum():.6f}%"
    )

    display(
        aggregated[
            [
                "Rank",
                "Meta_Theme",
                "Meta_Theme_Prevalence",
            ]
        ]
    )

OVERTON
=======
Total prevalence: 100.000000%

,Rank,Meta_Theme,Meta_Theme_Prevalence
0,1,Renewable Energy and Resource Integration,16.232708
1,2,"Power-System Operation, Stability, and Reliabi...",12.137651
2,3,"Policy, Society, and Energy Transition",11.877667
3,4,Power Electronics and Grid Technologies,9.795837
4,5,"Markets, Flexibility, and Demand Response",9.650724
5,6,"Distribution Systems, Microgrids, and Smart Grids",8.460937
6,7,"Climate, Environment, and Decarbonization",7.844959
7,8,Optimization and Computational Methods,6.267905
8,9,Cross-Cutting and Review Studies,6.015329
9,10,Machine Learning and Data-Driven Methods,5.910540
10,11,Energy Storage and Electric Vehicles,5.805742

SCOPUS
======
Total prevalence: 100.000000%

,Rank,Meta_Theme,Meta_Theme_Prevalence
0,1,Optimization and Computational Methods,26.884539
1,2,Machine Learning and Data-Driven Methods,17.937459
2,3,"Power-System Operation, Stability, and Reliabi...",15.609353
3,4,Cross-Cutting and Review Studies,10.089870
4,5,Renewable Energy and Resource Integration,7.890067
5,6,"Distribution Systems, Microgrids, and Smart Grids",5.831549
6,7,"Markets, Flexibility, and Demand Response",5.771897
7,8,Energy Storage and Electric Vehicles,3.842298
8,9,"Policy, Society, and Energy Transition",2.273343
9,10,"Climate, Environment, and Decarbonization",1.943472
10,11,Power Electronics and Grid Technologies,1.926153

In [81]:
overton_meta = (
    meta_theme_prevalence[
        "overton"
    ][
        [
            "Meta_Theme",
            "Meta_Theme_Prevalence",
        ]
    ]
    .rename(
        columns={
            "Meta_Theme_Prevalence":
            "Overton_Percent"
        }
    )
)

scopus_meta = (
    meta_theme_prevalence[
        "scopus"
    ][
        [
            "Meta_Theme",
            "Meta_Theme_Prevalence",
        ]
    ]
    .rename(
        columns={
            "Meta_Theme_Prevalence":
            "Scopus_Percent"
        }
    )
)

meta_theme_comparison = (
    overton_meta
    .merge(
        scopus_meta,
        on="Meta_Theme",
        how="outer",
        validate="one_to_one",
    )
)

# Percentage-point difference:
# positive = relatively greater Overton emphasis
# negative = relatively greater Scopus emphasis
meta_theme_comparison[
    "Difference_pp"
] = (
    meta_theme_comparison[
        "Overton_Percent"
    ]
    -
    meta_theme_comparison[
        "Scopus_Percent"
    ]
)

meta_theme_comparison[
    "Absolute_Difference_pp"
] = (
    meta_theme_comparison[
        "Difference_pp"
    ]
    .abs()
)

meta_theme_comparison[
    "Relative_Emphasis"
] = (
    meta_theme_comparison[
        "Difference_pp"
    ]
    .apply(
        lambda x:
        "Overton"
        if x > 0
        else (
            "Scopus"
            if x < 0
            else "Equal"
        )
    )
)

meta_theme_comparison = (
    meta_theme_comparison
    .sort_values(
        "Absolute_Difference_pp",
        ascending=False,
    )
    .reset_index(drop=True)
)

display(
    meta_theme_comparison[
        [
            "Meta_Theme",
            "Overton_Percent",
            "Scopus_Percent",
            "Difference_pp",
            "Relative_Emphasis",
        ]
    ]
)

,Meta_Theme,Overton_Percent,Scopus_Percent,Difference_pp,Relative_Emphasis
0,Optimization and Computational Methods,6.267905,26.884539,-20.616634,Scopus
1,Machine Learning and Data-Driven Methods,5.910540,17.937459,-12.026919,Scopus
2,"Policy, Society, and Energy Transition",11.877667,2.273343,9.604324,Overton
3,Renewable Energy and Resource Integration,16.232708,7.890067,8.342641,Overton
4,Power Electronics and Grid Technologies,9.795837,1.926153,7.869685,Overton
5,"Climate, Environment, and Decarbonization",7.844959,1.943472,5.901487,Overton
6,Cross-Cutting and Review Studies,6.015329,10.089870,-4.074540,Scopus
7,"Markets, Flexibility, and Demand Response",9.650724,5.771897,3.878828,Overton
8,"Power-System Operation, Stability, and Reliabi...",12.137651,15.609353,-3.471702,Scopus
9,"Distribution Systems, Microgrids, and Smart Grids",8.460937,5.831549,2.629388,Overton
10,Energy Storage and Electric Vehicles,5.805742,3.842298,1.963443,Overton

In [82]:
print(
    "Overton total:",
    f"{meta_theme_comparison['Overton_Percent'].sum():.6f}%"
)

print(
    "Scopus total :",
    f"{meta_theme_comparison['Scopus_Percent'].sum():.6f}%"
)

print(
    "Number of meta-themes:",
    len(meta_theme_comparison)
)

Overton total: 100.000000%
Scopus total : 100.000000%
Number of meta-themes: 11

In [83]:
comparison_file = (
    META_THEME_DIR
    / "overton_scopus_meta_theme_comparison.csv"
)

meta_theme_comparison.to_csv(
    comparison_file,
    index=False,
    encoding="utf-8",
)

print(
    "Saved:",
    comparison_file
)

Saved: /nfs/mfirdausi/project/review_paper_2/output/meta_theme_analysis/overton_scopus_meta_theme_comparison.csv

### 7.4 Cross-Corpus Thematic Mapping

### 7.5 Policy-Facing vs Academic Research Priorities